import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";

import type {
  EventReportSummary,
  ReportEvent,
  ReportGuest,
  ReportInvitation,
  ReportWish,
} from "@/services/reportService";

import AttendanceTable from "./AttendanceTable";
import GuestTable from "./GuestTable";
import InvitationTable from "./InvitationTable";
import SummarySection from "./SummarySection";
import { pdfStyles } from "./PdfStyles";

type EventReportPDFProps = {
  event: ReportEvent;
  summary: EventReportSummary;
  guests: ReportGuest[];
  invitations: ReportInvitation[];
  wishes: ReportWish[];
};

const wishStyles = StyleSheet.create({
  section: { marginTop: 18 },
  title: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 4,
  },
  subtitle: {
    color: "#64748b",
    fontSize: 9,
    marginBottom: 14,
  },
  summary: {
    alignItems: "center",
    backgroundColor: "#eff6ff",
    borderColor: "#bfdbfe",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  summaryLabel: {
    color: "#1e3a8a",
    fontSize: 9,
    fontWeight: 700,
  },
  summaryValue: {
    color: "#2563eb",
    fontSize: 16,
    fontWeight: 700,
  },
  list: { gap: 9 },
  card: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 7,
    borderWidth: 1,
    padding: 12,
  },
  cardHeader: {
    alignItems: "center",
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    paddingBottom: 7,
  },
  guestName: {
    color: "#0f172a",
    fontSize: 11,
    fontWeight: 700,
  },
  date: {
    color: "#64748b",
    fontSize: 8,
  },
  message: {
    color: "#334155",
    fontSize: 10,
    lineHeight: 1.55,
  },
  emptyState: {
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderStyle: "dashed",
    borderWidth: 1,
    padding: 28,
  },
  emptyTitle: {
    color: "#334155",
    fontSize: 12,
    fontWeight: 700,
  },
  emptyText: {
    color: "#64748b",
    fontSize: 9,
    marginTop: 5,
  },
});

function formatEventDate(value: string) {
  if (!value) {
    return "-";
  }

  return new Intl.DateTimeFormat("en-GB", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(new Date(`${value}T00:00:00`));
}

function formatEventTime(value: string) {
  if (!value) {
    return "-";
  }

  const [hours, minutes] = value.split(":");

  if (!hours || !minutes) {
    return value;
  }

  const date = new Date();

  date.setHours(
    Number(hours),
    Number(minutes),
    0,
    0
  );

  return new Intl.DateTimeFormat("en-GB", {
    hour: "2-digit",
    minute: "2-digit",
  }).format(date);
}

function formatGeneratedDate() {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "long",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date());
}

function formatWishDate(value: string) {
  if (!value) {
    return "-";
  }

  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(value));
}

function PageHeader({
  eventTitle,
}: {
  eventTitle: string;
}) {
  return (
    <View style={pdfStyles.pageHeader} fixed>
      <Text style={pdfStyles.pageHeaderBrand}>
        Smart Event Pass
      </Text>

      <Text style={pdfStyles.pageHeaderEvent}>
        {eventTitle}
      </Text>
    </View>
  );
}

function PageFooter() {
  return (
    <View style={pdfStyles.footer} fixed>
      <Text style={pdfStyles.footerText}>
        Generated by Smart Event Pass
      </Text>

      <Text
        style={pdfStyles.pageNumber}
        render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}`
        }
      />
    </View>
  );
}

export default function EventReportPDF({
  event,
  summary,
  guests,
  invitations,
  wishes,
}: EventReportPDFProps) {
  return (
    <Document
      title={`${event.title} Event Report`}
      author="Smart Event Pass"
      subject="Event attendance, guest, RSVP and guest wishes report"
      creator="Smart Event Pass"
    >
      {/* COVER PAGE */}
      <Page
        size="A4"
        style={pdfStyles.coverPage}
      >
        <View style={pdfStyles.coverHero}>
          <Text style={pdfStyles.brandSmall}>
            Smart Event Pass
          </Text>

          <Text style={pdfStyles.brandTitle}>
            Professional Event Report
          </Text>

          <Text style={pdfStyles.reportLabel}>
            Attendance, Guests, RSVP and Wishes
          </Text>
        </View>

        <View style={pdfStyles.coverEventSection}>
          <Text style={pdfStyles.coverEventType}>
            {event.event_type || "Event"}
          </Text>

          <Text style={pdfStyles.coverEventTitle}>
            {event.title}
          </Text>

          <View style={pdfStyles.coverMetaGrid}>
            <View style={pdfStyles.coverMetaItem}>
              <Text style={pdfStyles.metaLabel}>
                Event Date
              </Text>

              <Text style={pdfStyles.metaValue}>
                {formatEventDate(event.event_date)}
              </Text>
            </View>

            <View style={pdfStyles.coverMetaItem}>
              <Text style={pdfStyles.metaLabel}>
                Event Time
              </Text>

              <Text style={pdfStyles.metaValue}>
                {formatEventTime(event.event_time)}
              </Text>
            </View>

            <View style={pdfStyles.coverMetaItem}>
              <Text style={pdfStyles.metaLabel}>
                Venue
              </Text>

              <Text style={pdfStyles.metaValue}>
                {event.venue || "-"}
              </Text>
            </View>

            <View style={pdfStyles.coverMetaItem}>
              <Text style={pdfStyles.metaLabel}>
                Attendance
              </Text>

              <Text style={pdfStyles.metaValue}>
                {summary.attendancePercentage}%
              </Text>
            </View>
          </View>
        </View>

        <View style={pdfStyles.coverSummary}>
          <Text style={pdfStyles.coverSummaryTitle}>
            Report Summary
          </Text>

          <View style={pdfStyles.summaryGrid}>
            <View style={pdfStyles.summaryCard}>
              <Text style={pdfStyles.summaryCardLabel}>
                Total Guests
              </Text>

              <Text style={pdfStyles.summaryCardValue}>
                {summary.totalGuests}
              </Text>
            </View>

            <View style={pdfStyles.summaryCard}>
              <Text style={pdfStyles.summaryCardLabel}>
                Checked In
              </Text>

              <Text
                style={
                  pdfStyles.summaryCardValueSuccess
                }
              >
                {summary.checkedIn}
              </Text>
            </View>

            <View style={pdfStyles.summaryCard}>
              <Text style={pdfStyles.summaryCardLabel}>
                Pending
              </Text>

              <Text
                style={
                  pdfStyles.summaryCardValueWarning
                }
              >
                {summary.pending}
              </Text>
            </View>

            <View style={pdfStyles.summaryCard}>
              <Text style={pdfStyles.summaryCardLabel}>
                Invitations
              </Text>

              <Text style={pdfStyles.summaryCardValue}>
                {summary.totalInvitations}
              </Text>
            </View>

            <View style={pdfStyles.summaryCard}>
              <Text style={pdfStyles.summaryCardLabel}>
                Viewed
              </Text>

              <Text style={pdfStyles.summaryCardValue}>
                {summary.viewed}
              </Text>
            </View>

            <View style={pdfStyles.summaryCard}>
              <Text style={pdfStyles.summaryCardLabel}>
                Accepted
              </Text>

              <Text
                style={
                  pdfStyles.summaryCardValueSuccess
                }
              >
                {summary.accepted}
              </Text>
            </View>

            <View style={pdfStyles.summaryCard}>
              <Text style={pdfStyles.summaryCardLabel}>
                Maybe
              </Text>

              <Text
                style={
                  pdfStyles.summaryCardValueWarning
                }
              >
                {summary.maybe}
              </Text>
            </View>

            <View style={pdfStyles.summaryCard}>
              <Text style={pdfStyles.summaryCardLabel}>
                Declined
              </Text>

              <Text
                style={
                  pdfStyles.summaryCardValueDanger
                }
              >
                {summary.declined}
              </Text>
            </View>

            <View style={pdfStyles.summaryCard}>
              <Text style={pdfStyles.summaryCardLabel}>
                Guest Wishes
              </Text>

              <Text style={pdfStyles.summaryCardValue}>
                {wishes.length}
              </Text>
            </View>
          </View>
        </View>

        <View style={pdfStyles.generatedSection}>
          <Text style={pdfStyles.generatedText}>
            Generated on {formatGeneratedDate()}
          </Text>

          <Text style={pdfStyles.generatedBrand}>
            Smart Event Pass
          </Text>
        </View>
      </Page>

      {/* SUMMARY PAGE */}
      <Page
        size="A4"
        style={pdfStyles.page}
        wrap
      >
        <PageHeader eventTitle={event.title} />

        <SummarySection
          totalGuests={summary.totalGuests}
          checkedIn={summary.checkedIn}
          pending={summary.pending}
          attendancePercentage={
            summary.attendancePercentage
          }
          viewed={summary.viewed}
          accepted={summary.accepted}
          maybe={summary.maybe}
          declined={summary.declined}
        />

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>
            Invitation Overview
          </Text>

          <Text style={pdfStyles.sectionSubtitle}>
            General invitation and RSVP statistics.
          </Text>

          <View style={pdfStyles.statisticRow}>
            <View style={pdfStyles.statisticBox}>
              <Text style={pdfStyles.statisticLabel}>
                Total Invitations
              </Text>

              <Text style={pdfStyles.statisticValue}>
                {summary.totalInvitations}
              </Text>
            </View>

            <View style={pdfStyles.statisticBox}>
              <Text style={pdfStyles.statisticLabel}>
                Viewed
              </Text>

              <Text style={pdfStyles.statisticValue}>
                {summary.viewed}
              </Text>
            </View>

            <View style={pdfStyles.statisticBox}>
              <Text style={pdfStyles.statisticLabel}>
                Not Viewed
              </Text>

              <Text style={pdfStyles.statisticValue}>
                {summary.notViewed}
              </Text>
            </View>

            <View style={pdfStyles.statisticBoxLast}>
              <Text style={pdfStyles.statisticLabel}>
                No Response
              </Text>

              <Text style={pdfStyles.statisticValue}>
                {summary.noResponse}
              </Text>
            </View>
          </View>
        </View>

        <PageFooter />
      </Page>

      {/* ATTENDANCE REPORT */}
      <Page
        size="A4"
        orientation="landscape"
        style={pdfStyles.page}
        wrap
      >
        <PageHeader eventTitle={event.title} />

        <AttendanceTable guests={guests} />

        <PageFooter />
      </Page>

      {/* GUEST LIST */}
      <Page
        size="A4"
        orientation="landscape"
        style={pdfStyles.page}
        wrap
      >
        <PageHeader eventTitle={event.title} />

        <GuestTable guests={guests} />

        <PageFooter />
      </Page>

      {/* INVITATIONS AND RSVP */}
      <Page
        size="A4"
        orientation="landscape"
        style={pdfStyles.page}
        wrap
      >
        <PageHeader eventTitle={event.title} />

        <InvitationTable
          invitations={invitations}
        />

        <PageFooter />
      </Page>

      {/* GUEST WISHES */}
      <Page
        size="A4"
        style={pdfStyles.page}
        wrap
      >
        <PageHeader eventTitle={event.title} />

        <View style={wishStyles.section}>
          <Text style={wishStyles.title}>
            Guest Wishes
          </Text>

          <Text style={wishStyles.subtitle}>
            Messages and well wishes submitted by invited guests.
          </Text>

          <View style={wishStyles.summary}>
            <Text style={wishStyles.summaryLabel}>
              Total wishes received
            </Text>

            <Text style={wishStyles.summaryValue}>
              {wishes.length}
            </Text>
          </View>

          {wishes.length > 0 ? (
            <View style={wishStyles.list}>
              {wishes.map((wish) => (
                <View
                  key={wish.id}
                  style={wishStyles.card}
                  minPresenceAhead={40}
                >
                  <View style={wishStyles.cardHeader}>
                    <Text style={wishStyles.guestName}>
                      {wish.guest_name || "Guest"}
                    </Text>

                    <Text style={wishStyles.date}>
                      {formatWishDate(wish.updated_at)}
                    </Text>
                  </View>

                  <Text style={wishStyles.message}>
                    {wish.message}
                  </Text>
                </View>
              ))}
            </View>
          ) : (
            <View style={wishStyles.emptyState}>
              <Text style={wishStyles.emptyTitle}>
                No guest wishes received
              </Text>

              <Text style={wishStyles.emptyText}>
                Guest messages will appear here once submitted.
              </Text>
            </View>
          )}
        </View>

        <PageFooter />
      </Page>
    </Document>
  );
}