"use client";

import { useEffect, useRef, useState, type ChangeEvent, type FormEvent } from "react";
import Image from "next/image";
import EventPreviewSwitcher, { type EventPreviewData } from "./EventPreviewSwitcher";
import TemplateThumbnail from "./TemplateThumbnail";
import ThemePalettePicker, { type EventThemePalette } from "./ThemePalettePicker";
import { EVENT_TEMPLATE_OPTIONS, EVENT_WIZARD_STEP_COUNT } from "./eventFormConfig";
import { useAppLanguage } from "@/lib/i18n/useAppLanguage";
import type { EventLanguage, InvitationTemplate } from "@/services/eventService";

export type EventFormValues = {
  title:string; event_type:string; bride_name:string; groom_name:string; language:EventLanguage;
  invitation_template:InvitationTemplate; invitation_message:string; ceremony_title:string;
  ceremony_date:string; ceremony_time:string; ceremony_venue:string; ceremony_map_url:string;
  event_date:string; event_time:string; venue:string; reception_map_url:string; dress_code:string;
  theme_primary_color:string; theme_secondary_color:string; theme_accent_color:string;
};

type Copy = typeof COPY.en;
const COPY = {
  en: {
    createTitle:"Create Event", editTitle:"Edit Event", createDescription:"Build a polished invitation experience in a few focused steps.", editDescription:"Update event details and invitation presentation in a few focused steps.",
    steps:["Basic Information","Theme & Invitation Design","Wedding Ceremony","Main Event / Reception","Review"] as const,
    descriptions:["The essentials guests will see first.","Choose the invitation's visual direction.","Optional ceremony details and location.","Main event date, time and venue.","Review changes before saving."] as const,
    step:"Step", of:"of", eventTitle:"Event Title", eventType:"Event Type", bride:"Bride / Celebrant", groom:"Groom", invitationLanguage:"Invitation Language", invitationMessage:"Invitation Message", invitationMessageHint:"Optional message shown in invitation and WhatsApp previews.", dressCode:"Dress Code", coverPhoto:"Cover Photo", existingCover:"Existing cover photo", replacePhoto:"Replace photo", removePhoto:"Remove photo", restorePhoto:"Restore photo", dropPhoto:"Drop a cover photo here, or click to browse", imageLimit:"Image files up to 5 MB", selectedTheme:"Selected Theme", changeTheme:"Change Theme", chooseStyle:"Choose your invitation style", themeHint:"Selections update the local preview and are saved only when you submit.", close:"Close", ceremonyTitle:"Ceremony Title", date:"Date", time:"Time", venue:"Venue", mapLink:"Google Maps Link", receptionDate:"Reception Date", receptionTime:"Reception Time", receptionVenue:"Reception Venue", reviewChanges:"Review changes", edit:"Edit", notSet:"Not set", hosts:"Hosts / Celebrants", language:"Language", theme:"Theme", ceremony:"Ceremony", reception:"Reception", cover:"Cover", noCover:"No cover photo", newCover:"New cover photo", currentCover:"Existing cover photo", cancel:"Cancel", create:"Create Event", creating:"Creating Event…", save:"Save Changes", saving:"Saving Changes…", unsaved:"Unsaved changes", saved:"Event updated successfully", preview:"Preview", photoType:"Please select an image file.", photoSize:"The image must not exceed 5 MB.", required:"Complete the required event and reception fields.",
  },
  sw: {
    createTitle:"Tengeneza Event", editTitle:"Hariri Event", createDescription:"Tengeneza invitation yenye muonekano bora kwa hatua chache.", editDescription:"Badilisha taarifa na muonekano wa event yako kwa hatua chache.",
    steps:["Taarifa za Msingi","Theme na Muonekano wa Mwaliko","Ibada ya Ndoa","Event Kuu / Reception","Hakiki"] as const,
    descriptions:["Taarifa muhimu ambazo wageni wataona kwanza.","Chagua muonekano wa invitation.","Taarifa za hiari za ibada na eneo.","Tarehe, muda na eneo la event kuu.","Hakiki mabadiliko kabla ya kuhifadhi."] as const,
    step:"Hatua", of:"kati ya", eventTitle:"Jina la Event", eventType:"Aina ya Event", bride:"Bibi Harusi / Mhusika", groom:"Bwana Harusi", invitationLanguage:"Lugha ya Invitation", invitationMessage:"Ujumbe wa Mwaliko", invitationMessageHint:"Ujumbe wa hiari unaoonekana kwenye invitation na WhatsApp preview.", dressCode:"Dress Code", coverPhoto:"Picha ya Cover", existingCover:"Picha ya cover iliyopo", replacePhoto:"Badilisha picha", removePhoto:"Ondoa picha", restorePhoto:"Rudisha picha", dropPhoto:"Dondosha picha hapa, au bofya kuchagua", imageLimit:"Picha zisizozidi MB 5", selectedTheme:"Theme Iliyochaguliwa", changeTheme:"Badilisha Theme", chooseStyle:"Chagua muonekano wa invitation", themeHint:"Mabadiliko yanaonekana kwenye preview na yatahifadhiwa tu ukibonyeza kuhifadhi.", close:"Funga", ceremonyTitle:"Jina la Ibada", date:"Tarehe", time:"Muda", venue:"Eneo", mapLink:"Kiungo cha Google Maps", receptionDate:"Tarehe ya Reception", receptionTime:"Muda wa Reception", receptionVenue:"Eneo la Reception", reviewChanges:"Hakiki mabadiliko", edit:"Hariri", notSet:"Haijawekwa", hosts:"Wahusika", language:"Lugha", theme:"Theme", ceremony:"Ibada", reception:"Reception", cover:"Cover", noCover:"Hakuna picha ya cover", newCover:"Picha mpya ya cover", currentCover:"Picha ya cover iliyopo", cancel:"Ghairi", create:"Tengeneza Event", creating:"Inatengeneza Event…", save:"Hifadhi Mabadiliko", saving:"Inahifadhi Mabadiliko…", unsaved:"Mabadiliko hayajahifadhiwa", saved:"Event imebadilishwa vizuri", preview:"Preview", photoType:"Tafadhali chagua file la picha.", photoSize:"Picha isizidi MB 5.", required:"Kamilisha taarifa muhimu za event na reception.",
  },
} satisfies Record<"en"|"sw",Record<string,unknown>>;

type Props = {
  mode:"create"|"edit"; values:EventFormValues; onValuesChange:(values:EventFormValues)=>void;
  currentCoverUrl?:string|null; coverFile:File|null; coverPreviewUrl:string; coverRemoved:boolean;
  onCoverFile:(file:File|null,previewUrl:string)=>void; onCoverRemoved:(removed:boolean)=>void;
  isSaving:boolean; isDirty?:boolean; errorMessage?:string; successMessage?:string;
  onSubmit:(event:FormEvent<HTMLFormElement>)=>void; onCancel:()=>void;
};

export default function EventFormWizard(props:Props) {
  const {language:appLanguage}=useAppLanguage(); const copy=COPY[appLanguage] as Copy;
  const [active,setActive]=useState(0); const [themeOpen,setThemeOpen]=useState(false); const [category,setCategory]=useState("All"); const [mobilePreview,setMobilePreview]=useState(false);
  const fileRef=useRef<HTMLInputElement>(null); const dialogRef=useRef<HTMLDivElement>(null);
  const selectedTemplate=EVENT_TEMPLATE_OPTIONS.find(item=>item.value===props.values.invitation_template)??EVENT_TEMPLATE_OPTIONS[0];
  const shownCover=props.coverPreviewUrl||(!props.coverRemoved?props.currentCoverUrl??"":"");
  const previewData:EventPreviewData={title:props.values.title,eventType:props.values.event_type,brideName:props.values.bride_name,groomName:props.values.groom_name,language:props.values.language,template:props.values.invitation_template,invitationMessage:props.values.invitation_message,coverImageUrl:shownCover||null,eventDate:props.values.event_date,eventTime:props.values.event_time,venue:props.values.venue,ceremonyTitle:props.values.ceremony_title,ceremonyDate:props.values.ceremony_date,ceremonyTime:props.values.ceremony_time,ceremonyVenue:props.values.ceremony_venue,ceremonyMapUrl:props.values.ceremony_map_url,receptionMapUrl:props.values.reception_map_url,dressCode:props.values.dress_code,primary:props.values.theme_primary_color,secondary:props.values.theme_secondary_color,accent:props.values.theme_accent_color};
  const set=(patch:Partial<EventFormValues>)=>props.onValuesChange({...props.values,...patch});
  const openStep=(index:number)=>{setActive(index);requestAnimationFrame(()=>document.getElementById(`event-step-${index}`)?.scrollIntoView({behavior:"smooth",block:"start"}));};
  const change=(event:ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>set({[event.target.name]:event.target.value} as Partial<EventFormValues>);
  const selectPalette=(palette:EventThemePalette)=>set({dress_code:palette.dressCode,theme_primary_color:palette.primaryColor,theme_secondary_color:palette.secondaryColor,theme_accent_color:palette.accentColor});
  const chooseFile=(file?:File)=>{if(!file)return;if(!file.type.startsWith("image/")){window.alert(copy.photoType);return;}if(file.size>5*1024*1024){window.alert(copy.photoSize);return;}props.onCoverFile(file,URL.createObjectURL(file));props.onCoverRemoved(false);};

  useEffect(()=>{if(!themeOpen&&!mobilePreview)return;const previous=document.activeElement as HTMLElement|null;const dialog=dialogRef.current;dialog?.querySelector<HTMLElement>("button")?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setThemeOpen(false);setMobilePreview(false);}if(event.key!=="Tab"||!dialog)return;const items=[...dialog.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')];if(!items.length)return;const first=items[0],last=items.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};window.addEventListener("keydown",key);return()=>{window.removeEventListener("keydown",key);previous?.focus();};},[themeOpen,mobilePreview]);
  useEffect(()=>{if(props.mode!=="edit"||!props.isDirty)return;const before=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener("beforeunload",before);return()=>window.removeEventListener("beforeunload",before);},[props.mode,props.isDirty]);

  const invitationPreview=<PhonePreview values={props.values} cover={shownCover} templateName={selectedTemplate.name}/>;
  const review:Array<[string,string,number]>=[[copy.eventTitle,props.values.title||copy.notSet,0],[copy.eventType,props.values.event_type||copy.notSet,0],[copy.hosts,[props.values.bride_name,props.values.groom_name].filter(Boolean).join(" & ")||copy.notSet,0],[copy.language,props.values.language==="sw"?"Kiswahili":"English",0],[copy.theme,selectedTemplate.name,1],[copy.dressCode,props.values.dress_code||copy.notSet,1],[copy.cover,props.coverFile?copy.newCover:shownCover?copy.currentCover:copy.noCover,0],[copy.ceremony,[props.values.ceremony_date,props.values.ceremony_time,props.values.ceremony_venue].filter(Boolean).join(" · ")||copy.notSet,2],[copy.reception,[props.values.event_date,props.values.event_time,props.values.venue].filter(Boolean).join(" · ")||copy.notSet,3]];
  return <section className="mx-auto max-w-[1480px] pb-28">
    <header className="mb-6 rounded-[18px] border border-stone-200 bg-white px-5 py-5 shadow-[0_14px_40px_rgba(28,25,23,.06)] sm:px-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">Smart Event Pass</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950">{props.mode==="edit"?copy.editTitle:copy.createTitle}</h1><p className="mt-1 text-sm text-slate-500">{props.mode==="edit"?copy.editDescription:copy.createDescription}</p>{props.mode==="edit"&&props.isDirty&&<p className="mt-2 text-xs font-bold text-amber-700">● {copy.unsaved}</p>}</div><div className="w-full sm:max-w-xs"><div className="flex justify-between text-xs font-bold text-slate-500"><span>{copy.step} {active+1} {copy.of} {EVENT_WIZARD_STEP_COUNT}</span><span>{copy.steps[active]}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-emerald-600 transition-[width] motion-reduce:transition-none" style={{width:`${(active+1)*20}%`}}/></div></div></div></header>
    {props.errorMessage&&<div role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{props.errorMessage}</div>}{props.successMessage&&<div role="status" className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800">{props.successMessage}</div>}
    <form onSubmit={props.onSubmit} className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_390px]"><div className="space-y-3">
      <Step index={0} title={copy.steps[0]} description={copy.descriptions[0]} active={active===0} complete={Boolean(props.values.title&&props.values.event_type)} onOpen={openStep}><div className="grid gap-4 md:grid-cols-2"><Field label={copy.eventTitle} name="title" value={props.values.title} required onChange={change}/><Field label={copy.eventType} name="event_type" value={props.values.event_type} required onChange={change}/><Field label={copy.bride} name="bride_name" value={props.values.bride_name} onChange={change}/><Field label={copy.groom} name="groom_name" value={props.values.groom_name} onChange={change}/><label className="text-sm font-bold text-slate-700">{copy.invitationLanguage}<select name="language" value={props.values.language} disabled={props.isSaving} onChange={event=>{const language=event.target.value as EventLanguage;const defaultTitle=["Ibada ya Ndoa","Wedding Ceremony"].includes(props.values.ceremony_title);set({language,ceremony_title:defaultTitle?(language==="en"?"Wedding Ceremony":"Ibada ya Ndoa"):props.values.ceremony_title});}} className="mt-1.5 h-[52px] w-full rounded-xl border border-stone-300 bg-white px-4 focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100"><option value="sw">Kiswahili</option><option value="en">English</option></select></label><Field label={copy.dressCode} name="dress_code" value={props.values.dress_code} onChange={change}/><label className="text-sm font-bold text-slate-700 md:col-span-2">{copy.invitationMessage}<textarea name="invitation_message" value={props.values.invitation_message} maxLength={600} onChange={change} rows={3} className="mt-1.5 w-full rounded-xl border border-stone-300 p-4 focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100"/><span className="mt-1 block text-xs font-normal text-slate-500">{copy.invitationMessageHint} · {props.values.invitation_message.length}/600</span></label></div>
        <div className="mt-4"><p className="mb-1.5 text-sm font-bold text-slate-700">{copy.coverPhoto}</p><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" disabled={props.isSaving} onChange={event=>chooseFile(event.target.files?.[0])} className="sr-only"/><div role="button" tabIndex={0} onClick={()=>fileRef.current?.click()} onKeyDown={event=>{if(event.key==="Enter"||event.key===" ")fileRef.current?.click();}} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();chooseFile(event.dataTransfer.files[0]);}} className="rounded-2xl border-2 border-dashed border-stone-300 bg-stone-50 p-4 outline-none hover:border-emerald-500 focus:ring-4 focus:ring-emerald-100">{shownCover?<div className="flex items-center gap-4"><Image src={shownCover} alt={copy.coverPhoto} width={96} height={80} unoptimized className="h-20 w-24 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="truncate font-bold">{props.coverFile?.name||copy.existingCover}</p><p className="text-xs text-slate-500">{props.coverFile?`${(props.coverFile.size/1024/1024).toFixed(2)} MB`:copy.currentCover}</p><div className="mt-2 flex gap-4 text-xs font-bold"><span className="text-emerald-700">{copy.replacePhoto}</span><button type="button" onClick={event=>{event.stopPropagation();props.onCoverFile(null,"");props.onCoverRemoved(Boolean(props.currentCoverUrl));}} className="text-red-700">{copy.removePhoto}</button></div></div></div>:<div className="py-5 text-center"><p className="font-bold text-slate-800">{copy.dropPhoto}</p><p className="mt-1 text-xs text-slate-500">{copy.imageLimit}</p>{props.coverRemoved&&<button type="button" onClick={event=>{event.stopPropagation();props.onCoverRemoved(false);}} className="mt-3 font-bold text-emerald-700">{copy.restorePhoto}</button>}</div>}</div></div>
      </Step>
      <Step index={1} title={copy.steps[1]} description={copy.descriptions[1]} active={active===1} complete onOpen={openStep}><div className="rounded-2xl border border-stone-200 bg-stone-50 p-4 sm:flex sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-wide text-slate-400">{copy.selectedTheme}</p><div className="mt-2 flex items-center gap-3"><Dots colors={[props.values.theme_primary_color,props.values.theme_secondary_color,props.values.theme_accent_color]}/><div><p className="font-black">{props.values.dress_code||selectedTemplate.name}</p><p className="text-sm text-slate-500">{selectedTemplate.name}</p></div></div></div><button type="button" onClick={()=>setThemeOpen(true)} className="mt-4 min-h-11 rounded-xl border bg-white px-4 font-bold focus:ring-4 focus:ring-emerald-100 sm:mt-0">{copy.changeTheme}</button></div></Step>
      <Step index={2} title={copy.steps[2]} description={copy.descriptions[2]} active={active===2} complete={Boolean(props.values.ceremony_date||props.values.ceremony_venue)} onOpen={openStep}><div className="grid gap-4 md:grid-cols-2"><Field label={copy.ceremonyTitle} name="ceremony_title" value={props.values.ceremony_title} onChange={change}/><Field label={copy.date} name="ceremony_date" type="date" value={props.values.ceremony_date} onChange={change}/><Field label={copy.time} name="ceremony_time" type="time" value={props.values.ceremony_time} onChange={change}/><Field label={copy.venue} name="ceremony_venue" value={props.values.ceremony_venue} onChange={change}/><div className="md:col-span-2"><Field label={copy.mapLink} name="ceremony_map_url" type="url" value={props.values.ceremony_map_url} onChange={change}/></div></div></Step>
      <Step index={3} title={copy.steps[3]} description={copy.descriptions[3]} active={active===3} complete={Boolean(props.values.event_date&&props.values.event_time&&props.values.venue)} onOpen={openStep}><div className="grid gap-4 md:grid-cols-2"><Field label={copy.receptionDate} name="event_date" type="date" value={props.values.event_date} required onChange={change}/><Field label={copy.receptionTime} name="event_time" type="time" value={props.values.event_time} required onChange={change}/><Field label={copy.receptionVenue} name="venue" value={props.values.venue} required onChange={change}/><Field label={copy.mapLink} name="reception_map_url" type="url" value={props.values.reception_map_url} onChange={change}/></div></Step>
      <Step index={4} title={copy.reviewChanges} description={copy.descriptions[4]} active={active===4} complete={false} onOpen={openStep}><div className="grid gap-3 sm:grid-cols-2">{review.map(([label,value,step])=><div key={label} className="rounded-xl border border-stone-200 bg-stone-50 p-3"><div className="flex justify-between gap-3"><p className="text-xs font-bold text-slate-500">{label}</p><button type="button" onClick={()=>openStep(step)} className="text-xs font-bold text-emerald-700">{copy.edit}</button></div><p className="mt-1 break-words font-bold">{value}</p></div>)}</div></Step>
    </div><aside className="hidden xl:sticky xl:top-6 xl:block"><EventPreviewSwitcher data={previewData} invitationPreview={invitationPreview}/></aside><button type="button" onClick={()=>setMobilePreview(true)} className="min-h-11 rounded-xl border bg-white font-bold xl:hidden">{copy.preview}</button>
    <div className="fixed inset-x-0 bottom-0 z-30 border-t border-stone-200 bg-white/95 px-4 py-3 shadow-[0_-10px_30px_rgba(28,25,23,.08)] backdrop-blur"><div className="mx-auto flex max-w-[1480px] items-center justify-between gap-3"><button type="button" disabled={props.isSaving} onClick={props.onCancel} className="min-h-11 rounded-xl px-4 font-bold text-slate-600 hover:bg-stone-100">{copy.cancel}</button><button type="submit" disabled={props.isSaving||(props.mode==="edit"&&!props.isDirty)} className="min-h-11 rounded-xl bg-emerald-700 px-5 font-black text-white shadow-lg disabled:cursor-not-allowed disabled:opacity-50">{props.isSaving?(props.mode==="edit"?copy.saving:copy.creating):(props.mode==="edit"?copy.save:copy.create)}</button></div></div></form>
    {themeOpen&&<Modal dialogRef={dialogRef} onClose={()=>setThemeOpen(false)} title={copy.chooseStyle}><p className="text-sm text-slate-500">{copy.themeHint}</p><div className="mt-4 flex gap-2 overflow-x-auto">{(["All","Classic","Luxury","Modern","Minimal","Premium"] as const).map(item=><button key={item} type="button" aria-pressed={category===item} onClick={()=>setCategory(item)} className={`min-h-11 rounded-full px-4 text-sm font-bold ${category===item?"bg-slate-950 text-white":"bg-stone-100"}`}>{appLanguage==="sw"?({All:"Zote",Classic:"Kawaida",Luxury:"Kifahari",Modern:"Kisasa",Minimal:"Safi",Premium:"Premium"} as const)[item]:item}</button>)}</div><div className="mt-5"><ThemePalettePicker primaryColor={props.values.theme_primary_color} secondaryColor={props.values.theme_secondary_color} accentColor={props.values.theme_accent_color} disabled={props.isSaving} onSelect={selectPalette}/></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{EVENT_TEMPLATE_OPTIONS.filter(item=>category==="All"||item.category===category).map(item=><button key={item.value} type="button" onClick={()=>{set({invitation_template:item.value});setThemeOpen(false);}} className={`rounded-2xl border-2 p-3 text-left focus:ring-4 focus:ring-emerald-100 ${item.value===props.values.invitation_template?"border-emerald-600 bg-emerald-50":"border-stone-200"}`}><div className="overflow-hidden rounded-xl border border-stone-200 shadow-sm"><TemplateThumbnail template={item.value} language={props.values.language} primaryColor={props.values.theme_primary_color} secondaryColor={props.values.theme_secondary_color} accentColor={props.values.theme_accent_color} eventTitle={props.values.title} eventType={props.values.event_type} brideName={props.values.bride_name} groomName={props.values.groom_name} invitationMessage={props.values.invitation_message} ceremonyTitle={props.values.ceremony_title} ceremonyDate={props.values.ceremony_date} ceremonyTime={props.values.ceremony_time} ceremonyVenue={props.values.ceremony_venue} eventDate={props.values.event_date} eventTime={props.values.event_time} venue={props.values.venue} dressCode={props.values.dress_code} coverImageUrl={shownCover||null}/></div><h3 className="mt-3 font-black">{item.name}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{item.description[appLanguage]}</p></button>)}</div></Modal>}
    {mobilePreview&&<Modal dialogRef={dialogRef} onClose={()=>setMobilePreview(false)} title={copy.preview}><EventPreviewSwitcher data={previewData} invitationPreview={invitationPreview}/></Modal>}
  </section>;
}

function Step({index,title,description,active,complete,onOpen,children}:{index:number;title:string;description:string;active:boolean;complete:boolean;onOpen:(index:number)=>void;children:React.ReactNode}){return <section id={`event-step-${index}`} className="scroll-mt-5 overflow-hidden rounded-[18px] border border-stone-200 bg-white shadow-sm"><button type="button" aria-expanded={active} aria-controls={`event-step-panel-${index}`} onClick={()=>onOpen(index)} className="flex min-h-16 w-full items-center gap-4 p-4 text-left focus-visible:ring-4 focus-visible:ring-inset focus-visible:ring-emerald-100"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full text-sm font-black ${active?"bg-emerald-700 text-white":complete?"bg-emerald-50 text-emerald-700":"bg-stone-100 text-slate-500"}`}>{complete&&!active?"✓":index+1}</span><span className="min-w-0 flex-1"><span className="block font-black">{title}</span><span className="block truncate text-xs text-slate-500">{description}</span></span><span aria-hidden="true">⌄</span></button><div id={`event-step-panel-${index}`} hidden={!active}><div className="border-t border-stone-100 px-4 py-5 sm:px-5">{children}</div></div></section>}
function Field({label,name,value,type="text",required,onChange}:{label:string;name:string;value:string;type?:string;required?:boolean;onChange:(event:ChangeEvent<HTMLInputElement>)=>void}){return <label className="text-sm font-bold text-slate-700">{label}<input name={name} type={type} value={value} required={required} onChange={onChange} className="mt-1.5 h-[52px] w-full rounded-xl border border-stone-300 bg-white px-4 outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100"/></label>}
function Dots({colors}:{colors:string[]}){return <span className="flex -space-x-1">{colors.map((color,index)=><span key={`${color}-${index}`} className="h-5 w-5 rounded-full border-2 border-white shadow" style={{backgroundColor:color}}/>)}</span>}
function PhonePreview({values,cover,templateName}:{values:EventFormValues;cover:string;templateName:string}){return <div><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-black uppercase text-slate-400">Live Preview</p><p className="font-bold">{templateName}</p></div><Dots colors={[values.theme_primary_color,values.theme_secondary_color,values.theme_accent_color]}/></div><div className="mx-auto max-w-[300px] rounded-[38px] bg-slate-950 p-2 shadow-2xl"><div className="min-h-[560px] overflow-hidden rounded-[31px] text-center" style={{backgroundColor:values.theme_secondary_color,color:values.theme_primary_color}}><div className="mx-auto mt-3 h-5 w-24 rounded-full bg-slate-950"/>{cover?<Image src={cover} alt="" width={300} height={208} unoptimized className="mt-3 h-52 w-full object-cover"/>:<div className="mt-3 grid h-52 place-items-center bg-black/5 text-xs font-bold">COVER PHOTO</div>}<div className="p-6"><p className="text-[10px] font-black uppercase tracking-[.2em]" style={{color:values.theme_accent_color}}>You are invited</p><h2 className="mt-4 font-serif text-3xl font-black">{values.bride_name||"Bride / Celebrant"}<span className="block text-lg">&</span>{values.groom_name||"Groom"}</h2><p className="mt-4 text-sm font-bold">{values.title||"Your Event"}</p><p className="mt-5 text-xs">{values.event_date||"Event date"} · {values.event_time||"Event time"}</p><p className="mt-2 text-xs font-bold">{values.venue||"Reception venue"}</p><div className="mx-auto mt-6 grid h-16 w-16 place-items-center bg-white text-[9px] font-black text-slate-900 shadow">QR</div></div></div></div></div>}
function Modal({dialogRef,onClose,title,children}:{dialogRef:React.RefObject<HTMLDivElement|null>;onClose:()=>void;title:string;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/55 p-0 backdrop-blur-sm sm:place-items-center sm:p-3" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="event-modal-title" className="max-h-[95vh] w-full overflow-y-auto rounded-t-[22px] bg-white p-5 shadow-2xl sm:max-w-5xl sm:rounded-[22px] sm:p-7"><div className="flex justify-between gap-4"><h2 id="event-modal-title" className="text-2xl font-black">{title}</h2><button type="button" onClick={onClose} aria-label="Close" className="min-h-11 rounded-xl px-4 font-bold hover:bg-stone-100">×</button></div>{children}</div></div>}
