"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useParams, useRouter } from "next/navigation";
import EventFormWizard, { type EventFormValues } from "@/components/events/EventFormWizard";
import { useAppLanguage } from "@/lib/i18n/useAppLanguage";
import { DEFAULT_EVENT_THEME, DEFAULT_INVITATION_TEMPLATE, DEFAULT_PHOTO_LAYOUT, getEventById, updateEvent, uploadEventCover, type Event } from "@/services/eventService";

function valuesFromEvent(event:Event):EventFormValues{return {title:event.title,event_type:event.event_type,bride_name:event.bride_name??"",groom_name:event.groom_name??"",language:event.language??"sw",invitation_template:event.invitation_template??DEFAULT_INVITATION_TEMPLATE,photo_layout:event.photo_layout??DEFAULT_PHOTO_LAYOUT,invitation_message:event.invitation_message??"",ceremony_title:event.ceremony_title??(event.language==="en"?"Wedding Ceremony":"Ibada ya Ndoa"),ceremony_date:event.ceremony_date??"",ceremony_time:event.ceremony_time?.slice(0,5)??"",ceremony_venue:event.ceremony_venue??"",ceremony_map_url:event.ceremony_map_url??"",event_date:event.event_date,event_time:event.event_time?.slice(0,5)??"",venue:event.venue,reception_map_url:event.reception_map_url??"",dress_code:event.dress_code??"",theme_primary_color:event.theme_primary_color||DEFAULT_EVENT_THEME.primaryColor,theme_secondary_color:event.theme_secondary_color||DEFAULT_EVENT_THEME.secondaryColor,theme_accent_color:event.theme_accent_color||DEFAULT_EVENT_THEME.accentColor};}

export default function EditEventPage(){
  const params=useParams();const router=useRouter();const {language}=useAppLanguage();const eventId=Number(params.id);
  const [event,setEvent]=useState<Event|null>(null);const [values,setValues]=useState<EventFormValues|null>(null);const [baseline,setBaseline]=useState("");const [coverFile,setCoverFile]=useState<File|null>(null);const [coverPreview,setCoverPreview]=useState("");const [coverRemoved,setCoverRemoved]=useState(false);const [isLoading,setIsLoading]=useState(true);const [isSaving,setIsSaving]=useState(false);const [loadFailed,setLoadFailed]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");
  useEffect(()=>{let active=true;(async()=>{setIsLoading(true);setLoadFailed(false);try{if(!Number.isInteger(eventId))throw new Error();const loaded=await getEventById(eventId);if(!loaded)throw new Error();if(!active)return;const hydrated=valuesFromEvent(loaded);setEvent(loaded);setValues(hydrated);setBaseline(JSON.stringify(hydrated));}catch{if(active)setLoadFailed(true);}finally{if(active)setIsLoading(false);}})();return()=>{active=false;};},[eventId]);
  useEffect(()=>()=>{if(coverPreview)URL.revokeObjectURL(coverPreview);},[coverPreview]);
  const isDirty=useMemo(()=>Boolean(values&&(JSON.stringify(values)!==baseline||coverFile||coverRemoved)),[values,baseline,coverFile,coverRemoved]);
  const changeCover=(file:File|null,url:string)=>{if(coverPreview)URL.revokeObjectURL(coverPreview);setCoverFile(file);setCoverPreview(url);setSuccess("");};
  const cancel=()=>{if(isDirty&&!window.confirm(language==="sw"?"Una mabadiliko ambayo hayajahifadhiwa. Uondoke bila kuhifadhi?":"You have unsaved changes. Leave without saving?"))return;router.push("/events");};
  async function submit(submitEvent:FormEvent<HTMLFormElement>){submitEvent.preventDefault();if(!event||!values||!isDirty||isSaving)return;setError("");setSuccess("");setIsSaving(true);try{let coverUrl=event.cover_image_url??null;if(coverRemoved)coverUrl=null;if(coverFile)coverUrl=await uploadEventCover(coverFile);const updated=await updateEvent(eventId,{title:values.title,event_type:values.event_type,bride_name:values.bride_name||undefined,groom_name:values.groom_name||undefined,language:values.language,invitation_template:values.invitation_template,photo_layout:values.photo_layout,invitation_message:values.invitation_message||undefined,ceremony_title:values.ceremony_title||undefined,ceremony_date:values.ceremony_date||undefined,ceremony_time:values.ceremony_time||undefined,ceremony_venue:values.ceremony_venue||undefined,ceremony_map_url:values.ceremony_map_url||undefined,event_date:values.event_date,event_time:values.event_time,venue:values.venue,reception_map_url:values.reception_map_url||undefined,dress_code:values.dress_code||undefined,cover_image_url:coverUrl,theme_primary_color:values.theme_primary_color,theme_secondary_color:values.theme_secondary_color,theme_accent_color:values.theme_accent_color});const hydrated=valuesFromEvent(updated);setEvent(updated);setValues(hydrated);setBaseline(JSON.stringify(hydrated));setCoverFile(null);setCoverRemoved(false);if(coverPreview)URL.revokeObjectURL(coverPreview);setCoverPreview("");setSuccess(language==="sw"?"Event imebadilishwa vizuri.":"Event updated successfully.");router.refresh();}catch{setError(language==="sw"?"Event haikuweza kubadilishwa. Tafadhali jaribu tena.":"Unable to update the event. Please try again.");}finally{setIsSaving(false);}}
  if(isLoading)return <LoadingState language={language}/>;
  if(loadFailed||!event||!values)return <section className="mx-auto max-w-3xl"><div className="rounded-2xl border border-red-200 bg-white p-8 shadow-sm"><h1 className="text-2xl font-black text-slate-900">{language==="sw"?"Event haipatikani":"Event unavailable"}</h1><p className="mt-2 text-red-700">{language==="sw"?"Event haikupatikana au huna ruhusa ya kuihariri.":"The event was not found or you are not authorized to edit it."}</p><button type="button" onClick={()=>router.push("/events")} className="mt-5 min-h-11 rounded-xl bg-slate-900 px-5 font-bold text-white">{language==="sw"?"Rudi kwenye Events":"Back to Events"}</button></div></section>;
  return <EventFormWizard mode="edit" values={values} onValuesChange={next=>{setValues(next);setSuccess("");}} currentCoverUrl={event.cover_image_url} coverFile={coverFile} coverPreviewUrl={coverPreview} coverRemoved={coverRemoved} onCoverFile={changeCover} onCoverRemoved={removed=>{setCoverRemoved(removed);setSuccess("");}} isSaving={isSaving} isDirty={isDirty} errorMessage={error} successMessage={success} onSubmit={submit} onCancel={cancel}/>;
}

function LoadingState({language}:{language:"sw"|"en"}){return <section aria-busy="true" className="mx-auto max-w-[1480px]"><div className="animate-pulse space-y-4 motion-reduce:animate-none"><div className="h-36 rounded-2xl bg-stone-200"/>{[1,2,3].map(item=><div key={item} className="h-20 rounded-2xl bg-stone-200"/>)}</div><p className="sr-only">{language==="sw"?"Inapakia event":"Loading event"}</p></section>}
