"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import EventFormWizard, { type EventFormValues } from "@/components/events/EventFormWizard";
import { createEvent, DEFAULT_EVENT_THEME, DEFAULT_INVITATION_TEMPLATE, getDefaultPhotoLayoutForTemplate, uploadEventCover, uploadInvitationBackground } from "@/services/eventService";
import { DEFAULT_CUSTOM_LAYOUT, saveCustomInvitationLayout } from "@/services/invitationLayoutService";

const INITIAL_VALUES:EventFormValues={title:"",event_type:"",bride_name:"",groom_name:"",language:"sw",invitation_template:DEFAULT_INVITATION_TEMPLATE,photo_layout:getDefaultPhotoLayoutForTemplate(DEFAULT_INVITATION_TEMPLATE),invitation_message:"",ceremony_title:"Ibada ya Ndoa",ceremony_date:"",ceremony_time:"",ceremony_venue:"",ceremony_map_url:"",event_date:"",event_time:"",venue:"",reception_map_url:"",dress_code:"",theme_primary_color:DEFAULT_EVENT_THEME.primaryColor,theme_secondary_color:DEFAULT_EVENT_THEME.secondaryColor,theme_accent_color:DEFAULT_EVENT_THEME.accentColor,custom_layout_elements:DEFAULT_CUSTOM_LAYOUT};

export default function CreateEventPage(){
  const router=useRouter();const [values,setValues]=useState(INITIAL_VALUES);const [coverFile,setCoverFile]=useState<File|null>(null);const [coverPreview,setCoverPreview]=useState("");const [backgroundFile,setBackgroundFile]=useState<File|null>(null);const [backgroundPreview,setBackgroundPreview]=useState("");const [isSaving,setIsSaving]=useState(false);const [error,setError]=useState("");
  useEffect(()=>()=>{if(coverPreview)URL.revokeObjectURL(coverPreview);},[coverPreview]);
  useEffect(()=>()=>{if(backgroundPreview)URL.revokeObjectURL(backgroundPreview);},[backgroundPreview]);
  const changeCover=(file:File|null,url:string)=>{if(coverPreview)URL.revokeObjectURL(coverPreview);setCoverFile(file);setCoverPreview(url);setError("");};
  const changeBackground=(file:File|null,url:string)=>{if(backgroundPreview)URL.revokeObjectURL(backgroundPreview);setBackgroundFile(file);setBackgroundPreview(url);setError("");};
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(isSaving)return;setError("");setIsSaving(true);try{const cover=coverFile?await uploadEventCover(coverFile):null;const background=backgroundFile?await uploadInvitationBackground(backgroundFile):null;const created=await createEvent({title:values.title,event_type:values.event_type,bride_name:values.bride_name||undefined,groom_name:values.groom_name||undefined,language:values.language,invitation_template:values.invitation_template,photo_layout:values.photo_layout,invitation_message:values.invitation_message||undefined,ceremony_title:values.ceremony_title||undefined,ceremony_date:values.ceremony_date||undefined,ceremony_time:values.ceremony_time||undefined,ceremony_venue:values.ceremony_venue||undefined,ceremony_map_url:values.ceremony_map_url||undefined,event_date:values.event_date,event_time:values.event_time,venue:values.venue,reception_map_url:values.reception_map_url||undefined,dress_code:values.dress_code||undefined,cover_image_url:cover,custom_invitation_background_url:background,theme_primary_color:values.theme_primary_color,theme_secondary_color:values.theme_secondary_color,theme_accent_color:values.theme_accent_color});if(values.invitation_template==="custom")await saveCustomInvitationLayout(created.id,values.custom_layout_elements);router.push("/events");router.refresh();}catch{setError(values.language==="sw"?"Event haikuweza kutengenezwa. Tafadhali hakiki taarifa na ujaribu tena.":"Unable to create the event. Check the details and try again.");}finally{setIsSaving(false);}}
  return <EventFormWizard mode="create" values={values} onValuesChange={setValues} coverFile={coverFile} coverPreviewUrl={coverPreview} coverRemoved={false} onCoverFile={changeCover} onCoverRemoved={()=>{}} backgroundFile={backgroundFile} backgroundPreviewUrl={backgroundPreview} backgroundRemoved={false} onBackgroundFile={changeBackground} onBackgroundRemoved={()=>{}} isSaving={isSaving} errorMessage={error} onSubmit={submit} onCancel={()=>router.push("/events")}/>;
}
