import { supabase } from "@/lib/supabase";
import { normalizeTanzanianPhone } from "@/services/pledgeMessageService";

export type WorkflowRow={id:number;event_id:number;event_type:string;entity_type:string;entity_id:string|null;source:string;status:"pending"|"processing"|"processed"|"failed"|"held"|"cancelled";attempt_count:number;available_at:string;processed_at:string|null;last_error:string|null;created_at:string;events:{title:string}|Array<{title:string}>|null};
export type UpcomingJob={id:string|number;event_id:number;pledge_id:number|null;schedule_type:string;scheduled_for:string;status:string;sequence_number:number;cancel_reason:string|null;event_pledges:{full_name:string}|Array<{full_name:string}>|null;events:{title:string}|Array<{title:string}>|null};
export type TimelineItem={id:string;eventId:number;eventTitle:string;kind:"workflow"|"audit"|"delivery"|"connector"|"invitation"|"rsvp"|"checkin";label:string;status:string;occurredAt:string;detail:string|null};
export type SimpleAutomationSetting={event_id:number;reminders_enabled:boolean;reminder_frequency:string;pledge_acknowledgement_mode:"off"|"preview"|"automatic";daily_summary_enabled:boolean;owner_summary_phone:string|null;daily_summary_channel:"sms"|"whatsapp"|"both";daily_summary_time:string;automatic_messaging_enabled:boolean;automation_paused_at:string|null};
export type AutomationCenterData={events:Array<{id:number;title:string}>;settings:SimpleAutomationSetting[];workflows:WorkflowRow[];jobs:UpcomingJob[];timeline:TimelineItem[];deliveries:Array<{id:number;event_id:number;delivery_status:string;channel:string;reminder_type:string;created_at:string;sent_at:string|null;error_message:string|null}>;heldCounts:Record<number,number>;sourceErrors:string[]};
const relation=<T>(value:T|T[]|null|undefined)=>Array.isArray(value)?value[0]??null:value??null;

export async function getAutomationCenterData():Promise<AutomationCenterData>{
 const eventResult=await supabase.from("events").select("id,title").order("event_date",{ascending:false});if(eventResult.error)throw new Error("Authorized events could not be loaded.");const events=(eventResult.data??[]) as Array<{id:number;title:string}>,ids=events.map(item=>item.id);if(!ids.length)return {events,settings:[],workflows:[],jobs:[],timeline:[],deliveries:[],heldCounts:{},sourceErrors:[]};
 const [settingResult,workflowResult,scheduleResult,deliveryResult,summaryDeliveryResult,auditResult,invitationResult,guestResult,connectorDeliveryResult]=await Promise.all([
  supabase.from("event_finance_automation_settings").select("event_id,reminders_enabled,reminder_frequency,pledge_acknowledgement_mode,daily_summary_enabled,owner_summary_phone,daily_summary_channel,daily_summary_time,automatic_messaging_enabled,automation_paused_at").in("event_id",ids),
  supabase.from("workflow_events").select("id,event_id,event_type,entity_type,entity_id,source,status,attempt_count,available_at,processed_at,last_error,created_at,events(title)").in("event_id",ids).order("created_at",{ascending:false}).limit(500),
  supabase.from("pledge_reminder_schedules").select("id,event_id,pledge_id,schedule_type,scheduled_for,status,sequence_number,cancel_reason,event_pledges(full_name),events(title)").in("event_id",ids).order("scheduled_for",{ascending:true}).limit(300),
  supabase.from("pledge_reminders").select("id,event_id,delivery_status,channel,reminder_type,created_at,sent_at,error_message").in("event_id",ids).order("created_at",{ascending:false}).limit(300),
  supabase.from("finance_automation_delivery_logs").select("id,event_id,delivery_status,channel,delivery_type,created_at,sent_at,error_message").in("event_id",ids).order("created_at",{ascending:false}).limit(300),
  supabase.from("finance_audit_logs").select("id,event_id,action,created_at,metadata,events(title)").in("event_id",ids).order("created_at",{ascending:false}).limit(300),
  supabase.from("invitations").select("id,event_id,invitation_status,rsvp_status,created_at,viewed_at,updated_at,events(title)").in("event_id",ids).order("created_at",{ascending:false}).limit(200),
  supabase.from("guests").select("id,event_id,full_name,checked_in_at,events(title)").in("event_id",ids).not("checked_in_at","is",null).order("checked_in_at",{ascending:false}).limit(200),
  supabase.from("automation_connector_deliveries").select("id,event_id,event_type,status,attempt_count,response_status,external_execution_id,last_error,created_at,updated_at").in("event_id",ids).order("created_at",{ascending:false}).limit(300),
 ]);
 const sourceErrors=[settingResult.error&&"Automation settings",workflowResult.error&&"Workflow queue",scheduleResult.error&&"Upcoming jobs",deliveryResult.error&&"Delivery logs",summaryDeliveryResult.error&&"Summary delivery logs",auditResult.error&&"Audit timeline",invitationResult.error&&"Invitation/RSVP activity",guestResult.error&&"Check-in activity",connectorDeliveryResult.error&&"Make connector activity"].filter(Boolean) as string[];
 const workflows=(workflowResult.data??[]) as unknown as WorkflowRow[],jobs=(scheduleResult.data??[]) as unknown as UpcomingJob[],deliveries=(deliveryResult.data??[]) as AutomationCenterData["deliveries"],eventMap=new Map(events.map(item=>[item.id,item.title]));
 for(const workflow of workflows){if(workflow.event_type==="owner.summary.daily_requested"&&workflow.status==="pending")jobs.push({id:`summary-${workflow.id}`,event_id:workflow.event_id,pledge_id:null,schedule_type:"Daily Summary",scheduled_for:workflow.available_at,status:"scheduled",sequence_number:1,cancel_reason:null,event_pledges:{full_name:"Daily Summary"},events:workflow.events})}
 jobs.sort((a,b)=>new Date(a.scheduled_for).getTime()-new Date(b.scheduled_for).getTime());
 const timeline:TimelineItem[]=[];
 workflows.forEach(item=>timeline.push({id:`w-${item.id}`,eventId:item.event_id,eventTitle:relation(item.events)?.title??eventMap.get(item.event_id)??"Event",kind:"workflow",label:item.event_type,status:item.status,occurredAt:item.processed_at??item.created_at,detail:item.last_error}));
 for(const item of auditResult.data??[]){const event=relation(item.events as {title:string}|Array<{title:string}>|null);timeline.push({id:`a-${item.id}`,eventId:item.event_id,eventTitle:event?.title??eventMap.get(item.event_id)??"Event",kind:"audit",label:item.action,status:"recorded",occurredAt:item.created_at,detail:null})}
 for(const item of deliveryResult.data??[])timeline.push({id:`d-${item.id}`,eventId:item.event_id,eventTitle:eventMap.get(item.event_id)??"Event",kind:"delivery",label:item.reminder_type,status:item.delivery_status,occurredAt:item.sent_at??item.created_at,detail:item.error_message});
 for(const item of summaryDeliveryResult.data??[])timeline.push({id:`s-${item.id}`,eventId:item.event_id,eventTitle:eventMap.get(item.event_id)??"Event",kind:"delivery",label:item.delivery_type,status:item.delivery_status,occurredAt:item.sent_at??item.created_at,detail:item.error_message??item.channel});
 for(const item of invitationResult.data??[]){const event=relation(item.events as {title:string}|Array<{title:string}>|null),rsvp=item.rsvp_status&&item.rsvp_status!=="pending";timeline.push({id:`i-${item.id}`,eventId:item.event_id,eventTitle:event?.title??eventMap.get(item.event_id)??"Event",kind:rsvp?"rsvp":"invitation",label:rsvp?`RSVP ${item.rsvp_status}`:`Invitation ${item.invitation_status}`,status:rsvp?item.rsvp_status:item.invitation_status,occurredAt:item.updated_at??item.viewed_at??item.created_at,detail:null})}
 for(const item of guestResult.data??[]){const event=relation(item.events as {title:string}|Array<{title:string}>|null);timeline.push({id:`c-${item.id}`,eventId:item.event_id,eventTitle:event?.title??eventMap.get(item.event_id)??"Event",kind:"checkin",label:"Guest checked in",status:"completed",occurredAt:item.checked_in_at!,detail:item.full_name})}
 for(const item of connectorDeliveryResult.data??[])timeline.push({id:`m-${item.id}`,eventId:item.event_id,eventTitle:eventMap.get(item.event_id)??"Event",kind:"connector",label:`Make ${item.event_type}`,status:item.status,occurredAt:item.updated_at??item.created_at,detail:item.last_error??(item.external_execution_id?`Execution ${item.external_execution_id}`:item.response_status?`HTTP ${item.response_status} · attempt ${item.attempt_count}`:`Attempt ${item.attempt_count}`)});
 const heldResults=await Promise.all(ids.map(async eventId=>({eventId,result:await supabase.rpc("event_held_automation_count",{target_event_id:eventId})})));const heldCounts=Object.fromEntries(heldResults.map(({eventId,result})=>[eventId,result.error?0:Number(result.data??0)]));
 timeline.sort((a,b)=>new Date(b.occurredAt).getTime()-new Date(a.occurredAt).getTime());return {events,settings:(settingResult.data??[]) as SimpleAutomationSetting[],workflows,jobs,timeline:timeline.slice(0,600),deliveries,heldCounts,sourceErrors};
}

export async function saveSimpleAutomationSettings(input:{eventId:number;reminderMode:"off"|"manual"|"automatic";acknowledgementMode:"off"|"preview"|"automatic";summaryEnabled:boolean;summaryPhone:string;summaryChannel:"sms"|"whatsapp"|"both";localSummaryTime:string}){const phone=input.summaryPhone.trim()?normalizeTanzanianPhone(input.summaryPhone):"";const {data,error}=await supabase.rpc("save_simple_automation_settings",{target_event_id:input.eventId,reminder_mode:input.reminderMode,acknowledgement_mode:input.acknowledgementMode,summary_enabled:input.summaryEnabled,summary_phone:phone,summary_channel:input.summaryChannel,local_summary_time:input.localSummaryTime,local_timezone:"Africa/Dar_es_Salaam"});if(error)throw new Error(error.message);return data as SimpleAutomationSetting}

export async function retryWorkflowEvent(id:number){const {data}=await supabase.auth.getSession();if(!data.session?.access_token)throw new Error("Your session has expired.");const response=await fetch("/api/automation/retry",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({workflowEventId:id})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Workflow event could not be retried.");}

export async function setMasterAutomation(eventId:number,enabled:boolean){const {data,error}=await supabase.rpc("set_event_master_automation",{target_event_id:eventId,enabled});if(error)throw new Error("Master Automation could not be updated. Please try again.");return data as SimpleAutomationSetting}
export async function manageHeldAutomation(eventId:number,action:"process"|"cancel"){const {data,error}=await supabase.rpc("manage_held_automation",{target_event_id:eventId,requested_action:action});if(error)throw new Error("Held messages could not be updated. Please try again.");return data as {affected:number;action:string}}
