import { supabase } from "@/lib/supabase";

export type WorkflowRow={id:number;event_id:number;event_type:string;entity_type:string;entity_id:string|null;source:string;status:"pending"|"processing"|"processed"|"failed";attempt_count:number;available_at:string;processed_at:string|null;last_error:string|null;created_at:string;events:{title:string}|Array<{title:string}>|null};
export type UpcomingJob={id:number;event_id:number;pledge_id:number;schedule_type:string;scheduled_for:string;status:string;sequence_number:number;cancel_reason:string|null;event_pledges:{full_name:string}|Array<{full_name:string}>|null;events:{title:string}|Array<{title:string}>|null};
export type TimelineItem={id:string;eventId:number;eventTitle:string;kind:"workflow"|"audit"|"delivery"|"invitation"|"rsvp"|"checkin";label:string;status:string;occurredAt:string;detail:string|null};
export type AutomationCenterData={events:Array<{id:number;title:string}>;workflows:WorkflowRow[];jobs:UpcomingJob[];timeline:TimelineItem[];deliveries:Array<{id:number;event_id:number;delivery_status:string;channel:string;reminder_type:string;created_at:string;sent_at:string|null;error_message:string|null}>;sourceErrors:string[]};
const relation=<T>(value:T|T[]|null|undefined)=>Array.isArray(value)?value[0]??null:value??null;

export async function getAutomationCenterData():Promise<AutomationCenterData>{
 const eventResult=await supabase.from("events").select("id,title").order("event_date",{ascending:false});if(eventResult.error)throw new Error("Authorized events could not be loaded.");const events=(eventResult.data??[]) as Array<{id:number;title:string}>,ids=events.map(item=>item.id);if(!ids.length)return {events,workflows:[],jobs:[],timeline:[],deliveries:[],sourceErrors:[]};
 const [workflowResult,scheduleResult,deliveryResult,auditResult,invitationResult,guestResult]=await Promise.all([
  supabase.from("workflow_events").select("id,event_id,event_type,entity_type,entity_id,source,status,attempt_count,available_at,processed_at,last_error,created_at,events(title)").in("event_id",ids).order("created_at",{ascending:false}).limit(500),
  supabase.from("pledge_reminder_schedules").select("id,event_id,pledge_id,schedule_type,scheduled_for,status,sequence_number,cancel_reason,event_pledges(full_name),events(title)").in("event_id",ids).order("scheduled_for",{ascending:true}).limit(300),
  supabase.from("pledge_reminders").select("id,event_id,delivery_status,channel,reminder_type,created_at,sent_at,error_message").in("event_id",ids).order("created_at",{ascending:false}).limit(300),
  supabase.from("finance_audit_logs").select("id,event_id,action,created_at,metadata,events(title)").in("event_id",ids).order("created_at",{ascending:false}).limit(300),
  supabase.from("invitations").select("id,event_id,invitation_status,rsvp_status,created_at,viewed_at,updated_at,events(title)").in("event_id",ids).order("created_at",{ascending:false}).limit(200),
  supabase.from("guests").select("id,event_id,full_name,checked_in_at,events(title)").in("event_id",ids).not("checked_in_at","is",null).order("checked_in_at",{ascending:false}).limit(200),
 ]);
 const sourceErrors=[workflowResult.error&&"Workflow queue",scheduleResult.error&&"Upcoming jobs",deliveryResult.error&&"Delivery logs",auditResult.error&&"Audit timeline",invitationResult.error&&"Invitation/RSVP activity",guestResult.error&&"Check-in activity"].filter(Boolean) as string[];
 const workflows=(workflowResult.data??[]) as unknown as WorkflowRow[],jobs=(scheduleResult.data??[]) as unknown as UpcomingJob[],deliveries=(deliveryResult.data??[]) as AutomationCenterData["deliveries"],eventMap=new Map(events.map(item=>[item.id,item.title]));
 const timeline:TimelineItem[]=[];
 workflows.forEach(item=>timeline.push({id:`w-${item.id}`,eventId:item.event_id,eventTitle:relation(item.events)?.title??eventMap.get(item.event_id)??"Event",kind:"workflow",label:item.event_type,status:item.status,occurredAt:item.processed_at??item.created_at,detail:item.last_error}));
 for(const item of auditResult.data??[]){const event=relation(item.events as {title:string}|Array<{title:string}>|null);timeline.push({id:`a-${item.id}`,eventId:item.event_id,eventTitle:event?.title??eventMap.get(item.event_id)??"Event",kind:"audit",label:item.action,status:"recorded",occurredAt:item.created_at,detail:null})}
 for(const item of deliveryResult.data??[])timeline.push({id:`d-${item.id}`,eventId:item.event_id,eventTitle:eventMap.get(item.event_id)??"Event",kind:"delivery",label:item.reminder_type,status:item.delivery_status,occurredAt:item.sent_at??item.created_at,detail:item.error_message});
 for(const item of invitationResult.data??[]){const event=relation(item.events as {title:string}|Array<{title:string}>|null),rsvp=item.rsvp_status&&item.rsvp_status!=="pending";timeline.push({id:`i-${item.id}`,eventId:item.event_id,eventTitle:event?.title??eventMap.get(item.event_id)??"Event",kind:rsvp?"rsvp":"invitation",label:rsvp?`RSVP ${item.rsvp_status}`:`Invitation ${item.invitation_status}`,status:rsvp?item.rsvp_status:item.invitation_status,occurredAt:item.updated_at??item.viewed_at??item.created_at,detail:null})}
 for(const item of guestResult.data??[]){const event=relation(item.events as {title:string}|Array<{title:string}>|null);timeline.push({id:`c-${item.id}`,eventId:item.event_id,eventTitle:event?.title??eventMap.get(item.event_id)??"Event",kind:"checkin",label:"Guest checked in",status:"completed",occurredAt:item.checked_in_at!,detail:item.full_name})}
 timeline.sort((a,b)=>new Date(b.occurredAt).getTime()-new Date(a.occurredAt).getTime());return {events,workflows,jobs,timeline:timeline.slice(0,600),deliveries,sourceErrors};
}

export async function retryWorkflowEvent(id:number){const {data}=await supabase.auth.getSession();if(!data.session?.access_token)throw new Error("Your session has expired.");const response=await fetch("/api/automation/retry",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({workflowEventId:id})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Workflow event could not be retried.");}
