import {ImageResponse} from "next/og";
import {getPublicPledgeInfo,pledgePreviewCopy,publicCoverUrl} from "@/lib/publicPledgeMetadata";
/* eslint-disable @next/next/no-img-element -- ImageResponse renders its own image tree; next/image is unsupported here. */
export const runtime="nodejs";export const size={width:1200,height:630};export const contentType="image/png";export const alt="Smart Event Pass contribution pledge";

async function safeCover(value:string|null){const url=publicCoverUrl(value);if(!url)return null;try{const response=await fetch(url,{signal:AbortSignal.timeout(3500),cache:"force-cache"});const type=response.headers.get("content-type")||"";const length=Number(response.headers.get("content-length")||0);if(!response.ok||!type.startsWith("image/")||length>4_000_000)return null;const bytes=await response.arrayBuffer();if(bytes.byteLength>4_000_000)return null;return `data:${type};base64,${Buffer.from(bytes).toString("base64")}`}catch{return null}}
function dateLabel(value:string|null,language:"sw"|"en"){if(!value)return null;try{return new Intl.DateTimeFormat(language==="sw"?"sw-TZ":"en-TZ",{day:"numeric",month:"long",year:"numeric",timeZone:"Africa/Dar_es_Salaam"}).format(new Date(`${value}T12:00:00+03:00`))}catch{return null}}
export default async function OpenGraphImage({params}:{params:Promise<{token:string}>}){const {token}=await params,info=await getPublicPledgeInfo(token);if(!info.valid)return new ImageResponse(<Fallback/>,size);const copy=pledgePreviewCopy(info),cover=await safeCover(info.cover_image_url),primary=/^#[0-9a-f]{6}$/i.test(info.theme_primary_color||"")?info.theme_primary_color!:"#071b2b",accent=/^#[0-9a-f]{6}$/i.test(info.theme_accent_color||"")?info.theme_accent_color!:"#d7b76d",date=dateLabel(info.event_date,info.language);return new ImageResponse(<div style={{width:"100%",height:"100%",display:"flex",position:"relative",background:`linear-gradient(135deg,${primary},#07111f)`,color:"white",fontFamily:"Arial, sans-serif",overflow:"hidden"}}>{cover&&<img src={cover} alt="" width="1200" height="630" style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}}/>}<div style={{position:"absolute",inset:0,display:"flex",background:cover?"linear-gradient(90deg,rgba(4,13,24,.96) 0%,rgba(4,13,24,.82) 56%,rgba(4,13,24,.28) 100%)":"linear-gradient(135deg,rgba(255,255,255,.04),rgba(255,255,255,0))"}}/><div style={{position:"absolute",right:-80,top:-120,width:420,height:420,borderRadius:999,border:`2px solid ${accent}55`,display:"flex"}}/><div style={{position:"relative",display:"flex",flexDirection:"column",justifyContent:"space-between",width:"760px",padding:"58px 68px"}}><div style={{display:"flex",alignItems:"center",fontSize:22,fontWeight:700,letterSpacing:4,textTransform:"uppercase",color:accent}}><span style={{display:"flex",width:42,height:4,background:accent,marginRight:18}}/>Smart Event Pass</div><div style={{display:"flex",flexDirection:"column"}}><div style={{display:"flex",fontSize:25,fontWeight:700,color:accent,marginBottom:18}}>{copy.label}</div><div style={{display:"flex",fontSize:58,lineHeight:1.05,fontWeight:800,letterSpacing:-2,maxHeight:190,overflow:"hidden"}}>{info.event_name}</div>{info.title&&<div style={{display:"flex",fontSize:28,marginTop:16,color:"#e8edf2"}}>{info.title}</div>}<div style={{display:"flex",fontSize:21,marginTop:24,color:"#d6dee7"}}>{[date,info.venue].filter(Boolean).join("  ·  ")}</div></div><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",fontSize:20}}><span style={{display:"flex",border:`1px solid ${accent}88`,borderRadius:999,padding:"13px 22px",background:"rgba(255,255,255,.08)"}}>🔒 {copy.action}</span><span style={{display:"flex",color:"#d6dee7",fontSize:17}}>{copy.trust}</span></div></div></div>,size)}
function Fallback(){return <div style={{width:"100%",height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",background:"linear-gradient(135deg,#071b2b,#123d46)",color:"white",fontFamily:"Arial, sans-serif"}}><div style={{display:"flex",fontSize:25,letterSpacing:5,textTransform:"uppercase",color:"#d7b76d"}}>Smart Event Pass</div><div style={{display:"flex",fontSize:58,fontWeight:800,marginTop:28}}>Secure event link</div><div style={{display:"flex",fontSize:25,color:"#dce7e8",marginTop:20}}>This secure event link is unavailable.</div></div>}
