"use client";
import { useEffect, useRef, useState } from "react";

type Language = "sw" | "en";
type LinkInfo = { event_name:string; title:string|null; message:string|null; language:Language;event_date:string|null;event_time:string|null;venue:string|null;cover_image_url:string|null };
type FieldErrors = { fullName?:string; phone?:string; email?:string };
const copy = {
  sw:{support:"Toa Ahadi ya Mchango",intro:"Jaza fomu hii rahisi kuonyesha ahadi yako ya kusaidia tukio.",personal:"Taarifa zako",pledgeDetails:"Taarifa za ahadi",name:"Jina kamili",nameRequired:"Tafadhali weka jina lako kamili.",phone:"Namba ya simu",phonePlaceholder:"07XX XXX XXX",phoneHelp:"Tunahitaji namba yako ili kutuma uthibitisho wa ahadi yako na vikumbusho vya malipo.",phoneRequired:"Tafadhali weka namba yako ya simu.",phoneInvalid:"Weka namba halali ya Tanzania, mfano 0712 345 678.",email:"Barua pepe (hiari)",emailInvalid:"Weka barua pepe halali.",amount:"Kiasi cha ahadi",date:"Tarehe unayotarajia kukamilisha (hiari)",dateHelp:"Unaweza kuacha wazi kama bado hujapanga tarehe ya kukamilisha.",note:"Ujumbe au maelezo (hiari)",consent:"Nathibitisha kuwa hii ni ahadi yangu ya mchango.",submit:"Tuma ahadi",sending:"Inatuma...",success:"Asante! Ahadi yako ya TZS {amount} imepokelewa.",thanks:"Tunakushukuru kwa moyo wako wa ushirikiano.",review:"Asante! Ombi lako la ahadi ya TZS {amount} limepokelewa.",reviewHelp:"Timu ya tukio italihakiki na kuwasiliana nawe.",secure:"Fomu salama ya ahadi imewezeshwa na Smart Event Pass.",privacy:"Taarifa zako hazitumiki kwa kitu kingine chochote zaidi ya tukio hili.",error:"Tafadhali rekebisha sehemu zenye makosa.",unavailable:"Link hii ya ahadi haipatikani au muda wake umeisha."},
  en:{support:"Make a Contribution Pledge",intro:"Complete this short form to pledge your support for the event.",personal:"Your details",pledgeDetails:"Pledge details",name:"Full name",nameRequired:"Please enter your full name.",phone:"Phone number",phonePlaceholder:"07XX XXX XXX",phoneHelp:"We need your number to send your pledge confirmation and payment reminders.",phoneRequired:"Please enter your phone number.",phoneInvalid:"Enter a valid Tanzanian number, e.g. 0712 345 678.",email:"Email (optional)",emailInvalid:"Enter a valid email address.",amount:"Pledge amount",date:"Expected completion date (optional)",dateHelp:"You may leave this blank if you have not planned a completion date yet.",note:"Message or note (optional)",consent:"I confirm this contribution pledge.",submit:"Submit pledge",sending:"Submitting...",success:"Thank you! Your pledge of TZS {amount} has been received.",thanks:"We truly appreciate your generous support.",review:"Thank you! Your pledge request of TZS {amount} has been received.",reviewHelp:"The event team will review it and get in touch.",secure:"Secure pledge form powered by Smart Event Pass.",privacy:"Your details are used only for this event and nothing else.",error:"Please correct the highlighted fields.",unavailable:"This pledge link is unavailable or has expired."}
} as const;

// Mirrors normalizePublicPhone in lib/publicPledge.ts (server is the source of truth).
function isValidTanzanianPhone(input:string){let value=input.trim().replace(/[^\d+]/g,"").replace(/^\+/,"");if(value.startsWith("2550"))value=`255${value.slice(4)}`;else if(value.startsWith("0"))value=`255${value.slice(1)}`;return /^255[67]\d{8}$/.test(value)}
const formatAmount=(digits:string)=>digits?Number(digits).toLocaleString("en-US"):"";

export default function PublicPledgeForm({token,initialInfo}:{token:string;initialInfo:LinkInfo|null}) {
  const [info]=useState<LinkInfo|null>(initialInfo),[language,setLanguage]=useState<Language>(initialInfo?.language??"sw"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[fieldErrors,setFieldErrors]=useState<FieldErrors>({}),[amount,setAmount]=useState(""),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState<{status:"received"|"review";amount:string}|null>(null);
  const started=useRef(0),idempotency=useRef(""),resultRef=useRef<HTMLDivElement>(null),t=copy[language];
  useEffect(()=>{started.current=Date.now();idempotency.current=crypto.randomUUID()},[]);
  useEffect(()=>{if(result)resultRef.current?.scrollIntoView({behavior:"smooth",block:"center"})},[result]);
  const phoneError=(value:string)=>!value.trim()?"required":isValidTanzanianPhone(value)?undefined:"invalid";
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget),phone=String(form.get("phone")??""),fullName=String(form.get("fullName")??"").trim(),next:FieldErrors={fullName:fullName.length<2?"required":undefined,phone:phoneError(phone)};
    if(next.fullName||next.phone){setFieldErrors(next);event.currentTarget.querySelector<HTMLInputElement>(`[name=${next.fullName?"fullName":"phone"}]`)?.focus();return}
    setFieldErrors({});setBusy(true);const body={token,idempotencyKey:idempotency.current,durationMs:Date.now()-started.current,website:form.get("website"),fullName,phone,email:form.get("email"),amount,expectedDate:form.get("expectedDate"),note:form.get("note")};
    try{const response=await fetch("/api/public/pledges",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok){if(payload.code==="phone"||payload.code==="email"){setFieldErrors({[payload.code]:payload.code==="phone"?(phone.trim()?"invalid":"required"):"invalid"});return}throw new Error(payload.error||t.error)}setResult({status:payload.status,amount:formatAmount(amount)});}catch(e){setError(e instanceof Error?e.message:t.error);}finally{setBusy(false)}}
  if(!info)return <main className="grid min-h-screen place-items-center bg-[#f6f2e9] p-4"><section className="max-w-md rounded-3xl bg-white p-8 text-center shadow-xl"><h1 className="text-2xl font-bold">Smart Event Pass</h1><p className="mt-4 text-slate-600" role="alert">{error||t.unavailable}</p></section></main>;
  const details=[info.event_date,info.event_time,info.venue].filter(Boolean).join(" · ");
  const phoneMessage=fieldErrors.phone==="required"?t.phoneRequired:fieldErrors.phone?t.phoneInvalid:undefined;
  return <main className="min-h-screen overflow-x-hidden bg-[#f6f2e9] px-4 py-6 text-slate-950 sm:py-12"><section className="mx-auto w-full max-w-xl overflow-hidden rounded-3xl border border-emerald-100 bg-white shadow-[0_24px_70px_rgba(62,45,20,.12)]"><header className="relative min-h-64 overflow-hidden bg-slate-950 px-5 py-6 text-white sm:min-h-72 sm:px-8 sm:py-7">{info.cover_image_url&&<div role="img" aria-label={`${info.event_name} event cover`} className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:`linear-gradient(90deg,rgba(2,12,22,.95),rgba(2,12,22,.5)),url(${JSON.stringify(info.cover_image_url).slice(1,-1)})`}}/>}<div className="relative flex min-h-52 flex-col justify-between sm:min-h-56"><div className="flex items-start justify-between gap-4"><p className="rounded-full border border-emerald-400/40 bg-black/20 px-3 py-2 text-xs font-bold uppercase tracking-[.16em] text-emerald-400">🔒 Smart Event Pass</p><button type="button" onClick={()=>setLanguage(v=>v==="sw"?"en":"sw")} className="min-h-12 rounded-xl border border-white/30 bg-black/20 px-3 font-semibold">{language==="sw"?"EN":"SW"}</button></div><div><p className="text-sm font-bold text-emerald-400">{language==="sw"?"Ahadi ya Mchango":"Contribution Pledge"}</p><h1 className="mt-2 break-words font-serif text-2xl font-bold sm:text-3xl">{info.event_name}</h1>{info.title&&<p className="mt-2 text-base text-white sm:text-lg">{info.title}</p>}{details&&<p className="mt-3 text-sm text-slate-200">{details}</p>}</div></div></header><div className="p-5 sm:p-8">{result?<div ref={resultRef} aria-live="polite" className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center sm:p-8"><div className="mx-auto grid size-16 place-items-center rounded-full bg-emerald-600 text-white shadow-lg shadow-emerald-600/25"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" className="size-8" aria-hidden="true"><path d="M5 12.5l4.5 4.5L19 7.5"/></svg></div><h2 className="mt-4 text-xl font-bold text-emerald-950">{(result.status==="review"?t.review:t.success).replace("{amount}",result.amount)}</h2><p className="mt-2 text-emerald-800">{result.status==="review"?t.reviewHelp:t.thanks}</p></div>:<><p className="text-slate-600">{info.message||t.intro}</p><div className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900"><p className="font-medium">🔒 {t.secure}</p><p className="mt-1 pl-6 text-emerald-800">{t.privacy}</p></div>{error&&<div role="alert" aria-live="assertive" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}<form onSubmit={submit} noValidate className="mt-6"><input name="website" tabIndex={-1} autoComplete="off" className="absolute -left-[9999px]" aria-hidden="true"/>
    <fieldset className="min-w-0 space-y-5"><legend className="mb-4 text-xs font-bold uppercase tracking-[.14em] text-slate-500">{t.personal}</legend><Field label={t.name} name="fullName" autoComplete="name" required maxLength={160} error={fieldErrors.fullName?t.nameRequired:undefined} onChange={()=>fieldErrors.fullName&&setFieldErrors(v=>({...v,fullName:undefined}))}/><Field label={t.phone} name="phone" type="tel" inputMode="tel" autoComplete="tel" required placeholder={t.phonePlaceholder} help={t.phoneHelp} error={phoneMessage} onChange={()=>fieldErrors.phone&&setFieldErrors(v=>({...v,phone:undefined}))}/><Field label={t.email} name="email" type="email" inputMode="email" autoComplete="email" error={fieldErrors.email?t.emailInvalid:undefined} onChange={()=>fieldErrors.email&&setFieldErrors(v=>({...v,email:undefined}))}/></fieldset>
    <fieldset className="mt-7 min-w-0 space-y-5 border-t border-slate-200 pt-6"><legend className="sr-only">{t.pledgeDetails}</legend><p aria-hidden="true" className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">{t.pledgeDetails}</p><label className="block"><span className="mb-2 block text-sm font-semibold">{t.amount}</span><span className="flex min-h-12 items-stretch overflow-hidden rounded-xl border border-slate-300 focus-within:border-emerald-600 focus-within:ring-2 focus-within:ring-emerald-100"><span className="flex items-center border-r border-slate-200 bg-slate-50 px-3 text-sm font-bold text-slate-600">TZS</span><input name="amount" type="text" inputMode="numeric" autoComplete="off" required placeholder="500,000" value={formatAmount(amount)} onChange={e=>setAmount(e.target.value.replace(/\D/g,"").replace(/^0+/,"").slice(0,10))} pattern="[0-9,]+" className="min-w-0 flex-1 px-3 text-base font-semibold tabular-nums focus:outline-none"/></span></label><Field label={t.date} name="expectedDate" type="date" help={t.dateHelp}/><label className="block"><span className="mb-2 block text-sm font-semibold">{t.note}</span><textarea name="note" maxLength={1000} rows={4} className="w-full rounded-xl border border-slate-300 p-3 text-base focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-100"/></label></fieldset>
    <label className="mt-6 flex cursor-pointer items-start gap-3 rounded-xl bg-slate-50 p-4"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1 size-5 shrink-0 accent-emerald-700"/><span className="text-sm">{t.consent}</span></label><button disabled={busy||!confirmed||Number(amount)<1||Number(amount)>1_000_000_000} className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 px-5 font-bold text-white transition-colors hover:bg-emerald-800 disabled:cursor-not-allowed disabled:bg-slate-300 disabled:text-slate-600">{busy&&<span aria-hidden="true" className="size-5 animate-spin rounded-full border-2 border-white/40 border-t-white"/>}{busy?t.sending:t.submit}</button></form></>}</div></section></main>;
}
function Field({label,help,error,...props}:{label:string;help?:string;error?:string}&React.InputHTMLAttributes<HTMLInputElement>){const id=props.name;return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><input {...props} aria-invalid={error?true:undefined} aria-describedby={error?`${id}-error`:help?`${id}-help`:undefined} className={`min-h-12 w-full rounded-xl border px-3 text-base focus:outline-none focus:ring-2 ${error?"border-red-500 focus:border-red-600 focus:ring-red-100":"border-slate-300 focus:border-emerald-600 focus:ring-emerald-100"}`}/>{error?<span id={`${id}-error`} role="alert" className="mt-2 block text-sm font-medium text-red-700">{error}</span>:help&&<span id={`${id}-help`} className="mt-2 block text-sm text-slate-500">{help}</span>}</label>}
