"use client";
import { useEffect, useRef, useState } from "react";

type Language = "sw" | "en";
type LinkInfo = { event_name:string; title:string|null; message:string|null; language:Language };
const copy = {
  sw:{support:"Toa Ahadi ya Mchango",intro:"Jaza fomu hii rahisi kuonyesha ahadi yako ya kusaidia tukio.",name:"Jina kamili",phone:"Namba ya simu (hiari)",phoneHelp:"Namba ya simu unaweza kuongeza ili kupokea vikumbusho.",email:"Barua pepe (hiari)",amount:"Kiasi cha ahadi (TZS)",date:"Tarehe unayotarajia kukamilisha (hiari)",note:"Ujumbe au maelezo (hiari)",consent:"Nathibitisha kuwa hii ni ahadi yangu ya mchango.",submit:"Tuma ahadi",sending:"Inatuma...",success:"Asante, ahadi yako imepokelewa.",thanks:"Tunakushukuru kwa moyo wako wa ushirikiano.",review:"Tumepokea ombi lako na timu ya tukio italihakiki.",error:"Tafadhali rekebisha sehemu zenye makosa.",unavailable:"Link hii ya ahadi haipatikani au muda wake umeisha."},
  en:{support:"Make a Contribution Pledge",intro:"Complete this short form to pledge your support for the event.",name:"Full name",phone:"Phone (optional)",phoneHelp:"Add a phone number if you would like to receive reminders.",email:"Email (optional)",amount:"Pledge amount (TZS)",date:"Expected completion date (optional)",note:"Message or note (optional)",consent:"I confirm this contribution pledge.",submit:"Submit pledge",sending:"Submitting...",success:"Thank you, your pledge has been received.",thanks:"We truly appreciate your generous support.",review:"We received your request and the event team will review it.",error:"Please correct the highlighted fields.",unavailable:"This pledge link is unavailable or has expired."}
} as const;

export default function PublicPledgeForm({token}:{token:string}) {
  const [info,setInfo]=useState<LinkInfo|null>(null),[language,setLanguage]=useState<Language>("sw"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<"received"|"review"|null>(null);
  const started=useRef(0),idempotency=useRef(""),t=copy[language];
  useEffect(()=>{started.current=Date.now();idempotency.current=crypto.randomUUID()},[]);
  useEffect(()=>{void fetch(`/api/public/pledges?token=${encodeURIComponent(token)}`,{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error);setInfo(p);setLanguage(p.language);}).catch(e=>setError(e instanceof Error?e.message:copy.sw.unavailable)).finally(()=>setLoading(false));},[token]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const body={token,idempotencyKey:idempotency.current,durationMs:Date.now()-started.current,website:form.get("website"),fullName:form.get("fullName"),phone:form.get("phone"),email:form.get("email"),amount:form.get("amount"),expectedDate:form.get("expectedDate"),note:form.get("note")};try{const response=await fetch("/api/public/pledges",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||t.error);setResult(payload.status);}catch(e){setError(e instanceof Error?e.message:t.error);}finally{setBusy(false)}}
  if(loading)return <main className="grid min-h-screen place-items-center bg-[#f6f2e9] p-4"><p aria-live="polite">Loading...</p></main>;
  if(!info)return <main className="grid min-h-screen place-items-center bg-[#f6f2e9] p-4"><section className="max-w-md rounded-3xl bg-white p-8 text-center shadow-xl"><h1 className="text-2xl font-bold">Smart Event Pass</h1><p className="mt-4 text-slate-600" role="alert">{error||t.unavailable}</p></section></main>;
  return <main className="min-h-screen overflow-x-hidden bg-[#f6f2e9] px-4 py-8 text-slate-950 sm:py-12"><section className="mx-auto w-full max-w-xl overflow-hidden rounded-3xl border border-amber-100 bg-white shadow-[0_24px_70px_rgba(62,45,20,.12)]"><header className="bg-slate-950 px-6 py-7 text-white sm:px-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Smart Event Pass</p><h1 className="mt-3 text-3xl font-bold">{info.title||t.support}</h1><p className="mt-2 text-slate-300">{info.event_name}</p></div><button type="button" onClick={()=>setLanguage(v=>v==="sw"?"en":"sw")} className="min-h-12 rounded-xl border border-white/30 px-3 font-semibold">{language==="sw"?"EN":"SW"}</button></div></header><div className="p-6 sm:p-8">{result?<div aria-live="polite" className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center"><div className="text-4xl">✓</div><h2 className="mt-3 text-xl font-bold text-emerald-950">{result==="review"?t.review:t.success}</h2><p className="mt-2 text-emerald-800">{t.thanks}</p></div>:<><p className="text-slate-600">{info.message||t.intro}</p>{error&&<div role="alert" aria-live="assertive" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}<form onSubmit={submit} className="mt-6 space-y-5"><input name="website" tabIndex={-1} autoComplete="off" className="absolute -left-[9999px]" aria-hidden="true"/><Field label={t.name} name="fullName" required minLength={2} maxLength={160}/><Field label={t.phone} name="phone" type="tel" inputMode="tel" help={t.phoneHelp}/><Field label={t.email} name="email" type="email" inputMode="email"/><Field label={t.amount} name="amount" type="number" inputMode="decimal" required min="1" max="1000000000" step="1"/><Field label={t.date} name="expectedDate" type="date"/><label className="block"><span className="mb-2 block text-sm font-semibold">{t.note}</span><textarea name="note" maxLength={1000} rows={4} className="w-full rounded-xl border border-slate-300 p-3 text-base focus:border-slate-800 focus:outline-none focus:ring-2 focus:ring-slate-300"/></label><label className="flex cursor-pointer items-start gap-3 rounded-xl bg-slate-50 p-4"><input required type="checkbox" className="mt-1 size-5"/><span className="text-sm">{t.consent}</span></label><button disabled={busy} className="min-h-12 w-full rounded-xl bg-emerald-700 px-5 font-bold text-white hover:bg-emerald-800 disabled:opacity-60">{busy?t.sending:t.submit}</button></form></>}</div></section></main>;
}
function Field({label,help,...props}:{label:string;help?:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><input {...props} className="min-h-12 w-full rounded-xl border border-slate-300 px-3 text-base focus:border-slate-800 focus:outline-none focus:ring-2 focus:ring-slate-300"/>{help&&<span className="mt-2 block text-sm text-slate-500">{help}</span>}</label>}
