"use client";

import { useCallback,useEffect,useState } from "react";
import MakeIntegrationPanel from "@/components/automation/MakeIntegrationPanel";
import { useAppLanguage } from "@/lib/i18n/useAppLanguage";
import { getAutomationCenterData,manageHeldAutomation,retryWorkflowEvent,saveSimpleAutomationSettings,setMasterAutomation,type AutomationCenterData,type SimpleAutomationSetting } from "@/services/automationCenterService";

type ReminderMode="off"|"manual"|"automatic";type AckMode="off"|"preview"|"automatic";
const words={
 en:{title:"Automation",subtitle:"Messages and reminders for your event, in one simple place.",overview:"Overview",settings:"Settings",activity:"Activity",advanced:"Advanced diagnostics",working:"Automation is working",attention:"Automation needs attention",whatsapp:"WhatsApp status",make:"Make status",nextReminder:"Next reminder",nextSummary:"Daily summary",sent:"Sent today",failed:"Failed today",test:"Send test message",event:"Event",reminder:"Reminder mode",ack:"Pledge acknowledgement",summary:"Daily summary",recipient:"Summary recipient",channel:"Summary channel",time:"Local summary time",save:"Save settings",saved:"Settings saved and verified",off:"Off",manual:"Manual",automatic:"Automatic",preview:"Preview",on:"On",recent:"Recent messages",pending:"Pending",tryAgain:"Try again",queue:"Workflow Queue",attempts:"Attempts",processor:"Cron/processor health",healthy:"Healthy",none:"Not scheduled",active:"Active",inactive:"Not configured",local:"Africa/Dar_es_Salaam"},
 sw:{title:"Automation",subtitle:"Ujumbe na vikumbusho vya tukio lako katika sehemu moja rahisi.",overview:"Muhtasari",settings:"Mipangilio",activity:"Shughuli",advanced:"Uchunguzi wa kina",working:"Automation inafanya kazi",attention:"Automation inahitaji uangalizi",whatsapp:"Hali ya WhatsApp",make:"Hali ya Make",nextReminder:"Kikumbusho kijacho",nextSummary:"Muhtasari wa kila siku",sent:"Zimetumwa leo",failed:"Zimeshindwa leo",test:"Tuma ujumbe wa majaribio",event:"Tukio",reminder:"Hali ya vikumbusho",ack:"Uthibitisho wa Ahadi",summary:"Muhtasari wa kila siku",recipient:"Mpokeaji wa muhtasari",channel:"Njia ya muhtasari",time:"Muda wa muhtasari",save:"Hifadhi mipangilio",saved:"Mipangilio imehifadhiwa na kuthibitishwa",off:"Imezimwa",manual:"Ya mkono",automatic:"Otomatiki",preview:"Hakiki",on:"Imewashwa",recent:"Ujumbe wa karibuni",pending:"Inasubiri",tryAgain:"Jaribu tena",queue:"Foleni ya mfumo",attempts:"Majaribio",processor:"Afya ya kichakataji",healthy:"Iko sawa",none:"Haijapangwa",active:"Inatumika",inactive:"Haijawekwa",local:"Africa/Dar_es_Salaam"}
} as const;
const initial=(eventId:number):SimpleAutomationSetting=>({event_id:eventId,reminders_enabled:false,reminder_frequency:"manual",pledge_acknowledgement_mode:"off",daily_summary_enabled:false,owner_summary_phone:null,daily_summary_channel:"whatsapp",daily_summary_time:"15:00:00",automatic_messaging_enabled:true,automation_paused_at:null});
function localTime(utc:string){const [h,m]=utc.slice(0,5).split(":").map(Number);return `${String((h+3)%24).padStart(2,"0")}:${String(m).padStart(2,"0")}`}
function friendly(type:string,language:"en"|"sw"){const sw=language==="sw";if(type.includes("acknowledgement"))return sw?"Ujumbe wa kuthibitisha ahadi":"Pledge acknowledgement message";if(type.includes("thank_you"))return sw?"Ujumbe wa shukrani":"Pledge thank-you message";if(type.includes("daily")||type==="daily_summary")return sw?"Muhtasari wa kila siku":"Daily summary";if(type.includes("reminder"))return sw?"Kikumbusho":"Reminder";return sw?"Shughuli ya automation":"Automation activity"}

export default function AutomationCenterDashboard(){const {language}=useAppLanguage(),t=words[language];const [data,setData]=useState<AutomationCenterData|null>(null),[eventId,setEventId]=useState<number|null>(null),[draft,setDraft]=useState<SimpleAutomationSetting|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{try{setError("");const next=await getAutomationCenterData(),selected=eventId??next.events[0]?.id??null;setData(next);setEventId(selected);setDraft(selected?(next.settings.find(x=>x.event_id===selected)??initial(selected)):null)}catch(cause){setError(cause instanceof Error?cause.message:"Automation could not be loaded.")}},[eventId]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const workflows=data?.workflows.filter(x=>x.event_id===eventId)??[],jobs=data?.jobs.filter(x=>x.event_id===eventId)??[],timeline=data?.timeline.filter(x=>x.eventId===eventId)??[],deliveries=data?.deliveries.filter(x=>x.event_id===eventId)??[];
 const heldCount=eventId?(data?.heldCounts[eventId]??0):0;
 const reminderMode:ReminderMode=draft?.reminders_enabled?(draft.reminder_frequency==="manual"?"manual":"automatic"):"off";const today=new Date().toDateString(),sent=deliveries.filter(x=>x.sent_at&&new Date(x.sent_at).toDateString()===today).length,failed=deliveries.filter(x=>x.delivery_status==="failed"&&new Date(x.created_at).toDateString()===today).length,pending=workflows.filter(x=>x.status==="pending").length,unhealthy=failed>0||workflows.some(x=>x.status==="failed"),nextReminder=jobs.find(x=>x.schedule_type!=="Daily Summary"),nextSummary=jobs.find(x=>x.schedule_type==="Daily Summary");const makeActive=timeline.some(x=>x.kind==="connector"&&!['failed','skipped'].includes(x.status));
 async function save(){if(!eventId||!draft)return;setBusy(true);setNotice("");try{await saveSimpleAutomationSettings({eventId,reminderMode,acknowledgementMode:draft.pledge_acknowledgement_mode,summaryEnabled:draft.daily_summary_enabled,summaryPhone:draft.owner_summary_phone??"",summaryChannel:draft.daily_summary_channel,localSummaryTime:localTime(draft.daily_summary_time)});await load();setNotice(t.saved)}catch(cause){setError(cause instanceof Error?cause.message:"Settings could not be saved.")}finally{setBusy(false)}}
 async function toggleMaster(){if(!eventId||!draft)return;const enabled=!draft.automatic_messaging_enabled;if(!window.confirm(enabled?"Resume automatic messaging? Held messages will remain held until you process or cancel them.":"Pause all automatic messaging for this event? Manual sending will remain available."))return;setBusy(true);setNotice("");setError("");try{await setMasterAutomation(eventId,enabled);await load();setNotice(enabled?"Automation resumed. Held messages were not released.":"Automation paused. Automatic work is now held.")}catch(cause){setError(cause instanceof Error?cause.message:"Automation state could not be saved.")}finally{setBusy(false)}}
 async function manageHeld(action:"process"|"cancel"){if(!eventId)return;const prompt=action==="process"?"Process eligible held messages now? Every item will be revalidated and automation must remain active.":"Cancel all held messages? This cannot be undone.";if(!window.confirm(prompt))return;setBusy(true);setNotice("");setError("");try{const result=await manageHeldAutomation(eventId,action);await load();setNotice(`${result.affected} held item${result.affected===1?"":"s"} ${action==="process"?"released for safe processing":"cancelled"}.`)}catch(cause){setError(cause instanceof Error?cause.message:"Held messages could not be managed.")}finally{setBusy(false)}}
 const setReminder=(mode:ReminderMode)=>setDraft(current=>current&&({...current,reminders_enabled:mode!=="off",reminder_frequency:mode==="automatic"?"weekly":"manual"}));
 return <main className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Smart Event Pass</p><h1 className="mt-2 text-3xl font-black">{t.title}</h1><p className="mt-1 text-sm text-slate-600">{t.subtitle}</p></div><label className="text-sm font-bold">{t.event}<select value={eventId??""} onChange={e=>setEventId(Number(e.target.value))} className="mt-1 min-h-12 w-full rounded-xl border bg-white px-3 sm:w-64">{data?.events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label></header>{error&&<p className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{notice}</p>}
 {draft&&<section className={`rounded-2xl border p-5 shadow-sm ${draft.automatic_messaging_enabled?"border-emerald-200 bg-emerald-50":"border-amber-300 bg-amber-50"}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-black uppercase tracking-wider">Master Automation</p><h2 className={`mt-1 text-2xl font-black ${draft.automatic_messaging_enabled?"text-emerald-800":"text-amber-900"}`}>{draft.automatic_messaging_enabled?"Automation Active":"Automation Paused"}</h2><p className="mt-2 max-w-3xl text-sm text-slate-700">{draft.automatic_messaging_enabled?"Automatic acknowledgements, payment messages, reminders, summaries, and Make workflows are enabled.":"Automatic messages for this event are paused. Manual sending is still available."}</p></div><button type="button" role="switch" aria-checked={draft.automatic_messaging_enabled} disabled={busy} onClick={()=>void toggleMaster()} className={`min-h-12 rounded-full px-5 font-black text-white disabled:opacity-50 ${draft.automatic_messaging_enabled?"bg-emerald-700":"bg-amber-700"}`}>{draft.automatic_messaging_enabled?"ON":"OFF"}</button></div><div className="mt-5 rounded-xl border border-amber-200 bg-white/80 p-4"><h3 className="font-black">Review held messages</h3><p className="mt-1 text-sm text-slate-600">{heldCount} held message{heldCount===1?"":"s"}. Resuming never releases them automatically.</p><div className="mt-3 flex flex-wrap gap-3"><button disabled={busy||heldCount===0||!draft.automatic_messaging_enabled} onClick={()=>void manageHeld("process")} className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white disabled:opacity-40">Process Held Messages</button><button disabled={busy||heldCount===0} onClick={()=>void manageHeld("cancel")} className="min-h-11 rounded-xl border border-amber-400 bg-white px-4 font-bold text-amber-900 disabled:opacity-40">Cancel Held Messages</button></div></div></section>}
 <section><h2 className="text-xl font-black">{t.overview}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label={unhealthy?t.attention:t.working} value={unhealthy?"!":"✓"}/><Card label={t.whatsapp} value={deliveries.some(x=>x.channel==="whatsapp")?t.active:t.inactive}/><Card label={t.make} value={makeActive?t.active:t.inactive}/><Card label={t.nextReminder} value={nextReminder?new Date(nextReminder.scheduled_for).toLocaleString():t.none}/><Card label={t.nextSummary} value={nextSummary?new Date(nextSummary.scheduled_for).toLocaleString(language==="sw"?"sw-TZ":"en-TZ",{timeZone:"Africa/Dar_es_Salaam"}):t.none}/><Card label={t.sent} value={String(sent)}/><Card label={t.failed} value={String(failed)}/><button disabled className="min-h-24 rounded-2xl border bg-slate-100 p-4 text-left font-bold text-slate-500">{t.test}<span className="mt-2 block text-xs font-normal">{language==="sw"?"Tumia jaribio la Make kwenye Advanced":"Use the Make test in Advanced"}</span></button></div></section>
 {draft&&<section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">{t.settings}</h2><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Choice label={t.reminder} value={reminderMode} onChange={v=>setReminder(v as ReminderMode)} options={[["off",t.off],["manual",t.manual],["automatic",t.automatic]]}/><Choice label={t.ack} value={draft.pledge_acknowledgement_mode} onChange={v=>setDraft({...draft,pledge_acknowledgement_mode:v as AckMode})} options={[["off",t.off],["preview",t.preview],["automatic",t.automatic]]}/><Choice label={t.summary} value={draft.daily_summary_enabled?"on":"off"} onChange={v=>setDraft({...draft,daily_summary_enabled:v==="on"})} options={[["off",t.off],["on",t.on]]}/><Field label={t.recipient} value={draft.owner_summary_phone??""} onChange={v=>setDraft({...draft,owner_summary_phone:v})}/><Choice label={t.channel} value={draft.daily_summary_channel} onChange={v=>setDraft({...draft,daily_summary_channel:v as SimpleAutomationSetting["daily_summary_channel"]})} options={[["sms","SMS"],["whatsapp","WhatsApp"],["both","SMS + WhatsApp"]]}/><Field label={`${t.time} · ${t.local}`} type="time" value={localTime(draft.daily_summary_time)} onChange={v=>{const [h,m]=v.split(":").map(Number);setDraft({...draft,daily_summary_time:`${String((h+21)%24).padStart(2,"0")}:${String(m).padStart(2,"0")}:00`})}}/></div><button disabled={busy} onClick={()=>void save()} className="mt-5 min-h-12 rounded-xl bg-slate-950 px-5 font-bold text-white disabled:opacity-50">{t.save}</button></section>}
 <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">{t.activity}</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Card label={t.recent} value={String(deliveries.length)}/><Card label={t.pending} value={String(pending)}/><Card label={t.failed} value={String(failed)}/></div><div className="mt-4 space-y-2">{timeline.filter(x=>x.kind==="delivery"||x.kind==="connector").slice(0,12).map(x=><article key={x.id} className="flex justify-between gap-3 rounded-xl border p-3"><div><p className="font-bold">{friendly(x.label,language)}</p><p className="text-xs text-slate-500">{new Date(x.occurredAt).toLocaleString()}</p></div><span className="text-sm capitalize">{x.status==="failed"?(language==="sw"?"Ujumbe haukutumwa":"Message could not be sent"):x.status}</span></article>)}</div></section>
 <details className="rounded-2xl border bg-white shadow-sm"><summary className="cursor-pointer p-5 text-xl font-black">{t.advanced}</summary><div className="space-y-6 border-t p-5"><div className="grid gap-3 sm:grid-cols-3"><Card label={t.processor} value={unhealthy?t.attention:t.healthy}/><Card label={t.queue} value={String(workflows.length)}/><Card label={t.attempts} value={String(workflows.reduce((n,x)=>n+x.attempt_count,0))}/></div><div className="overflow-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr><th className="p-2">Workflow</th><th>Status</th><th>{t.attempts}</th><th/></tr></thead><tbody>{workflows.map(x=><tr key={x.id} className="border-t"><td className="p-2 font-mono text-xs">{x.event_type}</td><td>{x.status}</td><td>{x.attempt_count}/5</td><td>{x.status==="failed"&&x.attempt_count<5&&<button onClick={()=>void retryWorkflowEvent(x.id).then(load)} className="rounded-lg bg-red-50 px-3 py-2 font-bold text-red-700">{t.tryAgain}</button>}</td></tr>)}</tbody></table></div><MakeIntegrationPanel eventId={eventId} events={data?.events??[]}/></div></details></main>}

function Card({label,value}:{label:string;value:string}){return <article className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-lg font-black">{value}</p></article>}
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:readonly (readonly [string,string])[]}){return <label className="text-sm font-bold">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border bg-white px-3 font-normal">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="text-sm font-bold">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border px-3 font-normal"/></label>}
