"use client";
import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { useAppLanguage } from "@/lib/i18n/useAppLanguage";

type Connector={id:number;display_name:string;webhook_url_masked:string;is_active:boolean;allowed_event_types:string[];last_success_at:string|null;last_failure_at:string|null;pendingDeliveries:number};
const events=["pledge.submitted","message.acknowledgement.requested","pledge.reminder.send_requested","payment.completed","invitation.sent","rsvp.accepted","guest.checked_in"];
const text={en:{title:"Integrations → Make",connected:"Connected",disconnected:"Disconnected",active:"Active",paused:"Paused",destination:"Webhook destination",allowed:"Allowed event types",lastSuccess:"Last successful delivery",lastFailure:"Last failure",pending:"Pending deliveries",test:"Test connection",pause:"Pause",resume:"Resume",rotate:"Rotate secret",disconnect:"Disconnect",configure:"Connect Make",save:"Connect",secret:"Copy this signing secret now. It will not be shown again.",guide:"Pledge acknowledgement setup guide",guideSteps:["Create a Make Webhooks → Custom webhook module.","Validate schemaVersion, deliveryId, idempotencyKey, eventType, event.publicReference, and subject.publicReference.","Add a router for an available recipient phone versus a missing phone.","Send through the selected approved channel. Do not calculate or change pledge state.","POST completed to the callbackUrl with the signed raw callback body.","Add an error handler that posts failed without changing Smart Event Pass business data."]},sw:{title:"Miunganisho → Make",connected:"Imeunganishwa",disconnected:"Haijaunganishwa",active:"Inatumika",paused:"Imesitishwa",destination:"Anwani ya webhook",allowed:"Aina za matukio zinazoruhusiwa",lastSuccess:"Utumaji wa mwisho uliofanikiwa",lastFailure:"Hitilafu ya mwisho",pending:"Utumaji unaosubiri",test:"Jaribu muunganisho",pause:"Sitisha",resume:"Endelea",rotate:"Badilisha siri",disconnect:"Ondoa muunganisho",configure:"Unganisha Make",save:"Unganisha",secret:"Nakili siri hii sasa. Haitaonyeshwa tena.",guide:"Mwongozo wa kuthibitisha ahadi",guideSteps:["Unda moduli ya Make Webhooks → Custom webhook.","Thibitisha schemaVersion, deliveryId, idempotencyKey, eventType, event.publicReference, na subject.publicReference.","Weka router ya simu iliyopo dhidi ya simu inayokosekana.","Tuma kupitia njia iliyoidhinishwa. Usihesabu au kubadilisha hali ya ahadi.","Tuma completed kwenye callbackUrl ukiwa umesaini raw callback body.","Weka error handler inayotuma failed bila kubadilisha data ya biashara ya Smart Event Pass."]}} as const;

export default function MakeIntegrationPanel({eventId}:{eventId:number|null}){const {language}=useAppLanguage(),t=text[language];const [connectors,setConnectors]=useState<Connector[]>([]),[url,setUrl]=useState(""),[selected,setSelected]=useState<string[]>(["pledge.submitted","message.acknowledgement.requested"]),[secret,setSecret]=useState(""),[message,setMessage]=useState("");
 const request=useCallback(async(path:string,init?:RequestInit)=>{const {data}=await supabase.auth.getSession();if(!data.session)throw new Error("Session expired.");const response=await fetch(path,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session.access_token}`,...init?.headers}}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"Request failed.");return payload},[]);
 const load=useCallback(async()=>{if(!eventId){setConnectors([]);return}try{const payload=await request(`/api/automation/make/connectors?eventId=${eventId}`);setConnectors(payload.connectors)}catch(cause){setMessage(cause instanceof Error?cause.message:"Request failed.")}},[eventId,request]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function create(){if(!eventId)return;try{const payload=await request("/api/automation/make/connectors",{method:"POST",body:JSON.stringify({eventId,webhookUrl:url,allowedEventTypes:selected})});setSecret(payload.signingSecret);setUrl("");await load()}catch(cause){setMessage(cause instanceof Error?cause.message:"Request failed.")}}
 async function action(connector:Connector,name:string){if(!eventId)return;try{const path=name==="test"?"/api/automation/make/deliveries":"/api/automation/make/connectors",payload=await request(path,{method:name==="test"?"POST":"PATCH",body:JSON.stringify({eventId,connectorId:connector.id,action:name})});if(payload.signingSecret)setSecret(payload.signingSecret);setMessage(name==="test"?`Delivery ${payload.deliveryId} · ${payload.durationMs}ms`:"");await load()}catch(cause){setMessage(cause instanceof Error?cause.message:"Request failed.")}}
 return <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">{t.title}</h2>{message&&<p className="mt-3 rounded-lg bg-slate-100 p-3 text-sm">{message}</p>}{secret&&<div className="mt-3 rounded-xl border border-amber-300 bg-amber-50 p-4"><p className="text-sm font-bold">{t.secret}</p><code className="mt-2 block break-all text-xs">{secret}</code></div>}{connectors.map(c=><article key={c.id} className="mt-4 rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-black">{c.display_name} · {c.is_active?t.active:t.paused}</h3><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">{t.connected}</span></div><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><Info label={t.destination} value={c.webhook_url_masked}/><Info label={t.pending} value={String(c.pendingDeliveries)}/><Info label={t.lastSuccess} value={c.last_success_at?new Date(c.last_success_at).toLocaleString():"—"}/><Info label={t.lastFailure} value={c.last_failure_at?new Date(c.last_failure_at).toLocaleString():"—"}/></dl><p className="mt-3 text-xs text-slate-500">{t.allowed}: {c.allowed_event_types.join(", ")}</p><div className="mt-4 flex flex-wrap gap-2"><Button onClick={()=>void action(c,"test")}>{t.test}</Button><Button onClick={()=>void action(c,c.is_active?"pause":"resume")}>{c.is_active?t.pause:t.resume}</Button><Button onClick={()=>void action(c,"rotate")}>{t.rotate}</Button><Button danger onClick={()=>void action(c,"disconnect")}>{t.disconnect}</Button></div></article>)}{eventId&&connectors.length===0&&<div className="mt-4 rounded-xl border p-4"><h3 className="font-bold">{t.configure}</h3><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://hook.make.com/…" className="mt-3 min-h-12 w-full rounded-xl border px-3"/><div className="mt-3 grid gap-2 sm:grid-cols-2">{events.map(value=><label key={value} className="flex gap-2 text-sm"><input type="checkbox" checked={selected.includes(value)} onChange={()=>setSelected(current=>current.includes(value)?current.filter(x=>x!==value):[...current,value])}/>{value}</label>)}</div><button onClick={()=>void create()} className="mt-4 min-h-12 rounded-xl bg-slate-950 px-5 font-bold text-white">{t.save}</button></div>}<details className="mt-5 rounded-xl bg-slate-50 p-4"><summary className="cursor-pointer font-bold">{t.guide}</summary><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm">{t.guideSteps.map(step=><li key={step}>{step}</li>)}</ol></details></section>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold text-slate-500">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>};function Button({children,onClick,danger=false}:{children:string;onClick:()=>void;danger?:boolean}){return <button onClick={onClick} className={`min-h-10 rounded-lg px-3 text-sm font-bold ${danger?"bg-red-50 text-red-700":"bg-slate-100 text-slate-800"}`}>{children}</button>}
