"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { pdf } from "@react-pdf/renderer";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import {
  dailySummary, exportClosingWorkbook, getAutomationSettings, getClosingReport,
  getReminderEligibility, saveAutomationSettings, type AutomationSettings, type ClosingReport,
} from "@/services/financialAutomationService";
import type { FinancialPledge } from "@/services/financialSuiteService";
import { formatTzs } from "@/services/pledgeMessageService";
import FinancialClosingPDF from "./FinancialClosingPDF";

export default function AutomationAndClosingPanel({eventId,eventDate,pledges}:{eventId:number;eventDate:string;pledges:FinancialPledge[]}) {
  const [settings,setSettings]=useState<AutomationSettings|null>(null);const [report,setReport]=useState<ClosingReport|null>(null);const [range,setRange]=useState<7|30|0>(7);
  const [selectedDate,setSelectedDate]=useState(new Date().toISOString().slice(0,10));const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [showBulk,setShowBulk]=useState(false);
  const load=useCallback(async()=>{try{setError("");const [nextSettings,nextReport]=await Promise.all([getAutomationSettings(eventId),getClosingReport(eventId)]);setSettings(nextSettings);setReport(nextReport);}catch(err){setError(err instanceof Error?err.message:"Automation data could not be loaded.");}},[eventId]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  const trend=useMemo(()=>{if(!report)return[];if(!range)return report.trend;const cutoff=new Date();cutoff.setDate(cutoff.getDate()-range+1);return report.trend.filter(p=>new Date(`${p.date}T00:00:00`)>=cutoff);},[report,range]);
  const eligibility=settings?getReminderEligibility(pledges,eventDate,settings):[];const daily=report?dailySummary(report,selectedDate):null;
  async function save(){if(!settings)return;try{setBusy(true);await saveAutomationSettings(settings);setNotice("Automation settings saved. Scheduled delivery remains disabled until cron is configured.");}catch(err){setError(err instanceof Error?err.message:"Settings could not be saved.");}finally{setBusy(false);}}
  async function downloadPdf(){if(!report)return;try{setBusy(true);const blob=await pdf(<FinancialClosingPDF report={report} generatedBy="Authenticated event manager"/>).toBlob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${report.event.title.replace(/\W+/g,"_")}_Financial_Closing.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}finally{setBusy(false);}}
  const dailyText=daily?`Today's Collection (${daily.date})\nCollected: ${formatTzs(daily.amount)}\nTransactions: ${daily.transactions}\nContributors: ${daily.contributors}\nOutstanding: ${formatTzs(daily.outstanding)}\nCollection Rate: ${daily.percentage.toFixed(1)}%`:"";
  const closingText=report?`${report.event.title} Financial Closing\nPledged: ${formatTzs(report.financial.totalPledged)}\nCollected: ${formatTzs(report.financial.totalCollected)}\nOutstanding: ${formatTzs(report.financial.outstanding)}\nCollection: ${report.financial.percentage.toFixed(1)}%\nCompleted: ${report.financial.completed} · Partial: ${report.financial.partial} · Pending: ${report.financial.pending}`:"";
  return <div className="space-y-6">{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-700">{notice}</p>}
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Reminder Automation</h2><p className="text-sm text-slate-600">Configure scheduler-ready reminders. Automatic delivery is not enabled by saving these settings.</p>{settings&&<div className="mt-4 grid gap-4 md:grid-cols-3"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={settings.reminders_enabled} onChange={e=>setSettings({...settings,reminders_enabled:e.target.checked})}/>Reminders enabled</label><label className="text-sm font-semibold">Channel<select value={settings.reminder_channel} onChange={e=>setSettings({...settings,reminder_channel:e.target.value as AutomationSettings["reminder_channel"]})} className="mt-1 w-full rounded-xl border px-3 py-2"><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option><option value="both">Both</option></select></label><label className="text-sm font-semibold">Frequency<select value={settings.reminder_frequency} onChange={e=>setSettings({...settings,reminder_frequency:e.target.value as AutomationSettings["reminder_frequency"]})} className="mt-1 w-full rounded-xl border px-3 py-2"><option value="manual">Manual only</option><option value="weekly">Weekly</option><option value="custom">Custom interval</option></select></label>{settings.reminder_frequency==="custom"&&<label className="text-sm font-semibold">Interval days<input type="number" min="1" max="365" value={settings.custom_interval_days??7} onChange={e=>setSettings({...settings,custom_interval_days:Number(e.target.value)})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>}<label className="text-sm font-semibold">Owner summary phone<input value={settings.owner_summary_phone??""} onChange={e=>setSettings({...settings,owner_summary_phone:e.target.value||null})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="text-sm font-semibold">Cooldown hours<input type="number" min="1" value={settings.reminder_cooldown_hours} onChange={e=>setSettings({...settings,reminder_cooldown_hours:Number(e.target.value)})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><div className="flex items-end gap-2"><button disabled={busy} onClick={()=>void save()} className="rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white">Save settings</button><button onClick={()=>setShowBulk(!showBulk)} className="rounded-xl border px-4 py-2 font-semibold">Bulk preview ({eligibility.filter(i=>i.eligible).length})</button></div></div>}
      {showBulk&&<div className="mt-4 rounded-xl bg-slate-50 p-4"><h3 className="font-bold">Bulk reminder preview</h3><p className="text-sm text-slate-600">{eligibility.filter(i=>i.eligible).length} eligible · {eligibility.filter(i=>!i.eligible).length} skipped</p><ul className="mt-2 max-h-48 overflow-auto text-sm">{eligibility.map(i=><li key={i.pledge.id}>{i.pledge.full_name} — {i.eligible?"Eligible":i.reason}</li>)}</ul><button disabled className="mt-3 rounded-xl bg-slate-300 px-4 py-2 font-semibold text-white">Confirm sending unavailable until provider/cron configuration</button></div>}</section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="text-xl font-bold">Collection Trend</h2><p className="text-sm text-slate-500">Valid transactions only</p></div><select value={range} onChange={e=>setRange(Number(e.target.value) as 7|30|0)} className="rounded-xl border px-3 py-2"><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={0}>Entire period</option></select></div><div className="mt-4 h-64">{trend.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tickFormatter={v=>`${Math.round(Number(v)/1000)}k`} tick={{fontSize:10}}/><Tooltip formatter={(v)=>formatTzs(String(v))}/><Area dataKey="amount" stroke="#059669" fill="#d1fae5"/></AreaChart></ResponsiveContainer>:<div className="flex h-full items-center justify-center rounded-xl bg-slate-50 text-slate-500">No collection data in this period.</div>}</div></div>
      <div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Daily Collection Summary</h2><input type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)} className="mt-3 rounded-xl border px-3 py-2"/>{daily&&<div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div>Collected<br/><b>{formatTzs(daily.amount)}</b></div><div>Transactions<br/><b>{daily.transactions}</b></div><div>Contributors<br/><b>{daily.contributors}</b></div><div>Outstanding<br/><b>{formatTzs(daily.outstanding)}</b></div></div>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void navigator.clipboard.writeText(dailyText)} className="rounded-xl border px-3 py-2 text-sm font-semibold">Copy summary</button><button onClick={()=>setNotice(`WhatsApp preview:\n${dailyText}`)} className="rounded-xl border px-3 py-2 text-sm font-semibold">WhatsApp preview</button><button onClick={()=>setNotice(`SMS preview:\n${dailyText}`)} className="rounded-xl border px-3 py-2 text-sm font-semibold">SMS preview</button></div></div></section>
    {report&&<section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Financial Closing Report</h2><p className="text-sm text-slate-600">{report.event.title} · generated preview</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Pledged",formatTzs(report.financial.totalPledged)],["Collected",formatTzs(report.financial.totalCollected)],["Outstanding",formatTzs(report.financial.outstanding)],["Collection",`${report.financial.percentage.toFixed(1)}%`],["Guests",report.guestStats.totalGuests],["Invitations",report.guestStats.totalInvitations],["Valid transactions",report.financial.validTransactions],["Voided transactions",report.financial.voidedTransactions]].map(([l,v])=><div key={l} className="rounded-xl bg-slate-50 p-3 text-sm">{l}<br/><b className="text-lg">{v}</b></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void downloadPdf()} className="rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white">Download Financial Closing PDF</button><button onClick={()=>exportClosingWorkbook(report)} className="rounded-xl border px-4 py-2 font-semibold">Export Excel</button><button onClick={()=>window.print()} className="rounded-xl border px-4 py-2 font-semibold">Print Report</button><button onClick={()=>void navigator.clipboard.writeText(closingText)} className="rounded-xl border px-4 py-2 font-semibold">Copy summary</button></div></section>}
  </div>;
}
