"use client";

import { useEffect, useMemo, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import FinancialSummaryCards from "./FinancialSummaryCards";
import RecordPaymentDialog from "./RecordPaymentDialog";
import PaymentHistoryDialog from "./PaymentHistoryDialog";
import ReceiptDialog from "./ReceiptDialog";
import { PortalDetailsForm } from "./OrganiserPortal";
import type { FinanceReceipt } from "@/services/receiptMessageService";
import type { FinanceSummary, FinancialPledge, PledgeInput, PledgePayment } from "@/services/financialSuiteService";
import { buildPledgeMessage, formatTzs } from "@/services/pledgeMessageService";

type PortalTab = "overview" | "contributors" | "payments" | "messages" | "reports";
export type PortalData={access_status:"active";event:{id:number;title:string;event_date:string;language:"sw"|"en"};permissions:Record<string,boolean>;summary:FinanceSummary;finance_target:Partial<FinanceSummary>|null;pledges:FinancialPledge[]};
type Dialog = "create" | "edit" | "payment" | "history" | null;
type PortalReport = {
  validTransactions:number;trend:Array<{date:string;amount:number;transactions:number}>;
  topContributors:Array<{name:string;amount:string}>;outstanding:Array<{name:string;amount:string}>;
};

async function portalRequest(token:string,body:Record<string,unknown>){
  const response=await fetch("/api/contributions/organiser",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,...body}),cache:"no-store"});
  const text=await response.text();const payload=text?JSON.parse(text):{};
  if(!response.ok)throw new Error(payload.error||"Request failed.");
  return payload;
}
const statusLabels={pledged:"Pending",partial:"Partial",completed:"Completed",cancelled:"Cancelled"};

export default function CommitteePortalTabbed({token,initialData,initialTab}:{token:string;initialData:PortalData;initialTab:string}){
  const [data,setData]=useState(initialData);const [query,setQuery]=useState("");const [status,setStatus]=useState("all");
  const [selected,setSelected]=useState<FinancialPledge|null>(null);const [dialog,setDialog]=useState<Dialog>(null);
  const [messageType,setMessageType]=useState<"reminder"|"thank_you"|null>(null);const [history,setHistory]=useState<PledgePayment[]>([]);
  const [newReceipt,setNewReceipt]=useState<{receipt:FinanceReceipt;verificationUrl:string}|null>(null);const [report,setReport]=useState<PortalReport|null>(null);
  const [error,setError]=useState("");const [notice,setNotice]=useState("");const router=useRouter();const pathname=usePathname();
  const allowed:PortalTab[]=["overview","contributors",...(data.permissions.record_payments||data.permissions.view_payment_history?["payments" as const]:[]),...(data.permissions.send_reminders||data.permissions.send_thank_you?["messages" as const]:[]),...(data.permissions.view_reports?["reports" as const]:[])];
  const active=allowed.includes(initialTab as PortalTab)?initialTab as PortalTab:allowed[0];
  const visible=useMemo(()=>data.pledges.filter(item=>(status==="all"||item.calculated_status===status)&&`${item.full_name} ${item.phone}`.toLowerCase().includes(query.toLowerCase())),[data.pledges,query,status]);
  const summary={...data.summary,...data.finance_target,budget_amount:data.finance_target?.budget_amount??null,contribution_deadline:data.finance_target?.contribution_deadline??null,budget_progress_percentage:data.finance_target?.budget_progress_percentage??null,remaining_to_budget:data.finance_target?.remaining_to_budget??null,days_remaining:data.finance_target?.days_remaining??null,deadline_status:data.finance_target?.deadline_status??"No deadline",active_pledge_count:data.pledges.filter(item=>item.calculated_status!=="cancelled").length,total_contributors:data.pledges.filter(item=>item.calculated_status!=="cancelled").length,pledged_count:data.pledges.filter(item=>item.calculated_status==="pledged").length,partial_count:data.pledges.filter(item=>item.calculated_status==="partial").length,completed_count:data.pledges.filter(item=>item.calculated_status==="completed").length,cancelled_count:data.pledges.filter(item=>item.calculated_status==="cancelled").length};
  useEffect(()=>{if(active!=="reports"||report)return;const timer=setTimeout(()=>void portalRequest(token,{action:"portal_report"}).then(setReport).catch(err=>setError(err instanceof Error?err.message:"Report could not be loaded.")),0);return()=>clearTimeout(timer);},[active,report,token]);
  async function refresh(message?:string){const next=await portalRequest(token,{action:"refresh"});if(next.access_status!=="active")throw new Error("This access link is no longer active.");setData(next);if(message)setNotice(message);}
  async function saveDetails(values:PledgeInput){await portalRequest(token,{action:dialog==="edit"?"edit_pledge":"create_pledge",pledgeId:selected?.id,fullName:values.fullName,phone:values.phone,email:values.email,pledgedAmount:values.pledgedAmount,notes:values.notes});setDialog(null);await refresh(dialog==="edit"?"Contributor updated.":"Pledge created.");}
  async function openHistory(item:FinancialPledge){try{setSelected(item);const result=await portalRequest(token,{action:"payment_history",pledgeId:item.id});setHistory(result.payments??[]);setDialog("history");}catch(err){setError(err instanceof Error?err.message:"History could not be loaded.");}}
  function action(item:FinancialPledge,next:"edit"|"payment"|"history"|"reminder"|"thank_you"){if(next==="history"){void openHistory(item);return;}setSelected(item);if(next==="reminder"||next==="thank_you")setMessageType(next);else setDialog(next);}
  return <main className="min-h-screen overflow-x-hidden bg-slate-100">
    <header className="bg-slate-950 px-4 py-5 text-white"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-400">Smart Event Pass · Committee Portal</p><h1 className="mt-1 text-xl font-bold">{data.event.title}</h1><p className="text-sm text-slate-300">{new Date(`${data.event.event_date}T00:00:00`).toLocaleDateString()}</p></div></header>
    <div className="mx-auto max-w-6xl space-y-4 p-3 sm:p-6">{notice&&<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      <div className="grid grid-cols-2 overflow-hidden rounded-2xl bg-white shadow-sm sm:grid-cols-4">{[["Contributors",summary.total_contributors],["Pledged",formatTzs(summary.total_pledged)],["Collected",formatTzs(summary.total_collected)],["Outstanding",formatTzs(summary.remaining_balance)]].map(([label,value])=><div key={label} className="border-b border-r border-slate-100 p-3"><p className="text-xs text-slate-500">{label}</p><b className="text-sm sm:text-base">{value}</b></div>)}</div>
      <nav className="-mx-3 overflow-x-auto border-b px-3"><div className="flex min-w-max">{allowed.map(tab=><button key={tab} onClick={()=>router.push(`${pathname}?tab=${tab}`,{scroll:false})} className={`min-h-11 border-b-2 px-4 text-sm font-semibold capitalize ${active===tab?"border-emerald-600 text-emerald-700":"border-transparent text-slate-600"}`}>{tab}</button>)}</div></nav>
      {active==="overview"&&<div className="space-y-4"><FinancialSummaryCards summary={summary}/><section className="rounded-2xl bg-white p-4 shadow-sm"><h2 className="font-bold">Quick navigation</h2><div className="mt-3 grid grid-cols-2 gap-2">{allowed.filter(tab=>tab!=="overview").map(tab=><button key={tab} onClick={()=>router.push(`${pathname}?tab=${tab}`,{scroll:false})} className="min-h-11 rounded-xl border text-sm font-semibold capitalize">Open {tab}</button>)}</div></section></div>}
      {active==="contributors"&&<section className="rounded-2xl bg-white shadow-sm"><div className="flex flex-col gap-2 border-b p-3 sm:flex-row">{data.permissions.search&&<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search name or phone" className="min-h-11 flex-1 rounded-xl border px-3"/>}<select value={status} onChange={event=>setStatus(event.target.value)} className="min-h-11 rounded-xl border px-3"><option value="all">All statuses</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{data.permissions.create_pledges&&<button onClick={()=>{setSelected(null);setDialog("create");}} className="rounded-xl bg-emerald-600 px-4 py-2 font-semibold text-white">+ New pledge</button>}</div><div className="grid gap-3 p-3 sm:grid-cols-2">{visible.map(item=><ContributorCard key={item.id} item={item} permissions={data.permissions} onAction={next=>action(item,next)}/>)}</div></section>}
      {active==="payments"&&<section className="rounded-2xl bg-white p-4 shadow-sm"><h2 className="text-xl font-bold">Payments</h2><p className="text-sm text-slate-600">Record payments and open event-scoped receipt history. Correction and voiding are not available.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.pledges.filter(item=>item.calculated_status!=="cancelled").map(item=><ContributorCard key={item.id} item={item} permissions={{record_payments:data.permissions.record_payments,view_payment_history:data.permissions.view_payment_history}} onAction={next=>action(item,next)}/>)}</div></section>}
      {active==="messages"&&<div className="space-y-4">{data.permissions.send_reminders&&<MessageList title="Outstanding Reminders" rows={data.pledges.filter(item=>item.calculated_status!=="cancelled"&&Number(item.balance)>0)} action="Reminder preview" onSelect={item=>action(item,"reminder")}/>} {data.permissions.send_thank_you&&<MessageList title="Completed Thank You" rows={data.pledges.filter(item=>item.calculated_status!=="cancelled"&&Number(item.balance)===0&&Number(item.total_paid)>=Number(item.pledged_amount))} action="Thank You preview" onSelect={item=>action(item,"thank_you")}/>}</div>}
      {active==="reports"&&<ReportsPanel summary={summary} report={report}/>}
    </div>
    <footer className="p-6 text-center text-sm text-slate-500">Managed securely by Smart Event Pass</footer>
    {dialog&&<Modal><h2 className="mb-4 text-xl font-bold">{dialog==="create"?"Create pledge":dialog==="edit"?"Edit contributor":dialog==="payment"?"Record payment":"Payment history"}</h2>{(dialog==="create"||dialog==="edit")&&<PortalDetailsForm pledge={selected} onSave={saveDetails} onClose={()=>setDialog(null)}/>} {dialog==="payment"&&selected&&<RecordPaymentDialog pledge={selected} onClose={()=>setDialog(null)} onSave={async values=>{const result=await portalRequest(token,{action:"record_payment",pledgeId:selected.id,...values});const issued=await portalRequest(token,{action:"issue_receipt",pledgeId:selected.id,receiptNumber:result.receipt_number});setDialog(null);setNewReceipt(issued);await refresh(`Payment recorded. Receipt ${result.receipt_number}.`);}}/>} {dialog==="history"&&<PaymentHistoryDialog payments={history} language={data.event.language} issueReceipt={receiptNumber=>portalRequest(token,{action:"issue_receipt",pledgeId:selected?.id,receiptNumber})} onClose={()=>setDialog(null)}/>}</Modal>}
    {selected&&messageType&&<PortalMessageDialog token={token} pledge={selected} event={data.event} type={messageType} onClose={()=>{setSelected(null);setMessageType(null);}}/>}
    {newReceipt&&<Modal><ReceiptDialog {...newReceipt} language={data.event.language} onClose={()=>setNewReceipt(null)}/></Modal>}
  </main>;
}

function Modal({children}:{children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-3"><div className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-5">{children}</div></div>;}
function ContributorCard({item,permissions,onAction}:{item:FinancialPledge;permissions:Record<string,boolean>;onAction:(next:"edit"|"payment"|"history"|"reminder"|"thank_you")=>void}){const completed=Number(item.balance)===0&&Number(item.total_paid)>=Number(item.pledged_amount)&&item.calculated_status!=="cancelled";return <article className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-2"><div><b>{item.full_name}</b><p className="text-sm text-slate-500">{item.phone}</p></div><span className="text-xs font-bold">{statusLabels[item.calculated_status]}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div>Pledged<br/><b>{formatTzs(item.pledged_amount)}</b></div><div>Paid<br/><b>{formatTzs(item.total_paid)}</b></div><div>Balance<br/><b>{formatTzs(item.balance)}</b></div></div><div className="mt-3 flex flex-wrap gap-3 text-sm font-semibold">{permissions.record_payments&&!completed&&<button onClick={()=>onAction("payment")} className="text-emerald-700">Record payment</button>}{permissions.view_payment_history&&<button onClick={()=>onAction("history")} className="text-slate-700">Payment history</button>}{permissions.edit_contributors&&<button onClick={()=>onAction("edit")} className="text-blue-700">Edit details</button>}{permissions.send_reminders&&!completed&&<button onClick={()=>onAction("reminder")} className="text-amber-700">Reminder preview</button>}{permissions.send_thank_you&&completed&&<button onClick={()=>onAction("thank_you")} className="text-emerald-700">Thank You Preview</button>}</div></article>;}
function MessageList({title,rows,action,onSelect}:{title:string;rows:FinancialPledge[];action:string;onSelect:(item:FinancialPledge)=>void}){return <section className="rounded-2xl bg-white p-4 shadow-sm"><h2 className="text-xl font-bold">{title}</h2><div className="mt-3 space-y-2">{rows.length?rows.map(item=><div key={item.id} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><b>{item.full_name}</b><p className="text-xs text-slate-500">{item.phone}</p></div><button onClick={()=>onSelect(item)} className="rounded-lg border px-3 py-2 text-sm font-semibold">{action}</button></div>):<p className="py-5 text-center text-sm text-slate-500">No contributors in this section.</p>}</div></section>;}
function ReportsPanel({summary,report}:{summary:Parameters<typeof FinancialSummaryCards>[0]["summary"];report:PortalReport|null}){return <div className="space-y-4"><section className="rounded-2xl bg-white p-4 shadow-sm"><h2 className="text-xl font-bold">Read-only Financial Report</h2><FinancialSummaryCards summary={summary}/><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Completed",summary.completed_count],["Partial",summary.partial_count],["Pending",summary.pledged_count],["Valid transactions",report?.validTransactions??"…"]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3 text-sm">{label}<br/><b className="text-xl">{value}</b></div>)}</div></section>{report&&<><section className="rounded-2xl bg-white p-4 shadow-sm"><h2 className="text-lg font-bold">Collection Trend</h2><div className="mt-3 h-60">{report.trend.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={report.trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tickFormatter={value=>`${Math.round(Number(value)/1000)}k`}/><Tooltip formatter={value=>formatTzs(String(value))}/><Area dataKey="amount" stroke="#059669" fill="#d1fae5"/></AreaChart></ResponsiveContainer>:<p className="py-16 text-center text-slate-500">No collection data.</p>}</div></section><section className="grid gap-4 sm:grid-cols-2"><Ranking title="Top contributors" rows={report.topContributors}/><Ranking title="Largest outstanding balances" rows={report.outstanding}/></section></>}</div>;}
function Ranking({title,rows}:{title:string;rows:Array<{name:string;amount:string}>}){return <div className="rounded-2xl bg-white p-4 shadow-sm"><h2 className="font-bold">{title}</h2><div className="mt-3 space-y-2">{rows.map((row,index)=><div key={`${row.name}-${index}`} className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>{index+1}. {row.name}</span><b>{formatTzs(row.amount)}</b></div>)}</div></div>;}
function PortalMessageDialog({token,pledge,event,type,onClose}:{token:string;pledge:FinancialPledge;event:PortalData["event"];type:"reminder"|"thank_you";onClose:()=>void}){const [channel,setChannel]=useState<"sms"|"whatsapp">("sms");const [preview,setPreview]=useState<{rows:Array<{message:string;eligible:boolean;skippedReason:string|null}>;provider:Record<"sms"|"whatsapp",{configured:boolean;message:string}>}|null>(null);const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const row=preview?.rows[0];const fallback=buildPledgeMessage(type==="thank_you"?"pledge_thank_you":"pledge_reminder",event.language,{guestName:pledge.full_name,eventTitle:event.title,pledgedAmount:pledge.pledged_amount,totalPaid:pledge.total_paid,balance:pledge.balance});async function load(){try{setBusy(true);setPreview(await portalRequest(token,{action:type==="thank_you"?"thank_you_preview":"reminder_preview",pledgeId:pledge.id,channel}));}catch(err){setError(err instanceof Error?err.message:"Preview failed.");}finally{setBusy(false);}}return <Modal><h2 className="text-xl font-bold">{type==="thank_you"?"Completed Thank You":"Outstanding Reminder"}</h2><select value={channel} onChange={event=>{setChannel(event.target.value as "sms"|"whatsapp");setPreview(null);setConfirmed(false);}} className="mt-3 min-h-11 w-full rounded-xl border px-3"><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select><pre className="mt-3 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm">{row?.message??fallback}</pre>{preview&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm">{row?.eligible?preview.provider[channel].message:`Not eligible: ${row?.skippedReason}`}</p>}{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I explicitly confirm this send.</label><div className="sticky bottom-0 mt-4 flex justify-end gap-2 bg-white py-2"><button onClick={onClose} className="rounded-xl border px-4 py-2">Close</button><button disabled={busy} onClick={()=>void load()} className="rounded-xl border px-4 py-2">Preview</button><button disabled={busy||!confirmed||!row?.eligible||!preview?.provider[channel].configured} onClick={async()=>{try{setBusy(true);await portalRequest(token,{action:type==="thank_you"?"thank_you_send":"send_reminder",pledgeId:pledge.id,channel,confirmed:true});onClose();}catch(err){setError(err instanceof Error?err.message:"Send failed.");}finally{setBusy(false);}}} className="rounded-xl bg-emerald-600 px-4 py-2 font-semibold text-white disabled:opacity-40">Send</button></div></Modal>;}
