"use client";
import { useEffect,useMemo,useState } from "react";
import { usePathname,useRouter } from "next/navigation";
import { Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import RecordPaymentDialog from "./RecordPaymentDialog";import PaymentHistoryDialog from "./PaymentHistoryDialog";import ReceiptDialog from "./ReceiptDialog";import { PortalDetailsForm } from "./OrganiserPortal";
import type { FinanceReceipt } from "@/services/receiptMessageService";
import type { FinanceSummary,FinancialPledge,PledgeInput,PledgePayment } from "@/services/financialSuiteService";
import { buildPledgeMessage,formatTzs } from "@/services/pledgeMessageService";

type Tab="overview"|"contributors"|"payments"|"messages"|"reports";type Dialog="create"|"edit"|"payment"|"history"|null;
export type PortalData={access_status:"active";event:{id:number;title:string;event_date:string;language:"sw"|"en"};permissions:Record<string,boolean>;summary:FinanceSummary;finance_target:Partial<FinanceSummary>|null;pledges:FinancialPledge[]};
type Report={validTransactions:number;trend:Array<{date:string;amount:number;transactions:number}>;topContributors:Array<{name:string;amount:string}>;outstanding:Array<{name:string;amount:string}>};
type MessageStatus={pledge_id:number;reminder_type:string;channel:"sms"|"whatsapp";delivery_status:string;created_at:string};
const copy={
 en:{portal:"Committee Portal",tabs:{overview:"Overview",contributors:"Contributors",payments:"Payments",messages:"Messages",reports:"Reports"},contributors:"Total Contributors",completed:"Completed",partial:"Partial",pending:"Pending",pledged:"Total Pledged",collected:"Total Collected",outstanding:"Outstanding",percentage:"Collection Percentage",budget:"Event Budget",remainingBudget:"Remaining to budget",deadline:"Contribution deadline",days:"Days remaining",deadlineStatus:"Deadline status",pledgeProgress:"Pledge collection",budgetProgress:"Budget progress",search:"Search by name or phone",all:"All",record:"Record Payment",history:"Payment History",edit:"Edit details",newPledge:"New pledge",paymentsIntro:"Record new payments and review contributors’ payment history and receipts.",messagesIntro:"Preview and send the correct message for each contributor’s current financial status.",financialStatus:"Financial status",deliveryStatus:"Delivery status",channel:"Channel",notSent:"Not sent",sent:"Sent",delivered:"Delivered",read:"Read",failed:"Failed",preview:"Preview Message",send:"Send Message",thankPreview:"Preview Thank You",thankSend:"Send Thank You",confirm:"I explicitly confirm this send.",close:"Close",report:"Read-only Financial Report",trend:"Collection Trend",top:"Top contributors",balances:"Largest outstanding balances",transactions:"Valid transactions",empty:"No matching contributors.",loading:"Loading…",managed:"Managed securely by Smart Event Pass"},
 sw:{portal:"Tovuti ya Kamati",tabs:{overview:"Muhtasari",contributors:"Wachangiaji",payments:"Malipo",messages:"Ujumbe",reports:"Ripoti"},contributors:"Jumla ya Wachangiaji",completed:"Waliokamilisha",partial:"Waliopunguza",pending:"Bado Hawajaanza",pledged:"Jumla ya Ahadi",collected:"Jumla Iliyopokelewa",outstanding:"Salio",percentage:"Asilimia Iliyokusanywa",budget:"Bajeti ya Tukio",remainingBudget:"Salio la bajeti",deadline:"Mwisho wa michango",days:"Siku zilizobaki",deadlineStatus:"Hali ya mwisho",pledgeProgress:"Maendeleo ya michango",budgetProgress:"Maendeleo ya bajeti",search:"Tafuta kwa jina au simu",all:"Zote",record:"Rekodi Malipo",history:"Historia ya Malipo",edit:"Hariri taarifa",newPledge:"Ahadi mpya",paymentsIntro:"Rekodi malipo mapya, angalia historia ya malipo na risiti za wachangiaji.",messagesIntro:"Hakiki na tuma ujumbe sahihi kulingana na hali ya sasa ya mchango.",financialStatus:"Hali ya mchango",deliveryStatus:"Hali ya ujumbe",channel:"Njia",notSent:"Haijatumwa",sent:"Imetumwa",delivered:"Imewasilishwa",read:"Imesomwa",failed:"Imeshindikana",preview:"Hakiki Ujumbe",send:"Tuma Ujumbe",thankPreview:"Hakiki Ujumbe wa Shukrani",thankSend:"Tuma Shukrani",confirm:"Ninathibitisha kutuma ujumbe huu.",close:"Funga",report:"Ripoti ya Fedha ya Kusoma",trend:"Mwenendo wa Makusanyo",top:"Wachangiaji wakuu",balances:"Salio kubwa zaidi",transactions:"Miamala halali",empty:"Hakuna wachangiaji wanaolingana.",loading:"Inapakia…",managed:"Inasimamiwa kwa usalama na Smart Event Pass"}
} as const;
async function request(token:string,body:Record<string,unknown>){const response=await fetch("/api/contributions/organiser",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,...body}),cache:"no-store"});const text=await response.text();const payload=text?JSON.parse(text):{};if(!response.ok)throw new Error(payload.error||"Request failed.");return payload;}

export default function CommitteePortalTabbed({token,initialData,initialTab}:{token:string;initialData:PortalData;initialTab:string}){
 const [data,setData]=useState(initialData);const [query,setQuery]=useState("");const [status,setStatus]=useState("all");const [paymentQuery,setPaymentQuery]=useState("");const [paymentStatus,setPaymentStatus]=useState("all");const [messageQuery,setMessageQuery]=useState("");const [messageStatus,setMessageStatus]=useState("all");const [delivery,setDelivery]=useState("not_sent");const [channel,setChannel]=useState<"whatsapp"|"sms">("whatsapp");
 const [selected,setSelected]=useState<FinancialPledge|null>(null);const [dialog,setDialog]=useState<Dialog>(null);const [messageType,setMessageType]=useState<"reminder"|"thank_you"|null>(null);const [history,setHistory]=useState<PledgePayment[]>([]);const [receipt,setReceipt]=useState<{receipt:FinanceReceipt;verificationUrl:string}|null>(null);const [report,setReport]=useState<Report|null>(null);const [messageStatuses,setMessageStatuses]=useState<MessageStatus[]>([]);const [error,setError]=useState("");const router=useRouter();const pathname=usePathname();const t=copy[data.event.language==="sw"?"sw":"en"];
 const allowed:Tab[]=["overview","contributors",...(data.permissions.record_payments||data.permissions.view_payment_history?["payments" as const]:[]),...(data.permissions.send_reminders||data.permissions.send_thank_you?["messages" as const]:[]),...(data.permissions.view_reports?["reports" as const]:[])];const active=allowed.includes(initialTab as Tab)?initialTab as Tab:allowed[0];
 const activePledges=data.pledges.filter(item=>item.calculated_status!=="cancelled");const summary={...data.summary,...data.finance_target,budget_amount:data.finance_target?.budget_amount??null,contribution_deadline:data.finance_target?.contribution_deadline??null,budget_progress_percentage:data.finance_target?.budget_progress_percentage??null,remaining_to_budget:data.finance_target?.remaining_to_budget??null,days_remaining:data.finance_target?.days_remaining??null,deadline_status:data.finance_target?.deadline_status??"No deadline",active_pledge_count:activePledges.length,total_contributors:activePledges.length,pledged_count:activePledges.filter(item=>item.calculated_status==="pledged").length,partial_count:activePledges.filter(item=>item.calculated_status==="partial").length,completed_count:activePledges.filter(item=>item.calculated_status==="completed").length,cancelled_count:data.pledges.filter(item=>item.calculated_status==="cancelled").length};
 const contributors=useMemo(()=>data.pledges.filter(item=>(status==="all"||item.calculated_status===status)&&`${item.full_name} ${item.phone}`.toLowerCase().includes(query.toLowerCase())),[data.pledges,query,status]);
 const payments=useMemo(()=>activePledges.filter(item=>(paymentStatus==="all"||item.calculated_status===paymentStatus)&&`${item.full_name} ${item.phone}`.toLowerCase().includes(paymentQuery.toLowerCase())),[activePledges,paymentQuery,paymentStatus]);
 function derived(item:FinancialPledge){return Number(item.balance)===0&&Number(item.total_paid)>=Number(item.pledged_amount)?"completed":Number(item.total_paid)>0?"partial":"pledged";}
 function latest(item:FinancialPledge){const type=derived(item)==="completed"?"pledge_thank_you":"pledge_reminder";return messageStatuses.find(row=>row.pledge_id===item.id&&row.reminder_type===type&&row.channel===channel)?.delivery_status??"not_sent";}
 const messages=activePledges.filter(item=>{const financial=derived(item);const state=latest(item);return(messageStatus==="all"||financial===messageStatus)&&(delivery==="all"||state===delivery)&&`${item.full_name} ${item.phone}`.toLowerCase().includes(messageQuery.toLowerCase());});
 useEffect(()=>{if(active!=="reports"||report)return;const timer=setTimeout(()=>void request(token,{action:"portal_report"}).then(setReport).catch(err=>setError(String(err))),0);return()=>clearTimeout(timer);},[active,report,token]);
 useEffect(()=>{if(active!=="messages")return;const timer=setTimeout(()=>void request(token,{action:"message_statuses"}).then(result=>setMessageStatuses(result.statuses??[])).catch(err=>setError(String(err))),0);return()=>clearTimeout(timer);},[active,token]);
 async function refresh(){setData(await request(token,{action:"refresh"}));}
 async function saveDetails(values:PledgeInput){await request(token,{action:dialog==="edit"?"edit_pledge":"create_pledge",pledgeId:selected?.id,fullName:values.fullName,phone:values.phone,email:values.email,pledgedAmount:values.pledgedAmount,notes:values.notes});setDialog(null);await refresh();}
 async function openHistory(item:FinancialPledge){setSelected(item);const result=await request(token,{action:"payment_history",pledgeId:item.id});setHistory(result.payments??[]);setDialog("history");}
 function act(item:FinancialPledge,next:"edit"|"payment"|"history"|"message"){if(next==="history"){void openHistory(item);return;}setSelected(item);if(next==="message")setMessageType(derived(item)==="completed"?"thank_you":"reminder");else setDialog(next);}
 return <main className="min-h-screen overflow-x-hidden bg-slate-100"><header className="bg-slate-950 px-4 py-4 text-white"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-400">Smart Event Pass · {t.portal}</p><h1 className="mt-1 text-xl font-bold">{data.event.title}</h1><p className="text-sm text-slate-300">{new Intl.DateTimeFormat(data.event.language==="sw"?"sw-TZ":"en-GB",{dateStyle:"medium"}).format(new Date(`${data.event.event_date}T00:00:00`))}</p></div></header><nav className="sticky top-0 z-20 overflow-x-auto border-b bg-white px-3"><div className="mx-auto flex min-w-max max-w-6xl">{allowed.map(tab=><button key={tab} onClick={()=>router.push(`${pathname}?tab=${tab}`,{scroll:false})} className={`min-h-11 border-b-2 px-4 text-sm font-semibold ${active===tab?"border-emerald-600 text-emerald-700":"border-transparent text-slate-600"}`}>{t.tabs[tab]}</button>)}</div></nav><div className="mx-auto max-w-6xl space-y-4 p-3 sm:p-6">{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 {active==="overview"&&<Overview summary={summary} t={t}/>}
 {active==="contributors"&&<section className="rounded-2xl bg-white shadow-sm"><Filters search={query} setSearch={setQuery} status={status} setStatus={setStatus} t={t}/>{data.permissions.create_pledges&&<button onClick={()=>{setSelected(null);setDialog("create");}} className="mx-3 mt-3 rounded-xl bg-emerald-600 px-4 py-2 font-semibold text-white">+ {t.newPledge}</button>}<div className="grid gap-3 p-3 sm:grid-cols-2">{contributors.map(item=><Card key={item.id} item={item} t={t} actions={<>{data.permissions.record_payments&&Number(item.balance)>0&&<button onClick={()=>act(item,"payment")} className="text-emerald-700">{t.record}</button>}{data.permissions.view_payment_history&&<button onClick={()=>act(item,"history")} className="text-slate-700">{t.history}</button>}{data.permissions.edit_contributors&&<button onClick={()=>act(item,"edit")} className="text-blue-700">{t.edit}</button>}</>}/>)}</div></section>}
 {active==="payments"&&<section className="rounded-2xl bg-white p-3 shadow-sm"><h2 className="text-xl font-bold">{t.tabs.payments}</h2><p className="mt-1 text-sm text-slate-600">{t.paymentsIntro}</p><Filters search={paymentQuery} setSearch={setPaymentQuery} status={paymentStatus} setStatus={setPaymentStatus} t={t} noCancelled/><div className="mt-3 grid gap-3 sm:grid-cols-2">{payments.map(item=><Card key={item.id} item={item} t={t} actions={<>{data.permissions.record_payments&&Number(item.balance)>0&&<button onClick={()=>act(item,"payment")} className="text-emerald-700">{t.record}</button>}{data.permissions.view_payment_history&&<button onClick={()=>act(item,"history")} className="text-slate-700">{t.history}</button>}</>}/>)}</div></section>}
 {active==="messages"&&<section className="rounded-2xl bg-white p-3 shadow-sm"><h2 className="text-xl font-bold">{t.tabs.messages}</h2><p className="mt-1 text-sm text-slate-600">{t.messagesIntro}</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input value={messageQuery} onChange={event=>setMessageQuery(event.target.value)} placeholder={t.search} className="min-h-11 rounded-xl border px-3"/><select value={messageStatus} onChange={event=>setMessageStatus(event.target.value)} className="min-h-11 rounded-xl border px-3"><option value="all">{t.all}</option><option value="completed">{t.completed}</option><option value="partial">{t.partial}</option><option value="pledged">{t.pending}</option></select><select value={delivery} onChange={event=>setDelivery(event.target.value)} className="min-h-11 rounded-xl border px-3"><option value="not_sent">{t.notSent}</option><option value="sent">{t.sent}</option><option value="delivered">{t.delivered}</option><option value="read">{t.read}</option><option value="failed">{t.failed}</option><option value="all">{t.all}</option></select><select value={channel} onChange={event=>setChannel(event.target.value as "sms"|"whatsapp")} className="min-h-11 rounded-xl border px-3"><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option></select></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{messages.map(item=>{const kind=derived(item);const canSend=kind==="completed"?data.permissions.send_thank_you:data.permissions.send_reminders;return <Card key={item.id} item={item} t={t} delivery={latest(item)} actions={canSend?<button onClick={()=>act(item,"message")} className="text-emerald-700">{kind==="completed"?t.thankPreview:t.preview}</button>:null}/>})}{!messages.length&&<p className="py-8 text-center text-sm text-slate-500">{t.empty}</p>}</div></section>}
 {active==="reports"&&<Reports summary={summary} report={report} t={t}/>}</div><footer className="p-5 text-center text-sm text-slate-500">{t.managed}</footer>
 {dialog&&<Modal><h2 className="mb-4 text-xl font-bold">{dialog==="payment"?t.record:dialog==="history"?t.history:dialog==="create"?t.newPledge:t.edit}</h2>{(dialog==="create"||dialog==="edit")&&<PortalDetailsForm pledge={selected} onSave={saveDetails} onClose={()=>setDialog(null)}/>} {dialog==="payment"&&selected&&<RecordPaymentDialog pledge={selected} onClose={()=>setDialog(null)} onSave={async values=>{const result=await request(token,{action:"record_payment",pledgeId:selected.id,...values});setReceipt(await request(token,{action:"issue_receipt",pledgeId:selected.id,receiptNumber:result.receipt_number}));setDialog(null);await refresh();}}/>} {dialog==="history"&&<PaymentHistoryDialog payments={history} language={data.event.language} issueReceipt={receiptNumber=>request(token,{action:"issue_receipt",pledgeId:selected?.id,receiptNumber})} onClose={()=>setDialog(null)}/>}</Modal>}{selected&&messageType&&<MessageDialog token={token} pledge={selected} event={data.event} type={messageType} channel={channel} t={t} onClose={()=>{setSelected(null);setMessageType(null);}}/>}{receipt&&<Modal><ReceiptDialog {...receipt} language={data.event.language} onClose={()=>setReceipt(null)}/></Modal>}</main>;
}

function Overview({summary,t}:{summary:FinanceSummary;t:typeof copy.en|typeof copy.sw}){const collection=Math.min(100,Number(summary.completion_percentage||0));const budget=summary.budget_amount?Math.min(100,Number(summary.budget_progress_percentage||0)):null;const cards=[[t.contributors,summary.total_contributors],[t.percentage,`${summary.completion_percentage}%`],[t.pledged,formatTzs(summary.total_pledged)],[t.collected,formatTzs(summary.total_collected)],[t.outstanding,formatTzs(summary.remaining_balance)],[t.completed,summary.completed_count]];return <div className="space-y-3"><div className="grid grid-cols-1 gap-2 min-[340px]:grid-cols-2">{cards.map(([label,value])=><div key={label} className="rounded-xl bg-white p-3 shadow-sm"><p className="text-xs text-slate-500">{label}</p><b className="text-base">{value}</b></div>)}</div><section className="rounded-xl bg-white p-3 shadow-sm"><Progress label={t.pledgeProgress} value={collection}/>{budget!==null&&<Progress label={t.budgetProgress} value={budget}/>}</section><section className="grid grid-cols-1 gap-2 rounded-xl bg-white p-3 shadow-sm min-[340px]:grid-cols-3"><Small label={t.deadline} value={summary.contribution_deadline??"—"}/><Small label={t.days} value={summary.days_remaining??"—"}/><Small label={t.deadlineStatus} value={summary.deadline_status}/>{summary.budget_amount&&<Small label={t.budget} value={formatTzs(summary.budget_amount)}/>} {summary.remaining_to_budget&&<Small label={t.remainingBudget} value={formatTzs(summary.remaining_to_budget)}/>}</section></div>;}
function Progress({label,value}:{label:string;value:number}){return <div className="mb-3 last:mb-0"><div className="flex justify-between text-xs font-semibold"><span>{label}</span><span>{value.toFixed(1)}%</span></div><div className="mt-1 h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-emerald-500" style={{width:`${value}%`}}/></div></div>;}function Small({label,value}:{label:string;value:string|number}){return <div><p className="text-xs text-slate-500">{label}</p><b className="text-sm">{value}</b></div>;}
function Filters({search,setSearch,status,setStatus,t,noCancelled=false}:{search:string;setSearch:(value:string)=>void;status:string;setStatus:(value:string)=>void;t:typeof copy.en|typeof copy.sw;noCancelled?:boolean}){return <div className="mt-3 grid gap-2 sm:grid-cols-2"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={t.search} className="min-h-11 rounded-xl border px-3"/><select value={status} onChange={event=>setStatus(event.target.value)} className="min-h-11 rounded-xl border px-3"><option value="all">{t.all}</option><option value="pledged">{t.pending}</option><option value="partial">{t.partial}</option><option value="completed">{t.completed}</option>{!noCancelled&&<option value="cancelled">Cancelled</option>}</select></div>;}
function Card({item,t,actions,delivery}:{item:FinancialPledge;t:typeof copy.en|typeof copy.sw;actions:React.ReactNode;delivery?:string}){const label=item.calculated_status==="completed"?t.completed:item.calculated_status==="partial"?t.partial:item.calculated_status==="pledged"?t.pending:"Cancelled";return <article className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-2"><div><b>{item.full_name}</b><p className="text-xs text-slate-500">{item.phone}</p></div><span className="text-xs font-bold">{label}</span></div><div className="mt-2 grid grid-cols-3 gap-2 text-xs"><Small label={t.pledged} value={formatTzs(item.pledged_amount)}/><Small label={t.collected} value={formatTzs(item.total_paid)}/><Small label={t.outstanding} value={formatTzs(item.balance)}/></div>{delivery&&<p className="mt-2 text-xs text-slate-500">{t.deliveryStatus}: {delivery==="not_sent"?t.notSent:delivery==="sent"?t.sent:delivery==="delivered"?t.delivered:delivery==="read"?t.read:t.failed}</p>}<div className="mt-3 flex flex-wrap gap-3 text-sm font-semibold">{actions}</div></article>;}
function Modal({children}:{children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-3"><div className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-5">{children}</div></div>;}
function MessageDialog({token,pledge,event,type,channel,t,onClose}:{token:string;pledge:FinancialPledge;event:PortalData["event"];type:"reminder"|"thank_you";channel:"sms"|"whatsapp";t:typeof copy.en|typeof copy.sw;onClose:()=>void}){const [preview,setPreview]=useState<{rows:Array<{message:string;eligible:boolean;skippedReason:string|null}>;provider:Record<"sms"|"whatsapp",{configured:boolean;message:string}>}|null>(null);const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const row=preview?.rows[0];const fallback=buildPledgeMessage(type==="thank_you"?"pledge_thank_you":"pledge_reminder",event.language,{guestName:pledge.full_name,eventTitle:event.title,pledgedAmount:pledge.pledged_amount,totalPaid:pledge.total_paid,balance:pledge.balance});async function load(){try{setBusy(true);setPreview(await request(token,{action:type==="thank_you"?"thank_you_preview":"reminder_preview",pledgeId:pledge.id,channel}));}catch(err){setError(err instanceof Error?err.message:"Preview failed.");}finally{setBusy(false);}}return <Modal><h2 className="sticky top-0 bg-white pb-3 text-xl font-bold">{type==="thank_you"?t.thankPreview:t.preview}</h2><pre className="whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm">{row?.message??fallback}</pre>{preview&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm">{row?.eligible?preview.provider[channel].message:`${t.failed}: ${row?.skippedReason}`}</p>}{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{t.confirm}</label><div className="sticky bottom-0 mt-4 flex justify-end gap-2 bg-white py-2"><button onClick={onClose} className="rounded-xl border px-4 py-2">{t.close}</button><button disabled={busy} onClick={()=>void load()} className="rounded-xl border px-4 py-2">{t.preview}</button><button disabled={busy||!confirmed||!row?.eligible||!preview?.provider[channel].configured} onClick={async()=>{try{setBusy(true);await request(token,{action:type==="thank_you"?"thank_you_send":"send_reminder",pledgeId:pledge.id,channel,confirmed:true});onClose();}catch(err){setError(err instanceof Error?err.message:t.failed);}finally{setBusy(false);}}} className="rounded-xl bg-emerald-600 px-4 py-2 font-semibold text-white disabled:opacity-40">{type==="thank_you"?t.thankSend:t.send}</button></div></Modal>;}
function Reports({summary,report,t}:{summary:FinanceSummary;report:Report|null;t:typeof copy.en|typeof copy.sw}){return <div className="space-y-3"><section className="rounded-xl bg-white p-3 shadow-sm"><h2 className="text-lg font-bold">{t.report}</h2><div className="mt-3 grid grid-cols-2 gap-2"><Small label={t.contributors} value={summary.total_contributors}/><Small label={t.pledged} value={formatTzs(summary.total_pledged)}/><Small label={t.collected} value={formatTzs(summary.total_collected)}/><Small label={t.outstanding} value={formatTzs(summary.remaining_balance)}/><Small label={t.percentage} value={`${summary.completion_percentage}%`}/><Small label={t.transactions} value={report?.validTransactions??t.loading}/></div></section>{report&&<><section className="rounded-xl bg-white p-3 shadow-sm"><h2 className="font-bold">{t.trend}</h2><div className="mt-2 h-56">{report.trend.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={report.trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tickFormatter={value=>`${Math.round(Number(value)/1000)}k`}/><Tooltip formatter={value=>formatTzs(String(value))}/><Area dataKey="amount" stroke="#059669" fill="#d1fae5"/></AreaChart></ResponsiveContainer>:<p className="py-16 text-center text-slate-500">{t.empty}</p>}</div></section><div className="grid gap-3 sm:grid-cols-2"><Rank title={t.top} rows={report.topContributors}/><Rank title={t.balances} rows={report.outstanding}/></div></>}</div>;}function Rank({title,rows}:{title:string;rows:Array<{name:string;amount:string}>}){return <section className="rounded-xl bg-white p-3 shadow-sm"><h2 className="font-bold">{title}</h2>{rows.map((row,index)=><div key={`${row.name}-${index}`} className="mt-2 flex justify-between rounded-lg bg-slate-50 p-2 text-sm"><span>{index+1}. {row.name}</span><b>{formatTzs(row.amount)}</b></div>)}</section>;}
