"use client";
import { useCallback, useEffect, useState } from "react";
import Button from "@/components/ui/Button";
import { previewReminders, sendReminders, type ReminderChannel, type ReminderPreview } from "@/services/financialAutomationService";
import type { FinancialPledge } from "@/services/financialSuiteService";
import { formatTzs } from "@/services/pledgeMessageService";

export default function FinancialReminderDialog({eventId,pledge,onClose,onSent}:{eventId:number;pledge:FinancialPledge;onClose:()=>void;onSent:()=>Promise<void>}){
  const [channel,setChannel]=useState<ReminderChannel>("sms");const [preview,setPreview]=useState<ReminderPreview|null>(null);const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(true);const [error,setError]=useState("");const [result,setResult]=useState("");
  const load=useCallback(async(next:ReminderChannel)=>{try{setBusy(true);setError("");setPreview(await previewReminders(eventId,[next],pledge.id));}catch(err){setError(err instanceof Error?err.message:"Preview failed.");}finally{setBusy(false);}},[eventId,pledge.id]);
  useEffect(()=>{const timer=setTimeout(()=>void load(channel),0);return()=>clearTimeout(timer);},[channel,load]);
  const row=preview?.rows[0];
  return <div className="space-y-4"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Send Reminder</h2><p className="text-sm text-slate-600">{pledge.full_name}</p></div><button onClick={onClose} aria-label="Close" className="text-2xl">×</button></div><label className="block text-sm font-semibold">Channel<select value={channel} onChange={(e)=>{setChannel(e.target.value as ReminderChannel);setConfirmed(false);}} className="mt-1 w-full rounded-xl border px-3 py-2"><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select></label><div className="grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 text-sm"><div>Phone<br/><b>{pledge.normalized_phone||"Missing"}</b></div><div>Pledged<br/><b>{formatTzs(pledge.pledged_amount)}</b></div><div>Paid<br/><b>{formatTzs(pledge.total_paid)}</b></div><div>Balance<br/><b>{formatTzs(pledge.balance)}</b></div><div>Last reminder<br/><b>{row?.lastReminderAt?new Date(row.lastReminderAt).toLocaleString():"Never"}</b></div><div>Cooldown until<br/><b>{row?.cooldownUntil?new Date(row.cooldownUntil).toLocaleString():"—"}</b></div></div><pre className="whitespace-pre-wrap rounded-xl border p-4 text-sm">{row?.message??"Loading preview…"}</pre>{preview&&<p className={`rounded-lg p-3 text-sm ${row?.eligible&&preview.provider[channel].configured?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-800"}`}>{!row?.eligible?`Skipped: ${row?.skippedReason}`:preview.provider[channel].message}</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{result&&<p role="status" className="text-sm text-emerald-700">{result}</p>}<label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={(e)=>setConfirmed(e.target.checked)}/>I confirm sending this reminder to this contributor.</label><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant="caution" loading={busy} disabled={busy||!confirmed||!row?.eligible||!preview?.provider[channel].configured} onClick={async()=>{try{setBusy(true);const sent=await sendReminders(eventId,[channel],pledge.id);setResult(sent.failed?`Provider failed: ${sent.errors[0]??"Unknown provider error"}`:"Reminder accepted by provider.");setConfirmed(false);await onSent();await load(channel);}catch(err){setError(err instanceof Error?err.message:"Send failed.");}finally{setBusy(false);}}}>Send reminder</Button></div></div>;
}
