import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { ClosingReport } from "@/services/financialAutomationService";
import { formatTzs } from "@/services/pledgeMessageService";
const s=StyleSheet.create({page:{padding:36,fontSize:9,fontFamily:"Helvetica",color:"#0f172a"},header:{backgroundColor:"#0f172a",color:"#fff",padding:20,borderRadius:8},brand:{color:"#34d399",fontSize:9,fontWeight:700},title:{fontSize:22,fontWeight:700,marginTop:4},section:{marginTop:18},heading:{fontSize:14,fontWeight:700,marginBottom:8},grid:{flexDirection:"row",flexWrap:"wrap",gap:7},card:{width:"31%",borderWidth:1,borderColor:"#e2e8f0",padding:8,borderRadius:5},label:{fontSize:7,color:"#64748b"},value:{fontSize:10,fontWeight:700,marginTop:3},row:{flexDirection:"row",borderBottomWidth:1,borderBottomColor:"#e2e8f0",paddingVertical:5},cell:{width:"25%"},footer:{position:"absolute",bottom:20,left:36,right:36,textAlign:"center",fontSize:7,color:"#64748b"}});
function Table({title,rows}:{title:string;rows:{name:string;paid:number;balance:number;status:string}[]}){return <View style={s.section} wrap><Text style={s.heading}>{title}</Text><View style={s.row}><Text style={s.cell}>Contributor</Text><Text style={s.cell}>Paid</Text><Text style={s.cell}>Balance</Text><Text style={s.cell}>Status</Text></View>{rows.slice(0,15).map((r,i)=><View key={`${r.name}-${i}`} style={s.row} wrap={false}><Text style={s.cell}>{r.name}</Text><Text style={s.cell}>{formatTzs(r.paid)}</Text><Text style={s.cell}>{formatTzs(r.balance)}</Text><Text style={s.cell}>{r.status}</Text></View>)}</View>}
export default function FinancialClosingPDF({report,generatedBy}:{report:ClosingReport;generatedBy:string}){
  const cards=[["Total Contributors",report.financial.totalContributors],["Event Budget",report.financial.target.budget===null?"Not set":formatTzs(report.financial.target.budget)],["Total Collected",formatTzs(report.financial.totalCollected)],["Remaining to Budget",report.financial.target.remaining===null?"—":formatTzs(report.financial.target.remaining)],["Budget Progress",report.financial.target.progress===null?"—":`${report.financial.target.progress.toFixed(1)}%`],["Contribution Deadline",report.financial.target.deadline??"No deadline"],["Deadline Status",report.financial.target.deadlineStatus],["Total Guests",report.guestStats.totalGuests],["Total Invitations",report.guestStats.totalInvitations],["Checked In",report.guestStats.checkedIn],["Total Pledged",formatTzs(report.financial.totalPledged)],["Outstanding",formatTzs(report.financial.outstanding)],["Pledge Collection",`${report.financial.percentage.toFixed(1)}%`],["Valid Transactions",report.financial.validTransactions],["Voided Transactions",report.financial.voidedTransactions]];
  const rows=report.pledges.map(p=>({name:p.full_name,paid:Number(p.total_paid),balance:Number(p.balance),status:p.calculated_status}));
  return <Document title={`${report.event.title} Financial Closing Report`}><Page size="A4" style={s.page}><View style={s.header}><Text style={s.brand}>SMART EVENT PASS</Text><Text style={s.title}>Financial Closing Report</Text><Text>{report.event.title} · {report.event.event_date} · {report.event.venue}</Text></View><View style={s.section}><Text style={s.heading}>Closing Summary</Text><View style={s.grid}>{cards.map(([label,value])=><View key={label} style={s.card}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>)}</View></View><Table title="Top Contributors" rows={[...rows].sort((a,b)=>b.paid-a.paid)}/><Table title="Largest Outstanding Balances" rows={[...rows].filter(r=>r.balance>0).sort((a,b)=>b.balance-a.balance)}/><View style={s.section}><Text style={s.heading}>Payment Methods</Text>{report.paymentMethods.map(m=><View key={m.method} style={s.row}><Text style={s.cell}>{m.method}</Text><Text style={s.cell}>{formatTzs(m.amount)}</Text></View>)}</View><Text style={s.footer}>Generated {new Date().toLocaleString()} by {generatedBy}. This report reflects guest, invitation and contribution records stored in Smart Event Pass at the time of generation.</Text></Page></Document>;
}
