"use client";
import { useAppLanguage } from "@/lib/i18n/useAppLanguage";
import { formatAppDate, formatAppNumber, formatAppTzs } from "@/lib/i18n/formatters";
import type { FinanceSummary } from "@/services/financialSuiteService";
export default function FinancialSummaryCards({ summary }: { summary: FinanceSummary }) {
  const { language, t } = useAppLanguage();
  const pct = (value: string | number) => formatAppNumber(Number(value) / 100, language, { style: "percent", maximumFractionDigits: 1 });
  const contributorCards = [[t("eligibility.total"), formatAppNumber(summary.total_contributors ?? summary.active_pledge_count, language), "text-blue-700"], [t("overview.completed"), formatAppNumber(summary.completed_count, language), "text-emerald-700"], [t("overview.partial"), formatAppNumber(summary.partial_count, language), "text-amber-700"], [t("overview.notStarted"), formatAppNumber(summary.pledged_count, language), "text-slate-700"]];
  const financeCards = [[t("overview.totalPledged"), formatAppTzs(Number(summary.total_pledged), language), "text-slate-900"], [t("overview.totalCollected"), formatAppTzs(Number(summary.total_collected), language), "text-emerald-700"], [t("overview.balance"), formatAppTzs(Number(summary.remaining_balance), language), "text-amber-700"], [t("overview.contributionProgress"), pct(summary.completion_percentage), "text-blue-700"], [t("overview.eventBudget"), summary.budget_amount ? formatAppTzs(Number(summary.budget_amount), language) : t("overview.budgetNotSet"), "text-slate-900"], [t("overview.remainingBudget"), summary.remaining_to_budget == null ? "—" : formatAppTzs(Number(summary.remaining_to_budget), language), "text-amber-700"], [t("overview.budgetProgress"), summary.budget_progress_percentage == null ? "—" : pct(summary.budget_progress_percentage), "text-blue-700"], [t("overview.deadline"), summary.contribution_deadline ? formatAppDate(`${summary.contribution_deadline}T00:00:00`, language, { day:"numeric", month:"short", year:"numeric" }) : t("overview.noDeadline"), "text-slate-900"], [t("overview.daysRemaining"), summary.days_remaining == null ? "—" : formatAppNumber(summary.days_remaining, language), "text-slate-700"]];
  const render=(cards:string[][])=>cards.map(([label,value,color])=><article key={label} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-sm font-medium text-slate-500">{label}</p><p className={`mt-2 break-words text-2xl font-bold ${color}`}>{value}</p></article>);
  return <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{render(contributorCards)}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{render(financeCards)}</div><div><div className="mb-1 flex justify-between text-xs font-semibold text-slate-600"><span>{t("overview.contributionProgress")}</span><span>{pct(summary.completion_percentage)}</span></div><div className="rounded-full bg-slate-200" aria-label={`${pct(summary.completion_percentage)} ${t("overview.contributionProgress")}`}><div className="h-3 rounded-full bg-emerald-500 transition-all" style={{width:`${Math.min(100,Number(summary.completion_percentage))}%`}}/></div></div><div><div className="mb-1 flex flex-wrap justify-between gap-2 text-xs font-semibold text-slate-600"><span>{t("overview.budgetProgress")} · {t("overview.collected")}: {formatAppTzs(Number(summary.total_collected), language)} · {t("overview.eventBudget")}: {summary.budget_amount?formatAppTzs(Number(summary.budget_amount),language):t("common.notSet")}</span><span>{summary.budget_progress_percentage == null ? "—" : pct(summary.budget_progress_percentage)}</span></div><div className="rounded-full bg-slate-200" aria-label={t("overview.budgetProgress")}><div className="h-3 rounded-full bg-blue-500 transition-all" style={{width:`${Math.min(100,Number(summary.budget_progress_percentage??0))}%`}}/></div></div></div>;
}
