"use client";
import { useMemo, useState } from "react";
import FinancialSummaryCards from "./FinancialSummaryCards";
import RecordPaymentDialog from "./RecordPaymentDialog";
import PaymentHistoryDialog from "./PaymentHistoryDialog";
import ReceiptDialog from "./ReceiptDialog";
import type { FinanceReceipt } from "@/services/receiptMessageService";
import { buildPledgeMessage, formatTzs } from "@/services/pledgeMessageService";
import type { FinanceSummary, FinancialPledge, PledgeInput, PledgePayment } from "@/services/financialSuiteService";

export type PortalData = {
  access_status: "active"; event: { id: number; title: string; event_date: string; language: "sw" | "en" };
  permissions: Record<string, boolean>; summary: FinanceSummary; finance_target: Partial<FinanceSummary> | null; pledges: FinancialPledge[];
};
const labels = { pledged: "Ameahidi", partial: "Amepunguza", completed: "Amekamilisha", cancelled: "Imefutwa" };
async function request(token: string, body: Record<string, unknown>) {
  const response = await fetch("/api/contributions/organiser", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, ...body }), cache: "no-store" });
  const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Request failed."); return payload;
}

export default function OrganiserPortal({ token, initialData }: { token: string; initialData: PortalData }) {
  const [data, setData] = useState(initialData); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all");
  const [selected, setSelected] = useState<FinancialPledge | null>(null); const [dialog, setDialog] = useState<"create"|"edit"|"payment"|"history"|"reminder"|null>(null);
  const [history, setHistory] = useState<PledgePayment[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [newReceipt,setNewReceipt]=useState<{receipt:FinanceReceipt;verificationUrl:string}|null>(null);
  const visible = useMemo(() => data.pledges.filter((p) => (status === "all" || p.calculated_status === status) && `${p.full_name} ${p.phone}`.toLowerCase().includes(query.toLowerCase())), [data, query, status]);
  async function refresh(message?: string) {
    const next = await request(token, { action: "refresh" }); if (next.access_status !== "active") throw new Error("This access link is no longer active.");
    setData(next); if (message) setNotice(message);
  }
  async function saveDetails(values: PledgeInput) {
    await request(token, { action: dialog === "edit" ? "edit_pledge" : "create_pledge", pledgeId: selected?.id, fullName: values.fullName, phone: values.phone, email: values.email, pledgedAmount: values.pledgedAmount, notes: values.notes });
    setDialog(null); await refresh(dialog === "edit" ? "Contributor updated." : "Pledge created.");
  }
  async function historyFor(pledge: FinancialPledge) {
    try { setSelected(pledge); const result = await request(token, { action: "payment_history", pledgeId: pledge.id }); setHistory(result.payments ?? []); setDialog("history"); }
    catch (err) { setError(err instanceof Error ? err.message : "History could not be loaded."); }
  }
  return <main className="min-h-screen bg-slate-100">
    <header className="bg-slate-950 px-4 py-6 text-white"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Smart Event Pass · Committee Portal</p><h1 className="mt-2 text-2xl font-bold">{data.event.title}</h1><p className="text-sm text-slate-300">{data.event.event_date}</p></div></header>
    <div className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6">
      {notice && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      <FinancialSummaryCards summary={{ ...data.summary, ...data.finance_target, budget_amount:data.finance_target?.budget_amount??null, contribution_deadline:data.finance_target?.contribution_deadline??null, budget_progress_percentage:data.finance_target?.budget_progress_percentage??null, remaining_to_budget:data.finance_target?.remaining_to_budget??null, days_remaining:data.finance_target?.days_remaining??null, deadline_status:data.finance_target?.deadline_status??"No deadline", active_pledge_count: data.pledges.filter((p) => p.calculated_status !== "cancelled").length, total_contributors:data.pledges.filter((p)=>p.calculated_status!=="cancelled").length, pledged_count: data.pledges.filter((p) => p.calculated_status === "pledged").length, partial_count: data.pledges.filter((p) => p.calculated_status === "partial").length, completed_count: data.pledges.filter((p) => p.calculated_status === "completed").length, cancelled_count: data.pledges.filter((p) => p.calculated_status === "cancelled").length }} />
      <section className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row">{data.permissions.search && <><input aria-label="Search contributors" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name or phone" className="flex-1 rounded-xl border px-3 py-2" /><select aria-label="Status filter" value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border px-3 py-2"><option value="all">All statuses</option>{Object.entries(labels).map(([key,value]) => <option key={key} value={key}>{value}</option>)}</select></>}{data.permissions.create_pledges && <button onClick={() => { setSelected(null); setDialog("create"); }} className="rounded-xl bg-emerald-600 px-4 py-2 font-semibold text-white">+ New pledge</button>}</div>
        <div className="grid gap-3 p-3">{visible.length === 0 && <p className="p-8 text-center text-slate-500">No pledges found.</p>}{visible.map((p) => <article key={p.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{p.full_name}</h2><p className="text-sm text-slate-500">{p.phone}</p></div><span className="h-fit rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{labels[p.calculated_status]}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><div>Pledged<br/><b>{formatTzs(p.pledged_amount)}</b></div><div>Paid<br/><b className="text-emerald-700">{formatTzs(p.total_paid)}</b></div><div>Balance<br/><b>{formatTzs(p.balance)}</b></div></div><div className="mt-4 flex flex-wrap gap-4 text-sm font-semibold">{data.permissions.record_payments && p.calculated_status !== "completed" && p.calculated_status !== "cancelled" && <button onClick={() => { setSelected(p); setDialog("payment"); }} className="text-emerald-700">Record payment</button>}{data.permissions.edit_contributors && <button onClick={() => { setSelected(p); setDialog("edit"); }} className="text-blue-700">Edit details</button>}{data.permissions.view_payment_history && <button onClick={() => void historyFor(p)} className="text-slate-700">Payment history</button>}{data.permissions.send_reminders && <button onClick={() => { setSelected(p); setDialog("reminder"); }} className="text-amber-700">Reminder preview</button>}</div></article>)}</div>
      </section>
    </div>
    <footer className="p-6 text-center text-sm text-slate-500">Managed securely by Smart Event Pass</footer>
    {dialog && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6"><h2 className="mb-4 text-xl font-bold">{dialog === "create" ? "Create pledge" : dialog === "edit" ? "Edit contributor" : dialog === "payment" ? "Record payment" : dialog === "history" ? "Payment history" : "Reminder preview"}</h2>
      {(dialog === "create" || dialog === "edit") && <PortalDetailsForm pledge={selected} onSave={saveDetails} onClose={() => setDialog(null)} />}
      {dialog === "payment" && selected && <RecordPaymentDialog pledge={selected} onClose={() => setDialog(null)} onSave={async (values) => { const result = await request(token, { action: "record_payment", pledgeId: selected.id, ...values });const issued=await request(token,{action:"issue_receipt",pledgeId:selected.id,receiptNumber:result.receipt_number}); setDialog(null);setNewReceipt(issued); await refresh(`Payment recorded. Receipt ${result.receipt_number}.`); }} />}
      {dialog === "history" && <PaymentHistoryDialog payments={history} language={data.event.language} issueReceipt={async(receiptNumber)=>request(token,{action:"issue_receipt",pledgeId:selected?.id,receiptNumber})} onClose={()=>setDialog(null)}/>}
      {dialog === "reminder" && selected && <ReminderPreview token={token} pledge={selected} event={data.event} onClose={() => setDialog(null)} />}
    </div></div>}
    {newReceipt&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6"><ReceiptDialog {...newReceipt} language={data.event.language} onClose={()=>setNewReceipt(null)}/></div></div>}
  </main>;
}

function PortalDetailsForm({ pledge, onSave, onClose }: { pledge: FinancialPledge | null; onSave: (values: PledgeInput) => Promise<void>; onClose: () => void }) {
  const [form,setForm]=useState({ fullName:pledge?.full_name??"",phone:pledge?.phone??"",email:pledge?.email??"",amount:pledge?.pledged_amount??"",notes:pledge?.notes??"" }); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  return <form className="space-y-3" onSubmit={async(e)=>{e.preventDefault();try{setBusy(true);await onSave({eventId:pledge?.event_id??0,fullName:form.fullName,phone:form.phone,email:form.email,pledgedAmount:form.amount,notes:form.notes});}catch(err){setError(err instanceof Error?err.message:"Could not save.");}finally{setBusy(false);}}}><label className="block text-sm font-semibold">Full name<input required value={form.fullName} onChange={(e)=>setForm({...form,fullName:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="block text-sm font-semibold">Phone<input required value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="block text-sm font-semibold">Email<input type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>{!pledge&&<label className="block text-sm font-semibold">Pledged amount<input required inputMode="decimal" value={form.amount} onChange={(e)=>setForm({...form,amount:e.target.value.replace(/,/g,"")})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>}<label className="block text-sm font-semibold">Notes<textarea value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>{error&&<p className="text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2">Cancel</button><button disabled={busy} className="rounded-xl bg-emerald-600 px-4 py-2 font-semibold text-white">{busy?"Saving...":"Save"}</button></div></form>;
}
function ReminderPreview({ token,pledge,event,onClose }:{token:string;pledge:FinancialPledge;event:PortalData["event"];onClose:()=>void}) {
  const [channel,setChannel]=useState<"sms"|"whatsapp">("sms");const [preview,setPreview]=useState<{rows:Array<{message:string;eligible:boolean;skippedReason:string|null;lastReminderAt:string|null;cooldownUntil:string|null}>;provider:Record<"sms"|"whatsapp",{configured:boolean;message:string}>}|null>(null);
  const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [result,setResult]=useState("");
  async function load(){try{setBusy(true);setError("");setPreview(await request(token,{action:"reminder_preview",pledgeId:pledge.id,channel}));}catch(err){setError(err instanceof Error?err.message:"Preview failed.");}finally{setBusy(false);}}
  const row=preview?.rows[0];const fallback=buildPledgeMessage("pledge_reminder",event.language,{guestName:pledge.full_name,eventTitle:event.title,pledgedAmount:pledge.pledged_amount,totalPaid:pledge.total_paid,balance:pledge.balance});
  return <div className="space-y-3"><label className="block text-sm font-semibold">Channel<select value={channel} onChange={(e)=>{setChannel(e.target.value as "sms"|"whatsapp");setPreview(null);setConfirmed(false);}} className="mt-1 w-full rounded-xl border px-3 py-2"><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select></label><div className="grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 text-sm"><div>Phone<br/><b>{pledge.normalized_phone||"Missing"}</b></div><div>Balance<br/><b>{formatTzs(pledge.balance)}</b></div><div>Last reminder<br/><b>{row?.lastReminderAt?new Date(row.lastReminderAt).toLocaleString():"Never"}</b></div><div>Cooldown<br/><b>{row?.cooldownUntil??"—"}</b></div></div><pre className="whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm">{row?.message??fallback}</pre>{preview&&<p className={`rounded-lg p-3 text-sm ${row?.eligible?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-800"}`}>{row?.eligible?preview.provider[channel].message:`Not eligible: ${row?.skippedReason}`}</p>}{error&&<p className="text-sm text-red-700">{error}</p>}{result&&<p className="text-sm text-emerald-700">{result}</p>}<label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={(e)=>setConfirmed(e.target.checked)}/>I confirm sending this reminder.</label><div className="flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border px-4 py-2">Close</button><button disabled={busy} onClick={()=>void load()} className="rounded-xl border px-4 py-2">{busy?"Loading…":"Preview"}</button><button disabled={busy||!confirmed||!row?.eligible||!preview?.provider[channel].configured} onClick={async()=>{try{setBusy(true);const sent=await request(token,{action:"send_reminder",pledgeId:pledge.id,channel,confirmed:true});setResult(sent.failed?`Failed: ${sent.errors?.[0]??"Provider rejected the reminder."}`:"Reminder accepted by provider.");setConfirmed(false);await load();}catch(err){setError(err instanceof Error?err.message:"Send failed.");}finally{setBusy(false);}}} className="rounded-xl bg-amber-600 px-4 py-2 font-semibold text-white disabled:opacity-40">Send reminder</button></div></div>;
}
