"use client";
import { useState } from "react";
import { pdf } from "@react-pdf/renderer";
import QRCode from "qrcode";
import ReceiptPDF from "./ReceiptPDF";
import { buildReceiptMessage, type FinanceReceipt } from "@/services/receiptMessageService";
import { formatTzs } from "@/services/pledgeMessageService";

export default function ReceiptDialog({ receipt, verificationUrl, language="sw", onClose }: { receipt: FinanceReceipt; verificationUrl: string; language?:"sw"|"en"; onClose:()=>void }) {
  const [preview,setPreview]=useState(false); const [busy,setBusy]=useState(false);
  async function download() { try { setBusy(true); const qr=await QRCode.toDataURL(verificationUrl,{margin:1,width:300}); const blob=await pdf(<ReceiptPDF receipt={receipt} verificationUrl={verificationUrl} qrDataUrl={qr}/>).toBlob(); const url=URL.createObjectURL(blob); const a=document.createElement("a");a.href=url;a.download=`${receipt.receipt_number}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}finally{setBusy(false);} }
  const rows=[["Event",receipt.event_name],["Contributor",receipt.contributor_name],["Phone",receipt.contributor_phone],["Pledged",formatTzs(receipt.pledged_amount)],["This payment",formatTzs(receipt.payment_amount)],["Total paid",formatTzs(receipt.total_paid)],["Balance",formatTzs(receipt.remaining_balance)],["Date",receipt.payment_date],["Method",receipt.payment_method.replaceAll("_"," ")],["Reference",receipt.payment_reference||"—"],["Recorded by",receipt.recorded_by],["Status",receipt.payment_status]];
  return <div className="space-y-4"><div id="printable-receipt" className="overflow-hidden rounded-xl border"><header className="bg-slate-950 p-5 text-white"><p className="text-xs font-bold tracking-widest text-emerald-400">SMART EVENT PASS</p><h2 className="mt-1 text-2xl font-bold">Contribution Receipt</h2><p>{receipt.receipt_number}</p></header>{receipt.payment_status==="voided"&&<div className="border-y-4 border-red-700 bg-red-50 p-4 text-center text-3xl font-black tracking-[.3em] text-red-700">VOIDED</div>}<dl className="divide-y p-5">{rows.map(([label,value])=><div key={label} className="flex justify-between gap-4 py-2 text-sm"><dt className="text-slate-500">{label}</dt><dd className="text-right font-semibold capitalize">{value}</dd></div>)}</dl></div><div className="flex flex-wrap gap-2"><button onClick={()=>window.print()} className="rounded-xl border px-3 py-2 text-sm font-semibold">Print Receipt</button><button onClick={()=>void download()} disabled={busy} className="rounded-xl bg-slate-900 px-3 py-2 text-sm font-semibold text-white">{busy?"Preparing...":"Download PDF"}</button><button onClick={()=>void navigator.clipboard.writeText(verificationUrl)} className="rounded-xl border px-3 py-2 text-sm font-semibold">Copy Verification Link</button><button onClick={()=>setPreview(!preview)} className="rounded-xl border px-3 py-2 text-sm font-semibold">Message Preview</button></div>{preview&&<div><pre className="whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm">{buildReceiptMessage(receipt,verificationUrl,language)}</pre><p className="mt-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Sending requires explicit confirmation and an approved provider template. No message has been sent.</p></div>}<button onClick={onClose} className="w-full rounded-xl border px-4 py-2">Close</button></div>;
}
