"use client";
import { useState } from "react";
import { useAppLanguage } from "@/lib/i18n/useAppLanguage";
import { formatAppTzs } from "@/lib/i18n/formatters";
import type { FinancialPledge } from "@/services/financialSuiteService";
export default function RecordPaymentDialog({ pledge, onSave, onClose }: { pledge: FinancialPledge; onSave: (values: { amount: string; date: string; method: string; reference: string; provider: string; notes: string }) => Promise<void>; onClose: () => void }) {
  const { language, t } = useAppLanguage();
  const [form, setForm] = useState({ amount: "", date: new Date().toISOString().slice(0, 10), method: "cash", reference: "", provider: "", notes: "" });
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const expected = form.amount && /^\d+$/.test(form.amount) ? BigInt(String(pledge.balance).split(".")[0]) - BigInt(form.amount) : null;
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!/^\d+(\.\d{1,2})?$/.test(form.amount) || Number(form.amount) <= 0 || expected === null || expected < BigInt(0)) { setError(t("payments.recordError")); return; } try { setSaving(true); await onSave(form); } catch (cause) { setError(cause instanceof Error ? cause.message : t("payments.recordError")); } finally { setSaving(false); } }
  const money = (value: string) => formatAppTzs(Number(value), language); const field = "mt-1 w-full rounded-xl border px-3 py-2";
  const methods = [["cash",t("payments.cash")],["mobile_money",t("payments.mobile")],["bank",t("payments.bank")],["cheque",t("payments.cheque")],["other",t("payments.other")]];
  return <form onSubmit={submit} className="space-y-4"><div className="grid grid-cols-3 gap-2 rounded-xl bg-slate-50 p-3 text-sm"><div>{t("settings.pledged")}<br/><b>{money(pledge.pledged_amount)}</b></div><div>{t("overview.collected")}<br/><b>{money(pledge.total_paid)}</b></div><div>{t("overview.balance")}<br/><b>{money(pledge.balance)}</b></div></div><label className="block text-sm font-semibold">{t("payments.amount")} (TZS)<input required inputMode="decimal" value={form.amount} onChange={(event) => setForm({...form,amount:event.target.value.replace(/,/g,"")})} className={field}/></label>{expected !== null && <p className="text-sm">{t("overview.balance")}: <b>{formatAppTzs(Number(expected),language)}</b></p>}<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">{t("payments.date")}<input type="date" required value={form.date} onChange={(event)=>setForm({...form,date:event.target.value})} className={field}/></label><label className="text-sm font-semibold">{t("payments.method")}<select value={form.method} onChange={(event)=>setForm({...form,method:event.target.value})} className={field}>{methods.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><label className="block text-sm font-semibold">{t("payments.reference")}<input value={form.reference} onChange={(event)=>setForm({...form,reference:event.target.value})} className={field}/></label>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex flex-wrap justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2">{t("common.cancel")}</button><button disabled={saving} className="rounded-xl bg-emerald-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{saving?t("common.saving"):t("payments.record")}</button></div></form>;
}
