-- Service Inquiries: public "Book Our Services" landing-page form submissions
-- (app/page.tsx -> components/marketing/BookServiceForm.tsx). Inserted via the
-- service-role client from app/api/public/service-inquiries/route.ts since the
-- visitor is unauthenticated -- mirrors the notifyAdminsBySms pattern already
-- used for support tickets. Admins are notified via SMS (Beem); WhatsApp/email
-- are out of scope for the same reasons noted in support_tickets.sql.
--
-- Forward-only. Deliberately not applied automatically.

create table public.service_inquiries (
  id bigint generated by default as identity primary key,
  full_name text not null check (length(btrim(full_name)) > 0 and length(full_name) <= 200),
  phone text not null check (length(btrim(phone)) > 0 and length(phone) <= 32),
  event_type text not null check (event_type in ('wedding', 'sendoff', 'birthday', 'kitchen_party', 'corporate')),
  event_date date,
  status text not null default 'new' check (status in ('new', 'contacted', 'closed')),
  created_at timestamptz not null default now()
);

create index service_inquiries_created_at_idx on public.service_inquiries(created_at desc);

alter table public.service_inquiries enable row level security;

create policy service_inquiries_admin_select on public.service_inquiries
for select to authenticated
using (public.is_active_admin());

create policy service_inquiries_admin_update on public.service_inquiries
for update to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

revoke all on public.service_inquiries from anon, authenticated, service_role;
grant select on public.service_inquiries to authenticated;
grant update(status) on public.service_inquiries to authenticated;
grant select, insert on public.service_inquiries to service_role;
