-- Custom SMS Outreach Campaigns V1. Bulk, admin-authored SMS blasts to a
-- guest list (not the pledge/contributor domain) -- e.g. a one-off payment
-- solicitation campaign with a fully custom message body. Mirrors the
-- event_meetings / meeting_invitation_deliveries shape (claim-before-send,
-- unique idempotency_key) but keyed to public.guests instead of
-- public.event_pledges, since recipients here are plain event guests.
--
-- Deliberately not applied automatically.

create table public.sms_campaigns (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete restrict,
  name text not null check (length(btrim(name)) > 0),
  message_template text not null check (length(btrim(message_template)) > 0),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.sms_campaign_deliveries (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.sms_campaigns(id) on delete restrict,
  event_id bigint not null references public.events(id) on delete restrict,
  guest_id bigint not null references public.guests(id) on delete restrict,
  recipient_phone text not null,
  message_body text not null,
  delivery_status text not null default 'processing' check (delivery_status in ('processing','sent','failed')),
  provider_message_id text,
  error_message text,
  idempotency_key text not null unique,
  sent_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index sms_campaigns_event_idx on public.sms_campaigns(event_id, created_at desc);
create index sms_campaign_deliveries_campaign_idx on public.sms_campaign_deliveries(campaign_id, created_at desc);
create index sms_campaign_deliveries_event_idx on public.sms_campaign_deliveries(event_id, created_at desc);
create index sms_campaign_deliveries_guest_idx on public.sms_campaign_deliveries(guest_id);

create trigger sms_campaigns_updated_at before update on public.sms_campaigns
for each row execute function public.set_finance_updated_at();
create trigger sms_campaign_deliveries_updated_at before update on public.sms_campaign_deliveries
for each row execute function public.set_finance_updated_at();

alter table public.sms_campaigns enable row level security;
alter table public.sms_campaign_deliveries enable row level security;

-- Admin-only in both directions: all writes go through the service-role
-- API route (app/api/sms/custom-campaign), which authenticates the caller
-- and checks profiles.role = 'admin' itself before touching these tables.
-- Authenticated grants below only cover read access, for a future direct
-- dashboard read if ever needed (matches the meeting_invitation_deliveries
-- precedent of read-only authenticated access to delivery history).
create policy sms_campaigns_admin_read on public.sms_campaigns for select to authenticated
using (public.is_active_admin());
create policy sms_campaign_deliveries_admin_read on public.sms_campaign_deliveries for select to authenticated
using (public.is_active_admin());

revoke all on public.sms_campaigns from anon,authenticated,service_role;
revoke all on public.sms_campaign_deliveries from anon,authenticated,service_role;
revoke all on sequence public.sms_campaigns_id_seq from anon,authenticated,service_role;
revoke all on sequence public.sms_campaign_deliveries_id_seq from anon,authenticated,service_role;

grant select on public.sms_campaigns to authenticated;
grant select on public.sms_campaign_deliveries to authenticated;
grant select,insert,update on public.sms_campaigns,public.sms_campaign_deliveries to service_role;
grant usage,select on sequence public.sms_campaigns_id_seq,public.sms_campaign_deliveries_id_seq to service_role;
