-- Support Tickets: any authenticated user can open a ticket for the admin
-- team; only an active admin can reply as "admin" or change ticket status.
-- Mirrors the owner-or-admin RLS shape already used by the Financial Suite
-- (is_active_admin / can_manage_event_finance / event_finance_targets).
--
-- Admin is notified via SMS (Beem) when a ticket is created -- see
-- app/api/support-tickets/route.ts. WhatsApp (requires a new Meta-approved
-- template) and email (no provider integrated yet) are deliberately out of
-- scope for this pass.
--
-- Forward-only. Deliberately not applied automatically.

create table public.support_tickets (
  id bigint generated by default as identity primary key,
  organizer_id uuid not null references auth.users(id) on delete cascade,
  subject text not null check (length(btrim(subject)) > 0 and length(subject) <= 200),
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index support_tickets_organizer_id_idx on public.support_tickets(organizer_id);
create index support_tickets_updated_at_idx on public.support_tickets(updated_at desc);

create trigger support_tickets_updated_at
before update on public.support_tickets
for each row execute function public.set_finance_updated_at();

create table public.support_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_type text not null check (sender_type in ('organizer', 'admin')),
  body text not null check (length(btrim(body)) > 0),
  created_at timestamptz not null default now()
);

create index support_ticket_messages_ticket_id_idx on public.support_ticket_messages(ticket_id, created_at);

-- Owner-or-admin authorization, same pattern as can_manage_event_finance.
create or replace function public.can_manage_support_ticket(target_ticket_id bigint)
returns boolean language sql stable security definer
set search_path = public, auth, pg_catalog
as $$
  select exists (
    select 1 from public.support_tickets t
    where t.id = target_ticket_id
      and (t.organizer_id = auth.uid() or public.is_active_admin())
  );
$$;
revoke all on function public.can_manage_support_ticket(bigint) from public;
grant execute on function public.can_manage_support_ticket(bigint) to authenticated;

-- Keeps the ticket list sortable by most recently active thread.
create or replace function public.touch_support_ticket_on_message()
returns trigger language plpgsql security definer
set search_path = public, auth, pg_catalog
as $$
begin
  update public.support_tickets set updated_at = now() where id = new.ticket_id;
  return new;
end;
$$;

create trigger touch_support_ticket_on_message
after insert on public.support_ticket_messages
for each row execute function public.touch_support_ticket_on_message();

alter table public.support_tickets enable row level security;

create policy support_tickets_select on public.support_tickets
for select to authenticated
using (organizer_id = auth.uid() or public.is_active_admin());

create policy support_tickets_insert on public.support_tickets
for insert to authenticated
with check (organizer_id = auth.uid());

create policy support_tickets_admin_update on public.support_tickets
for update to authenticated
using (public.is_active_admin())
with check (public.is_active_admin());

revoke all on public.support_tickets from anon, authenticated, service_role;
grant select on public.support_tickets to authenticated;
grant insert(organizer_id, subject) on public.support_tickets to authenticated;
grant update(status, updated_at) on public.support_tickets to authenticated;
grant select on public.support_tickets to service_role;

alter table public.support_ticket_messages enable row level security;

create policy support_ticket_messages_select on public.support_ticket_messages
for select to authenticated
using (public.can_manage_support_ticket(ticket_id));

create policy support_ticket_messages_insert on public.support_ticket_messages
for insert to authenticated
with check (
  sender_id = auth.uid()
  and sender_type = (
    select case when t.organizer_id = auth.uid() then 'organizer' else 'admin' end
    from public.support_tickets t
    where t.id = ticket_id
  )
  and public.can_manage_support_ticket(ticket_id)
);

revoke all on public.support_ticket_messages from anon, authenticated, service_role;
grant select on public.support_ticket_messages to authenticated;
grant insert(ticket_id, sender_id, sender_type, body) on public.support_ticket_messages to authenticated;
grant select on public.support_ticket_messages to service_role;
