-- Event archiving and narrowly scoped destructive Financial Suite operations.
-- Deliberately not applied automatically.

alter table public.events
  add column if not exists archived_at timestamptz;

create index if not exists events_active_event_date_idx
  on public.events(event_date)
  where archived_at is null;

drop policy if exists "Admin can delete all and organizer can delete own events" on public.events;
revoke delete on public.events from authenticated;

alter table public.finance_audit_logs
  drop constraint if exists finance_audit_logs_action_check;
alter table public.finance_audit_logs
  add constraint finance_audit_logs_action_check check (action in (
    'pledge_created','pledge_updated','pledge_cancelled','payment_recorded','payment_voided',
    'reminder_requested','reminder_sent','reminder_failed','organiser_link_created',
    'organiser_link_revoked','pledge_import_completed','bulk_contributions_cleanup'
  ));

create or replace function public.is_active_admin()
returns boolean language sql stable security definer
set search_path = public, auth, pg_catalog
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_active and role = 'admin'
  );
$$;
revoke all on function public.is_active_admin() from public;
grant execute on function public.is_active_admin() to authenticated;

create table if not exists public.destructive_action_audit (
  id bigint generated by default as identity primary key,
  action text not null check (length(btrim(action)) > 0),
  event_id bigint,
  event_title text not null,
  actor_user_id uuid,
  summary jsonb not null default '{}'::jsonb check (jsonb_typeof(summary) = 'object'),
  created_at timestamptz not null default now()
);
create index if not exists destructive_action_audit_created_at_idx
  on public.destructive_action_audit(created_at desc);
create index if not exists destructive_action_audit_event_id_idx
  on public.destructive_action_audit(event_id)
  where event_id is not null;
alter table public.destructive_action_audit enable row level security;
drop policy if exists destructive_action_audit_admin_select on public.destructive_action_audit;
create policy destructive_action_audit_admin_select
on public.destructive_action_audit for select to authenticated
using (public.is_active_admin());
revoke all on public.destructive_action_audit from public, anon, authenticated, service_role;
revoke all on sequence public.destructive_action_audit_id_seq from public, anon, authenticated, service_role;
grant select on public.destructive_action_audit to authenticated;

create or replace function public.guard_event_archive_transition()
returns trigger language plpgsql security definer
set search_path = public, auth, pg_catalog
as $$
begin
  if new.archived_at is distinct from old.archived_at then
    if public.is_active_admin() then return new; end if;
    if old.archived_at is null and new.archived_at is not null
      and public.can_manage_event_finance(old.id) then return new; end if;
    raise exception 'Not authorized';
  end if;
  return new;
end;
$$;
drop trigger if exists guard_event_archive_transition on public.events;
create trigger guard_event_archive_transition
before update of archived_at on public.events
for each row execute function public.guard_event_archive_transition();

create or replace function public.set_event_archived(
  target_event_id bigint,
  should_archive boolean
) returns jsonb language plpgsql security definer
set search_path = public, auth, pg_catalog
as $$
declare target public.events%rowtype;
begin
  select * into target from public.events where id = target_event_id for update;
  if not found then raise exception 'Event not found'; end if;
  if should_archive then
    if not public.can_manage_event_finance(target_event_id) then raise exception 'Not authorized'; end if;
    update public.events set archived_at = coalesce(archived_at, clock_timestamp())
    where id = target_event_id;
  else
    if not public.is_active_admin() then raise exception 'Not authorized'; end if;
    update public.events set archived_at = null where id = target_event_id;
  end if;
  return jsonb_build_object(
    'eventId', target_event_id,
    'archived', should_archive
  );
end;
$$;
revoke all on function public.set_event_archived(bigint,boolean) from public;
grant execute on function public.set_event_archived(bigint,boolean) to authenticated;

create or replace function public.preview_event_permanent_deletion(target_event_id bigint)
returns jsonb language plpgsql security definer
set search_path = public, auth, pg_catalog
as $$
declare target public.events%rowtype;
begin
  if not public.is_active_admin() then raise exception 'Not authorized'; end if;
  select * into target from public.events where id = target_event_id;
  if not found then raise exception 'Event not found'; end if;
  return jsonb_build_object(
    'eventId', target.id,
    'eventTitle', coalesce(target.title, ''),
    'guests', (select count(*) from public.guests where event_id=target.id),
    'invitations', (select count(*) from public.invitations where event_id=target.id),
    'pledges', (select count(*) from public.event_pledges where event_id=target.id),
    'validPayments', (select count(*) from public.pledge_payments pay join public.event_pledges p on p.id=pay.pledge_id where p.event_id=target.id and pay.voided_at is null),
    'voidedPayments', (select count(*) from public.pledge_payments pay join public.event_pledges p on p.id=pay.pledge_id where p.event_id=target.id and pay.voided_at is not null),
    'receipts', (select count(*) from public.finance_receipt_verifications verification join public.pledge_payments pay on pay.id=verification.payment_id join public.event_pledges p on p.id=pay.pledge_id where p.event_id=target.id),
    'committeeLinks', (select count(*) from public.event_finance_access_links where event_id=target.id),
    'reminderHistory', (select count(*) from public.pledge_reminders where event_id=target.id),
    'automationDeliveries', (select count(*) from public.finance_automation_delivery_logs where event_id=target.id),
    'wishes', (select count(*) from public.event_wishes where event_id=target.id),
    'guestImportHistory', (select count(*) from public.guest_import_history where event_id=target.id),
    'financeTargets', (select count(*) from public.event_finance_targets where event_id=target.id),
    'whatsappMessageLogs', (select count(*) from public.whatsapp_message_logs log
      join public.invitations invitation on invitation.id=log.invitation_id
      where invitation.event_id=target.id),
    'financeAuditLogs', (select count(*) from public.finance_audit_logs where event_id=target.id),
    'financeAutomationSettings', (select count(*) from public.event_finance_automation_settings where event_id=target.id)
  );
end;
$$;
revoke all on function public.preview_event_permanent_deletion(bigint) from public;
grant execute on function public.preview_event_permanent_deletion(bigint) to authenticated;

create or replace function public.delete_event_permanently(
  target_event_id bigint,
  expected_event_title text,
  second_confirmation boolean
) returns jsonb language plpgsql security definer
set search_path = public, auth, pg_catalog
as $$
declare target public.events%rowtype; summary jsonb;
begin
  if not public.is_active_admin() then raise exception 'Not authorized'; end if;
  if second_confirmation is not true then raise exception 'Confirmation required'; end if;
  select * into target from public.events where id=target_event_id for update;
  if not found then raise exception 'Event not found'; end if;
  if expected_event_title is distinct from coalesce(target.title,'') then
    raise exception 'Event title confirmation does not match';
  end if;
  summary := public.preview_event_permanent_deletion(target_event_id);

  delete from public.finance_receipt_verifications where payment_id in (
    select pay.id from public.pledge_payments pay join public.event_pledges p on p.id=pay.pledge_id where p.event_id=target_event_id
  );
  delete from public.finance_automation_delivery_logs where event_id=target_event_id;
  delete from public.pledge_reminders where event_id=target_event_id;
  delete from public.finance_audit_logs where event_id=target_event_id;
  delete from public.pledge_payments where pledge_id in (select id from public.event_pledges where event_id=target_event_id);
  delete from public.event_pledges where event_id=target_event_id;
  delete from public.event_finance_access_links where event_id=target_event_id;
  delete from public.event_finance_automation_settings where event_id=target_event_id;
  delete from public.event_finance_targets where event_id=target_event_id;
  delete from public.whatsapp_message_logs where invitation_id in (select id from public.invitations where event_id=target_event_id);
  delete from public.event_wishes where event_id=target_event_id;
  delete from public.invitations where event_id=target_event_id;
  delete from public.guest_import_history where event_id=target_event_id;
  delete from public.guests where event_id=target_event_id;
  insert into public.destructive_action_audit(
    action,event_id,event_title,actor_user_id,summary
  ) values (
    'event_deleted_permanently',target.id,coalesce(target.title,''),auth.uid(),summary
  );
  delete from public.events where id=target_event_id;

  return summary || jsonb_build_object('deleted',true);
end;
$$;
revoke all on function public.delete_event_permanently(bigint,text,boolean) from public;
grant execute on function public.delete_event_permanently(bigint,text,boolean) to authenticated;

create or replace function public.preview_event_contribution_cleanup(
  target_event_id bigint,
  allow_unmarked_guest_removal boolean default false
) returns jsonb language plpgsql security definer
set search_path = public, auth, pg_catalog
as $$
begin
  if not public.can_manage_event_finance(target_event_id) then raise exception 'Not authorized'; end if;
  return jsonb_build_object(
    'totalContributors', (select count(*) from public.event_pledges where event_id=target_event_id),
    'contributorsWithPayments', (select count(*) from public.event_pledges p where p.event_id=target_event_id and exists(select 1 from public.pledge_payments pay where pay.pledge_id=p.id)),
    'contributorsWithoutPayments', (select count(*) from public.event_pledges p where p.event_id=target_event_id and not exists(select 1 from public.pledge_payments pay where pay.pledge_id=p.id)),
    'guestsCanBeRemoved', (select count(distinct g.id) from public.guests g join public.event_pledges p on p.guest_id=g.id
      where p.event_id=target_event_id and g.event_id=target_event_id and allow_unmarked_guest_removal
        and g.checked_in_at is null
        and not exists(select 1 from public.event_pledges linked join public.pledge_payments pay on pay.pledge_id=linked.id where linked.guest_id=g.id)
        and not exists(select 1 from public.event_wishes w where w.guest_id=g.id)
        and not exists(select 1 from public.invitations i where i.guest_id=g.id and
          (i.viewed_at is not null or coalesce(i.rsvp_status,'pending') <> 'pending'
           or exists(select 1 from public.whatsapp_message_logs log where log.invitation_id=i.id)))),
    'guestsMustBePreserved', (select count(distinct g.id) from public.guests g join public.event_pledges p on p.guest_id=g.id
      where p.event_id=target_event_id and g.event_id=target_event_id and (
        not allow_unmarked_guest_removal or g.checked_in_at is not null
        or exists(select 1 from public.event_pledges linked join public.pledge_payments pay on pay.pledge_id=linked.id where linked.guest_id=g.id)
        or exists(select 1 from public.event_wishes w where w.guest_id=g.id)
        or exists(select 1 from public.invitations i where i.guest_id=g.id and
          (i.viewed_at is not null or coalesce(i.rsvp_status,'pending') <> 'pending'
           or exists(select 1 from public.whatsapp_message_logs log where log.invitation_id=i.id)))
      )),
    'receiptsRemainValid', (select count(*) from public.finance_receipt_verifications verification
      join public.pledge_payments pay on pay.id=verification.payment_id
      join public.event_pledges p on p.id=pay.pledge_id where p.event_id=target_event_id)
  );
end;
$$;
revoke all on function public.preview_event_contribution_cleanup(bigint,boolean) from public;
grant execute on function public.preview_event_contribution_cleanup(bigint,boolean) to authenticated;

create or replace function public.bulk_cleanup_event_contributions(
  target_event_id bigint,
  cleanup_action text,
  cancellation_reason text,
  typed_confirmation text default null,
  remove_linked_guests boolean default false,
  allow_unmarked_guest_removal boolean default false
) returns jsonb language plpgsql security definer
set search_path = public, auth, pg_catalog
as $$
declare deleted_pledges integer:=0; cancelled_pledges integer:=0; deleted_guests integer:=0;
  unpaid_ids bigint[]; linked_guest_ids bigint[]; target public.events%rowtype;
begin
  select * into target from public.events where id=target_event_id for update;
  if not found then raise exception 'Event not found'; end if;
  perform pg_advisory_xact_lock(target_event_id);
  if length(btrim(coalesce(cancellation_reason,''))) < 3 then raise exception 'Cancellation reason is required'; end if;

  if cleanup_action='cancel_all' then
    if not public.can_manage_event_finance(target_event_id) then raise exception 'Not authorized'; end if;
    update public.event_pledges set cancelled_at=clock_timestamp(),cancellation_reason=btrim(cancellation_reason)
    where event_id=target_event_id and cancelled_at is null;
    get diagnostics cancelled_pledges = row_count;
  elsif cleanup_action in ('delete_contributions','delete_contributions_and_guests') then
    if not public.is_active_admin() then raise exception 'Not authorized'; end if;
    if typed_confirmation <> 'DELETE CONTRIBUTIONS' then raise exception 'Confirmation phrase does not match'; end if;

    select coalesce(array_agg(p.id),'{}'),coalesce(array_agg(distinct p.guest_id) filter(where p.guest_id is not null),'{}')
    into unpaid_ids,linked_guest_ids from public.event_pledges p
    where p.event_id=target_event_id
      and not exists(select 1 from public.pledge_payments pay where pay.pledge_id=p.id);

    update public.event_pledges set cancelled_at=coalesce(cancelled_at,clock_timestamp()),
      cancellation_reason=case when cancelled_at is null then btrim(cancellation_reason) else public.event_pledges.cancellation_reason end
    where event_id=target_event_id and not (id=any(unpaid_ids)) and cancelled_at is null;
    get diagnostics cancelled_pledges = row_count;

    delete from public.pledge_reminders where pledge_id=any(unpaid_ids);
    update public.finance_audit_logs
      set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('deleted_pledge_id',pledge_id,'bulk_cleanup',true),
          pledge_id=null
      where pledge_id=any(unpaid_ids);
    delete from public.event_pledges where id=any(unpaid_ids);
    get diagnostics deleted_pledges = row_count;

    if cleanup_action='delete_contributions_and_guests' and remove_linked_guests and allow_unmarked_guest_removal then
      delete from public.invitations i using public.guests g
      where i.guest_id=g.id and g.id=any(linked_guest_ids) and g.event_id=target_event_id
        and g.checked_in_at is null and i.viewed_at is null and coalesce(i.rsvp_status,'pending')='pending'
        and not exists(select 1 from public.event_wishes w where w.guest_id=g.id)
        and not exists(select 1 from public.whatsapp_message_logs log where log.invitation_id=i.id);
      delete from public.guests g where g.id=any(linked_guest_ids) and g.event_id=target_event_id
        and g.checked_in_at is null
        and not exists(select 1 from public.event_wishes w where w.guest_id=g.id)
        and not exists(select 1 from public.invitations i where i.guest_id=g.id)
        and not exists(select 1 from public.event_pledges p where p.guest_id=g.id);
      get diagnostics deleted_guests = row_count;
    end if;
  else
    raise exception 'Unsupported cleanup action';
  end if;

  insert into public.finance_audit_logs(event_id,actor_type,actor_user_id,action,metadata)
  values(target_event_id,'authenticated_user',auth.uid(),'bulk_contributions_cleanup',
    jsonb_build_object('cleanup_action',cleanup_action,'deleted_pledges',deleted_pledges,
      'cancelled_pledges',cancelled_pledges,'deleted_guests',deleted_guests,
      'reason',btrim(cancellation_reason)));
  return jsonb_build_object('deletedPledges',deleted_pledges,'cancelledPledges',cancelled_pledges,'deletedGuests',deleted_guests);
end;
$$;
revoke all on function public.bulk_cleanup_event_contributions(bigint,text,text,text,boolean,boolean) from public;
grant execute on function public.bulk_cleanup_event_contributions(bigint,text,text,text,boolean,boolean) to authenticated;
