-- Expense Management: a separate spending budget (distinct from the existing
-- fundraising/collection target), a flexible-category event_expenses table
-- with the same void-and-audit pattern as pledge_payments (no hard deletes,
-- corrections and voids logged to finance_audit_logs), and a private storage
-- bucket for optional receipt/proof attachments.
-- Forward-only. Deliberately not applied automatically.

-- 1. Separate expense budget, alongside the existing fundraising target.
alter table public.event_finance_targets
  add column expense_budget_amount numeric(18,2) check (expense_budget_amount is null or expense_budget_amount > 0);
grant update(expense_budget_amount) on public.event_finance_targets to authenticated;

-- 2. event_expenses: flexible free-text category (no separate categories table),
-- optional receipt_path (nullable -- proof attachment is not required), void-and-audit
-- pattern matching pledge_payments (no hard deletes).
create table public.event_expenses (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete restrict,
  category text not null check (length(btrim(category)) > 0),
  description text,
  amount numeric(18,2) not null check (amount > 0),
  expense_date date not null default current_date,
  payee text,
  receipt_path text,
  notes text,
  recorded_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  voided_at timestamptz,
  voided_by uuid references auth.users(id) on delete set null,
  void_reason text,
  constraint event_expenses_void_reason_check check (
    (voided_at is null and voided_by is null and void_reason is null)
    or (voided_at is not null and length(btrim(void_reason)) >= 3)
  )
);
create index event_expenses_event_valid on public.event_expenses(event_id, expense_date desc)
  where voided_at is null;
create trigger event_expenses_updated_at
before update on public.event_expenses
for each row execute function public.set_finance_updated_at();

alter table public.event_expenses enable row level security;
create policy finance_expenses_select on public.event_expenses for select to authenticated
using (public.can_manage_event_finance(event_id));
revoke insert, update, delete on public.event_expenses from anon, authenticated;

-- 3. Audit trail: add expense_id (mirrors the existing payment_id column) and
-- extend the action list with the three new expense actions.
alter table public.finance_audit_logs
  add column expense_id bigint references public.event_expenses(id) on delete restrict;

alter table public.finance_audit_logs drop constraint if exists finance_audit_logs_action_check;
alter table public.finance_audit_logs add constraint finance_audit_logs_action_check check (action in (
  'pledge_created','pledge_updated','pledge_cancelled','pledge_restored','pledge_deleted_permanently','payment_recorded','payment_voided','payment_corrected',
  'reminder_requested','reminder_sent','reminder_failed','organiser_link_created','organiser_link_revoked','pledge_import_completed','bulk_contributions_cleanup',
  'contributor_guest_linked','contributor_guest_created','contributor_guest_card_upgraded','contributor_guest_card_downgrade_requested','contributor_guest_eligibility_lost','contributor_guest_sync_failed',
  'pledge_thank_you_requested','pledge_thank_you_sent','pledge_thank_you_failed','public_pledge_link_created','public_pledge_link_updated','public_pledge_link_revoked',
  'public_pledge_submitted','public_pledge_matched','public_pledge_review_required','acknowledgement_queued','acknowledgement_sent','acknowledgement_failed',
  'reminder_schedule_created','reminder_recommended','reminder_queued','reminder_skipped','reminder_schedules_cancelled','reminder_schedule_recalculated','reminder_no_date_manual','reminder_paused','reminder_resumed',
  'master_automation_paused','master_automation_resumed','held_automation_processed','held_automation_cancelled',
  'expense_recorded','expense_corrected','expense_voided'
));

-- 4. RPCs. All return jsonb (not a hand-declared RETURNS TABLE) to avoid the
-- column-type-mismatch class of bug hit in 202608100004/202608100005.

create or replace function public.record_event_expense(
  target_event_id bigint, category text, description text, amount numeric,
  expense_date date, payee text, receipt_path text, notes text
) returns jsonb language plpgsql security definer set search_path = public, auth, pg_catalog as $$
declare new_expense_id bigint;
begin
  if not public.can_manage_event_finance(target_event_id) then raise exception 'Not authorized'; end if;
  if amount is null or amount <= 0 then raise exception 'Expense amount must be greater than zero'; end if;
  if category is null or length(btrim(category)) = 0 then raise exception 'Expense category is required'; end if;

  insert into public.event_expenses(event_id, category, description, amount, expense_date, payee, receipt_path, notes, recorded_by)
  values (target_event_id, btrim(category), nullif(btrim(description),''), amount, coalesce(expense_date, current_date),
    nullif(btrim(payee),''), nullif(btrim(receipt_path),''), nullif(btrim(notes),''), auth.uid())
  returning id into new_expense_id;

  insert into public.finance_audit_logs(event_id, expense_id, actor_type, actor_user_id, action, new_data)
  values (target_event_id, new_expense_id, 'authenticated_user', auth.uid(), 'expense_recorded',
    jsonb_build_object('category', btrim(category), 'amount', amount, 'expense_date', coalesce(expense_date, current_date)));

  return (select to_jsonb(e) from public.event_expenses e where e.id = new_expense_id);
end;
$$;
revoke all on function public.record_event_expense(bigint,text,text,numeric,date,text,text,text) from public;
grant execute on function public.record_event_expense(bigint,text,text,numeric,date,text,text,text) to authenticated;

create or replace function public.correct_event_expense(
  target_expense_id bigint, corrected_category text, corrected_description text, corrected_amount numeric,
  corrected_expense_date date, corrected_payee text, corrected_receipt_path text, corrected_notes text,
  correction_reason text
) returns jsonb language plpgsql security definer set search_path = public, auth, pg_catalog as $$
declare expense public.event_expenses%rowtype;
begin
  select * into expense from public.event_expenses where id = target_expense_id for update;
  if not found then raise exception 'Expense not found'; end if;
  if not public.can_manage_event_finance(expense.event_id) then raise exception 'Not authorized'; end if;
  if expense.voided_at is not null then raise exception 'Voided expenses cannot be corrected'; end if;
  if corrected_amount is null or corrected_amount <= 0 then raise exception 'Expense amount must be greater than zero'; end if;
  if corrected_category is null or length(btrim(corrected_category)) = 0 then raise exception 'Expense category is required'; end if;
  if length(btrim(coalesce(correction_reason, ''))) < 3 then raise exception 'A clear correction reason is required'; end if;

  update public.event_expenses set
    category = btrim(corrected_category),
    description = nullif(btrim(corrected_description),''),
    amount = corrected_amount,
    expense_date = coalesce(corrected_expense_date, expense_date),
    payee = nullif(btrim(corrected_payee),''),
    receipt_path = nullif(btrim(corrected_receipt_path),''),
    notes = nullif(btrim(corrected_notes),'')
  where id = expense.id;

  insert into public.finance_audit_logs(event_id, expense_id, actor_type, actor_user_id, action, previous_data, new_data, metadata)
  values (expense.event_id, expense.id, 'authenticated_user', auth.uid(), 'expense_corrected',
    jsonb_build_object('category',expense.category,'amount',expense.amount,'expense_date',expense.expense_date,'payee',expense.payee,'notes',expense.notes),
    jsonb_build_object('category',btrim(corrected_category),'amount',corrected_amount,'expense_date',coalesce(corrected_expense_date,expense.expense_date),'payee',nullif(btrim(corrected_payee),''),'notes',nullif(btrim(corrected_notes),'')),
    jsonb_build_object('correction_reason', btrim(correction_reason)));

  return (select to_jsonb(e) from public.event_expenses e where e.id = expense.id);
end;
$$;
revoke all on function public.correct_event_expense(bigint,text,text,numeric,date,text,text,text,text) from public;
grant execute on function public.correct_event_expense(bigint,text,text,numeric,date,text,text,text,text) to authenticated;

create or replace function public.void_event_expense(target_expense_id bigint, reason text)
returns jsonb language plpgsql security definer set search_path = public, auth, pg_catalog as $$
declare expense public.event_expenses%rowtype;
begin
  select * into expense from public.event_expenses where id = target_expense_id for update;
  if not found then raise exception 'Expense not found'; end if;
  if not public.can_manage_event_finance(expense.event_id) then raise exception 'Not authorized'; end if;
  if expense.voided_at is not null then raise exception 'Expense is already voided'; end if;
  if length(btrim(coalesce(reason, ''))) < 3 then raise exception 'A clear void reason is required'; end if;

  update public.event_expenses set voided_at = now(), voided_by = auth.uid(), void_reason = btrim(reason)
  where id = expense.id;

  insert into public.finance_audit_logs(event_id, expense_id, actor_type, actor_user_id, action, previous_data, new_data)
  values (expense.event_id, expense.id, 'authenticated_user', auth.uid(), 'expense_voided',
    jsonb_build_object('amount', expense.amount, 'category', expense.category),
    jsonb_build_object('void_reason', btrim(reason)));

  return (select to_jsonb(e) from public.event_expenses e where e.id = expense.id);
end;
$$;
revoke all on function public.void_event_expense(bigint,text) from public;
grant execute on function public.void_event_expense(bigint,text) to authenticated;

-- 5. Expose the new expense budget alongside the existing fundraising target.
-- get_event_finance_summary()'s return type is changing (one new column), which
-- Postgres does not allow via CREATE OR REPLACE -- the old signature must be
-- dropped first (same reason 202608100004 needed a drop for its RPCs).
drop function if exists public.get_event_finance_summary(bigint);
create function public.get_event_finance_summary(target_event_id bigint)
returns table(
  total_pledged numeric, total_collected numeric, remaining_balance numeric,
  active_pledge_count bigint, pledged_count bigint, partial_count bigint,
  completed_count bigint, cancelled_count bigint, completion_percentage numeric,
  total_contributors bigint, budget_amount numeric, contribution_deadline date,
  budget_progress_percentage numeric, remaining_to_budget numeric,
  days_remaining integer, deadline_status text, expense_budget_amount numeric
)
language plpgsql security definer set search_path=public,auth,pg_catalog as $$
begin
  if not public.can_manage_event_finance(target_event_id) then raise exception 'Not authorized'; end if;
  return query
  with totals as (
    select
      coalesce(sum(s.pledged_amount) filter(where s.calculated_status<>'cancelled'),0) pledged,
      coalesce(sum(s.total_paid) filter(where s.calculated_status<>'cancelled'),0) collected,
      coalesce(sum(s.balance) filter(where s.calculated_status<>'cancelled'),0) balance,
      count(*) filter(where s.calculated_status<>'cancelled') active_count,
      count(*) filter(where s.calculated_status='pledged') pending_count,
      count(*) filter(where s.calculated_status='partial') partial_count,
      count(*) filter(where s.calculated_status='completed') completed_count,
      count(*) filter(where s.calculated_status='cancelled') cancelled_count
    from public.event_pledge_financial_summary s where s.event_id=target_event_id
  )
  select t.pledged,t.collected,t.balance,t.active_count,t.pending_count,t.partial_count,
    t.completed_count,t.cancelled_count,
    case when t.pledged=0 then 0 else round(100*t.collected/t.pledged,2) end,
    t.active_count,target.budget_amount,target.contribution_deadline,
    case when target.budget_amount is null then null else round(100*t.collected/target.budget_amount,2) end,
    case when target.budget_amount is null then null else greatest(target.budget_amount-t.collected,0) end,
    case when target.contribution_deadline is null then null else target.contribution_deadline-current_date end,
    case
      when target.budget_amount is not null and t.collected>=target.budget_amount then 'Budget achieved'
      when target.contribution_deadline is null then 'No deadline'
      when target.contribution_deadline<current_date then 'Deadline passed'
      when target.contribution_deadline=current_date then 'Due today'
      else 'Upcoming'
    end,
    target.expense_budget_amount
  from totals t left join public.event_finance_targets target on target.event_id=target_event_id;
end;
$$;
revoke all on function public.get_event_finance_summary(bigint) from public;
grant execute on function public.get_event_finance_summary(bigint) to authenticated;

-- 6. Private storage bucket for optional receipt/proof attachments. Objects are
-- expected at path "{event_id}/{filename}"; RLS extracts the event_id from the
-- path and checks the same can_manage_event_finance() used everywhere else.
-- NOTE: if this INSERT is rejected by your Supabase project's permissions, create
-- the bucket manually via Dashboard -> Storage -> New bucket (name
-- "expense-receipts", Public OFF) and then run just the three CREATE POLICY
-- statements below.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('expense-receipts', 'expense-receipts', false, 10485760, array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict (id) do nothing;

create policy expense_receipts_select on storage.objects for select to authenticated
using (bucket_id = 'expense-receipts' and public.can_manage_event_finance(((storage.foldername(name))[1])::bigint));

create policy expense_receipts_insert on storage.objects for insert to authenticated
with check (bucket_id = 'expense-receipts' and public.can_manage_event_finance(((storage.foldername(name))[1])::bigint));

create policy expense_receipts_delete on storage.objects for delete to authenticated
using (bucket_id = 'expense-receipts' and public.can_manage_event_finance(((storage.foldername(name))[1])::bigint));
