-- Meeting Invitations V1. Deliberately not applied automatically.

create table public.event_meetings (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete restrict,
  title text not null check (length(btrim(title)) > 0),
  meeting_date date not null,
  meeting_time time not null,
  venue text not null check (length(btrim(venue)) > 0),
  map_url text check (map_url is null or map_url ~ '^https?://'),
  note text,
  status text not null default 'draft' check (status in ('draft','active','completed','cancelled')),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.meeting_invitation_deliveries (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null references public.event_meetings(id) on delete restrict,
  event_id bigint not null references public.events(id) on delete restrict,
  pledge_id bigint not null references public.event_pledges(id) on delete restrict,
  channel text not null check (channel in ('sms','whatsapp')),
  recipient_phone text not null,
  message_body text not null,
  delivery_status text not null default 'queued' check (delivery_status in ('queued','processing','sent','delivered','read','failed')),
  provider_message_id text,
  error_code text,
  error_message text,
  retry_count integer not null default 0 check (retry_count >= 0),
  idempotency_key text not null unique,
  queued_at timestamptz,
  last_attempt_at timestamptz,
  sent_at timestamptz,
  delivered_at timestamptz,
  read_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index event_meetings_event_date_idx on public.event_meetings(event_id,meeting_date desc);
create index meeting_invitation_deliveries_meeting_idx on public.meeting_invitation_deliveries(meeting_id,created_at desc);
create index meeting_invitation_deliveries_event_idx on public.meeting_invitation_deliveries(event_id,created_at desc);
create index meeting_invitation_deliveries_pledge_idx on public.meeting_invitation_deliveries(pledge_id,created_at desc);
create unique index meeting_invitation_deliveries_provider_idx on public.meeting_invitation_deliveries(channel,provider_message_id) where provider_message_id is not null;

create trigger event_meetings_updated_at before update on public.event_meetings
for each row execute function public.set_finance_updated_at();
create trigger meeting_invitation_deliveries_updated_at before update on public.meeting_invitation_deliveries
for each row execute function public.set_finance_updated_at();

alter table public.event_meetings enable row level security;
alter table public.meeting_invitation_deliveries enable row level security;

create policy event_meetings_manager_all on public.event_meetings for all to authenticated
using (public.can_manage_event_finance(event_id))
with check (public.can_manage_event_finance(event_id));
create policy meeting_invitation_deliveries_manager_read on public.meeting_invitation_deliveries for select to authenticated
using (public.can_manage_event_finance(event_id));

revoke all on public.event_meetings from anon,authenticated,service_role;
revoke all on public.meeting_invitation_deliveries from anon,authenticated,service_role;
revoke all on sequence public.event_meetings_id_seq from anon,authenticated,service_role;
revoke all on sequence public.meeting_invitation_deliveries_id_seq from anon,authenticated,service_role;

grant select,insert,update on public.event_meetings to authenticated;
grant usage,select on sequence public.event_meetings_id_seq to authenticated;
grant select on public.meeting_invitation_deliveries to authenticated;
grant select,insert,update on public.event_meetings,public.meeting_invitation_deliveries to service_role;
grant usage,select on sequence public.event_meetings_id_seq,public.meeting_invitation_deliveries_id_seq to service_role;
