-- Apply through the normal reviewed migration workflow. Do not run ad hoc in production.
--
-- Adds a 6th invitation_template value, 'custom': organizers upload their own
-- fully-designed background image (colors/photo/decoration untouched) and
-- position four overlay elements (guest name, venue, date/time, QR code) on
-- it as percentages, independent of image resolution. The five existing
-- photo-led templates (202608060004) are untouched.

alter table public.events
  drop constraint if exists events_invitation_template_check;

alter table public.events
  add constraint events_invitation_template_check
  check (
    invitation_template in (
      'royal_portrait',
      'golden_elegance',
      'botanical_romance',
      'modern_minimal_photo',
      'heritage_pattern',
      'custom'
    )
  );

alter table public.events
  add column if not exists custom_invitation_background_url text;

create table if not exists public.event_invitation_layout_elements (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  element_key text not null check (element_key in ('guest_name', 'venue', 'datetime', 'qr')),
  x_pct numeric not null check (x_pct >= 0 and x_pct <= 100),
  y_pct numeric not null check (y_pct >= 0 and y_pct <= 100),
  width_pct numeric not null check (width_pct > 0 and width_pct <= 100),
  height_pct numeric not null check (height_pct > 0 and height_pct <= 100),
  font_size numeric,
  align text check (align in ('left', 'center', 'right')),
  color text,
  updated_at timestamptz not null default now(),
  unique (event_id, element_key)
);

alter table public.event_invitation_layout_elements enable row level security;

-- can_manage_event_finance() (202607250001) is a general admin-or-owning-organizer
-- check despite its name -- already reused outside finance for workflow_events
-- (202608010003), so reusing it here for invitation layout is consistent, not a
-- misuse of a finance-scoped helper.
create policy event_invitation_layout_elements_select on public.event_invitation_layout_elements
  for select to authenticated
  using (public.can_manage_event_finance(event_id));

create policy event_invitation_layout_elements_insert on public.event_invitation_layout_elements
  for insert to authenticated
  with check (public.can_manage_event_finance(event_id));

create policy event_invitation_layout_elements_update on public.event_invitation_layout_elements
  for update to authenticated
  using (public.can_manage_event_finance(event_id))
  with check (public.can_manage_event_finance(event_id));

create policy event_invitation_layout_elements_delete on public.event_invitation_layout_elements
  for delete to authenticated
  using (public.can_manage_event_finance(event_id));

grant select on public.event_invitation_layout_elements to service_role;

-- Storage bucket for uploaded backgrounds. Public (like event-covers), since the
-- WhatsApp card renderer and the public /invite/[token] page both fetch it via
-- plain HTTP, same as cover_image_url today. Uploads happen from the event
-- create/edit form before the event necessarily exists yet (same as
-- uploadEventCover), so writes are gated on the authenticated role only, not
-- scoped to a specific event folder.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('invitation-backgrounds', 'invitation-backgrounds', true, 8388608, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

create policy invitation_backgrounds_insert on storage.objects for insert to authenticated
with check (bucket_id = 'invitation-backgrounds');

create policy invitation_backgrounds_update on storage.objects for update to authenticated
using (bucket_id = 'invitation-backgrounds')
with check (bucket_id = 'invitation-backgrounds');

create policy invitation_backgrounds_delete on storage.objects for delete to authenticated
using (bucket_id = 'invitation-backgrounds');

-- Expose the new fields through the public invitation lookup used by the
-- invite page, WhatsApp card renderer, and template preview.
-- CREATE OR REPLACE can't change a function's OUT-parameter (return table)
-- shape, so the old signature must be dropped first.
drop function if exists public.get_public_invitation(uuid);

create function public.get_public_invitation(token_input uuid)
 returns table(invitation_id bigint, invitation_token uuid, invitation_status text, rsvp_status text, guest_id bigint, guest_name text, allowed_guests integer, category text, qr_token uuid, event_pass_id text, event_id bigint, event_title text, event_type text, bride_name text, groom_name text, language text, ceremony_title text, ceremony_date date, ceremony_time time without time zone, ceremony_venue text, ceremony_map_url text, event_date date, event_time time without time zone, venue text, reception_map_url text, dress_code text, cover_image_url text, theme_primary_color text, theme_secondary_color text, theme_accent_color text, invitation_template text, photo_layout text, invitation_message text, custom_invitation_background_url text, custom_layout_elements jsonb)
 language sql
 security definer
 set search_path to 'public'
as $function$
  select
    i.id::bigint as invitation_id,
    i.invitation_token,
    i.invitation_status,
    i.rsvp_status,

    g.id::bigint as guest_id,
    g.full_name as guest_name,
    g.allowed_guests,
    g.category,
    g.qr_token,
    g.event_pass_id,

    e.id::bigint as event_id,
    e.title as event_title,
    e.event_type,
    e.bride_name,
    e.groom_name,
    e.language,

    e.ceremony_title,
    e.ceremony_date,
    e.ceremony_time,
    e.ceremony_venue,
    e.ceremony_map_url,

    e.event_date,
    e.event_time,
    e.venue,
    e.reception_map_url,

    e.dress_code,
    e.cover_image_url,

    e.theme_primary_color,
    e.theme_secondary_color,
    e.theme_accent_color,

    e.invitation_template,
    e.photo_layout,
    e.invitation_message,

    e.custom_invitation_background_url,

    (
      select jsonb_agg(
        jsonb_build_object(
          'key', l.element_key,
          'xPct', l.x_pct,
          'yPct', l.y_pct,
          'widthPct', l.width_pct,
          'heightPct', l.height_pct,
          'fontSize', l.font_size,
          'align', l.align,
          'color', l.color
        )
      )
      from public.event_invitation_layout_elements as l
      where l.event_id = e.id
    ) as custom_layout_elements

  from public.invitations as i

  inner join public.guests as g
    on g.id = i.guest_id

  inner join public.events as e
    on e.id = i.event_id

  where i.invitation_token = token_input

  limit 1;
$function$;
