-- Redesign SMS Outreach recipients to be campaign-scoped and independent of
-- public.guests. Guests must only ever be created by the existing
-- contributor-guest sync path (sync_contributor_guest, gated by
-- event_contributor_guest_settings) when a pledge crosses a configured
-- threshold -- never as a side effect of an outreach campaign that hasn't
-- converted to a pledge yet. sms_campaign_deliveries is empty in every
-- environment (confirmed before writing this), so this is a clean
-- redefinition, not a data migration. 202608230001 was already applied to
-- production, so this is a new file rather than an edit to that one --
-- migration history should reflect what was actually run, in order.
--
-- Deliberately not applied automatically.

drop table if exists public.sms_campaign_deliveries;

create table public.sms_campaign_recipients (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.sms_campaigns(id) on delete restrict,
  full_name text not null check (length(btrim(full_name)) > 0),
  phone text not null check (length(btrim(phone)) > 0),
  normalized_phone text not null check (normalized_phone ~ '^255[67][0-9]{8}$'),
  created_at timestamptz not null default now()
);
create unique index sms_campaign_recipients_campaign_phone_idx
  on public.sms_campaign_recipients(campaign_id, normalized_phone);
create index sms_campaign_recipients_campaign_idx
  on public.sms_campaign_recipients(campaign_id, created_at desc);

create table public.sms_campaign_deliveries (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.sms_campaigns(id) on delete restrict,
  event_id bigint not null references public.events(id) on delete restrict,
  -- Informational only: deleting a recipient row must never restrict deleting
  -- (or block anything about) its permanent delivery/audit record, so this
  -- sets null on delete rather than restrict. full_name/recipient_phone are
  -- denormalized onto the row (same principle as message_body already was)
  -- so this table stands alone even if the recipient row is later removed.
  recipient_id bigint references public.sms_campaign_recipients(id) on delete set null,
  full_name text not null,
  recipient_phone text not null,
  message_body text not null,
  delivery_status text not null default 'processing' check (delivery_status in ('processing','sent','failed')),
  provider_message_id text,
  error_message text,
  idempotency_key text not null unique,
  sent_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index sms_campaign_deliveries_campaign_idx on public.sms_campaign_deliveries(campaign_id, created_at desc);
create index sms_campaign_deliveries_event_idx on public.sms_campaign_deliveries(event_id, created_at desc);
create index sms_campaign_deliveries_recipient_idx on public.sms_campaign_deliveries(recipient_id);

create trigger sms_campaign_deliveries_updated_at before update on public.sms_campaign_deliveries
for each row execute function public.set_finance_updated_at();

alter table public.sms_campaign_recipients enable row level security;
alter table public.sms_campaign_deliveries enable row level security;

-- Same admin-only shape as sms_campaigns: all writes go through the
-- service-role API route (app/api/sms/custom-campaign), which checks
-- profiles.role = 'admin' itself. Authenticated grants below are read-only.
create policy sms_campaign_recipients_admin_read on public.sms_campaign_recipients for select to authenticated
using (public.is_active_admin());
create policy sms_campaign_deliveries_admin_read on public.sms_campaign_deliveries for select to authenticated
using (public.is_active_admin());

revoke all on public.sms_campaign_recipients from anon,authenticated,service_role;
revoke all on public.sms_campaign_deliveries from anon,authenticated,service_role;
revoke all on sequence public.sms_campaign_recipients_id_seq from anon,authenticated,service_role;
revoke all on sequence public.sms_campaign_deliveries_id_seq from anon,authenticated,service_role;

grant select on public.sms_campaign_recipients to authenticated;
grant select on public.sms_campaign_deliveries to authenticated;
grant select,insert,update on public.sms_campaign_recipients,public.sms_campaign_deliveries to service_role;
grant usage,select on sequence public.sms_campaign_recipients_id_seq,public.sms_campaign_deliveries_id_seq to service_role;
