-- Save the Date: a card sent before the formal invitation, as its own campaign (not an
-- invitation_template value -- the event keeps its invitation card, e.g. gilded_border).
-- It carries no QR, Pass ID, guest count, time or ceremony details.
--
-- Recipients (enforced in services/saveTheDateService.ts, re-checked at send time): pledges that are
-- fully paid (calculated_status = 'completed') AND classified Double with total_paid >= 100,000, or
-- Single with total_paid >= 70,000. Sending is manual (admin/organizer presses "Tuma") for now.
--
-- 1. events.save_the_date_variant: the card's colour, chosen in the Contributions > Save the Date
--    tab. Independent of gilded_variant, so the Save the Date and the Gilded invitation of one event
--    can differ. Default 'navy' like gilded_variant; adding it changes no existing card.
-- 2. save_the_date_deliveries: one row per pledge, mirroring guest_thank_you_deliveries (claim
--    before send via a unique idempotency_key; processing/sent/failed; WhatsApp first, SMS fallback
--    with the WhatsApp error kept). card_token is the only key the public card URL accepts -- a
--    random uuid unrelated to guests.qr_token / event_pass_id, so the card can never act as a pass.
--    It does not touch invitations.invitation_status, so the invitation "sent" state is unaffected.
--
-- Foreign keys cascade so permanent event/pledge deletion needs no changes to the deletion
-- functions. Deliberately not applied automatically.

begin;

alter table public.events
  add column if not exists save_the_date_variant text not null default 'navy'
  check (save_the_date_variant in ('navy', 'cream'));

create table public.save_the_date_deliveries (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  pledge_id bigint not null references public.event_pledges(id) on delete cascade,
  guest_id bigint references public.guests(id) on delete set null,
  full_name text not null,
  recipient_phone text not null,
  card_token uuid not null unique default gen_random_uuid(),
  variant text not null check (variant in ('navy', 'cream')),
  channel text check (channel in ('whatsapp', 'sms')),
  delivery_status text not null default 'processing' check (delivery_status in ('processing', 'sent', 'failed')),
  provider_message_id text,
  error_message text,
  whatsapp_error_message text,
  idempotency_key text not null unique,
  sent_at timestamptz,
  failed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index save_the_date_deliveries_event_idx on public.save_the_date_deliveries(event_id, created_at desc);
create index save_the_date_deliveries_pledge_idx on public.save_the_date_deliveries(pledge_id);

create trigger save_the_date_deliveries_updated_at before update on public.save_the_date_deliveries
for each row execute function public.set_finance_updated_at();

alter table public.save_the_date_deliveries enable row level security;

-- Read-only for the event's admin/organizer (pledge domain, same rule as event_pledges). All writes go
-- through the service-role API route (app/api/save-the-date), which checks the caller itself.
create policy save_the_date_deliveries_manager_read on public.save_the_date_deliveries for select to authenticated
using (public.can_manage_event_finance(event_id));

revoke all on public.save_the_date_deliveries from anon, authenticated, service_role;
revoke all on sequence public.save_the_date_deliveries_id_seq from anon, authenticated, service_role;

grant select on public.save_the_date_deliveries to authenticated;
grant select, insert, update, delete on public.save_the_date_deliveries to service_role;
grant usage, select on sequence public.save_the_date_deliveries_id_seq to service_role;

commit;
