-- Guest Thank You messaging: a bulk "thank you for attending/supporting"
-- send to every guest invited to one event (not the pledge/contributor
-- domain -- that already has its own pledge_thank_you flow under
-- financialAutomationService/financialNotificationEngine). Mirrors the
-- sms_campaign_deliveries shape (claim-before-send via a unique
-- idempotency_key, processing/sent/failed states) but keyed directly to
-- public.guests for one event, with a nullable channel column since which
-- channel actually delivers (WhatsApp first, SMS fallback) is only known
-- after the send attempt.
--
-- Deliberately not applied automatically.

create table public.guest_thank_you_deliveries (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete restrict,
  guest_id bigint not null references public.guests(id) on delete cascade,
  full_name text not null,
  recipient_phone text not null,
  channel text check (channel in ('whatsapp', 'sms')),
  delivery_status text not null default 'processing' check (delivery_status in ('processing', 'sent', 'failed')),
  provider_message_id text,
  error_message text,
  idempotency_key text not null unique,
  sent_at timestamptz,
  failed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index guest_thank_you_deliveries_event_idx on public.guest_thank_you_deliveries(event_id, created_at desc);
create index guest_thank_you_deliveries_guest_idx on public.guest_thank_you_deliveries(guest_id);

create trigger guest_thank_you_deliveries_updated_at before update on public.guest_thank_you_deliveries
for each row execute function public.set_finance_updated_at();

alter table public.guest_thank_you_deliveries enable row level security;

-- Admin/organizer only, both directions: all writes go through the
-- service-role API route (app/api/invitations/thank-you), which
-- authenticates the caller and checks profiles.role itself before touching
-- this table. This read policy only covers a future direct dashboard read
-- (matches the sms_campaign_deliveries precedent).
create policy guest_thank_you_deliveries_admin_organizer_read on public.guest_thank_you_deliveries for select to authenticated
using (
  exists (
    select 1 from public.profiles
    where id = auth.uid() and is_active and role in ('admin', 'organizer')
  )
);

revoke all on public.guest_thank_you_deliveries from anon, authenticated, service_role;
revoke all on sequence public.guest_thank_you_deliveries_id_seq from anon, authenticated, service_role;

grant select on public.guest_thank_you_deliveries to authenticated;
grant select, insert, update on public.guest_thank_you_deliveries to service_role;
grant usage, select on sequence public.guest_thank_you_deliveries_id_seq to service_role;

-- Extend the permanent-deletion preview/cleanup functions the same way
-- every other event-scoped table has had to (most recently 202609130001) --
-- forward-only, not applied automatically, matching that migration's own
-- convention. Full bodies are carried forward unchanged aside from the new
-- guest_thank_you_deliveries line in each.
create or replace function public.preview_event_permanent_deletion(target_event_id bigint)
returns jsonb language plpgsql security definer
set search_path = public, auth, pg_catalog
as $$
declare target public.events%rowtype;
begin
  if not public.is_active_admin() then raise exception 'Not authorized'; end if;
  select * into target from public.events where id = target_event_id;
  if not found then raise exception 'Event not found'; end if;
  return jsonb_build_object(
    'eventId', target.id,
    'eventTitle', coalesce(target.title, ''),
    'guests', (select count(*) from public.guests where event_id=target.id),
    'invitations', (select count(*) from public.invitations where event_id=target.id),
    'pledges', (select count(*) from public.event_pledges where event_id=target.id),
    'validPayments', (select count(*) from public.pledge_payments pay join public.event_pledges p on p.id=pay.pledge_id where p.event_id=target.id and pay.voided_at is null),
    'voidedPayments', (select count(*) from public.pledge_payments pay join public.event_pledges p on p.id=pay.pledge_id where p.event_id=target.id and pay.voided_at is not null),
    'receipts', (select count(*) from public.finance_receipt_verifications verification join public.pledge_payments pay on pay.id=verification.payment_id join public.event_pledges p on p.id=pay.pledge_id where p.event_id=target.id),
    'committeeLinks', (select count(*) from public.event_finance_access_links where event_id=target.id),
    'reminderHistory', (select count(*) from public.pledge_reminders where event_id=target.id),
    'automationDeliveries', (select count(*) from public.finance_automation_delivery_logs where event_id=target.id),
    'wishes', (select count(*) from public.event_wishes where event_id=target.id),
    'guestImportHistory', (select count(*) from public.guest_import_history where event_id=target.id),
    'financeTargets', (select count(*) from public.event_finance_targets where event_id=target.id),
    'whatsappMessageLogs', (select count(*) from public.whatsapp_message_logs log
      join public.invitations invitation on invitation.id=log.invitation_id
      where invitation.event_id=target.id),
    'financeAuditLogs', (select count(*) from public.finance_audit_logs where event_id=target.id),
    'financeAutomationSettings', (select count(*) from public.event_finance_automation_settings where event_id=target.id),
    'workflowEvents', (select count(*) from public.workflow_events where event_id=target.id),
    'publicPledgeLinks', (select count(*) from public.public_pledge_links where event_id=target.id),
    'publicPledgeReviews', (select count(*) from public.public_pledge_reviews where event_id=target.id),
    'pledgeReminderSettings', (select count(*) from public.event_pledge_reminder_settings where event_id=target.id),
    'expenses', (select count(*) from public.event_expenses where event_id=target.id),
    'expenseCategoryBudgets', (select count(*) from public.event_expense_category_budgets where event_id=target.id),
    'meetings', (select count(*) from public.event_meetings where event_id=target.id),
    'meetingInvitationDeliveries', (select count(*) from public.meeting_invitation_deliveries where event_id=target.id),
    'smsCampaigns', (select count(*) from public.sms_campaigns where event_id=target.id),
    'smsCampaignRecipients', (select count(*) from public.sms_campaign_recipients recipient
      join public.sms_campaigns campaign on campaign.id=recipient.campaign_id
      where campaign.event_id=target.id),
    'smsCampaignDeliveries', (select count(*) from public.sms_campaign_deliveries where event_id=target.id),
    'guestThankYouDeliveries', (select count(*) from public.guest_thank_you_deliveries where event_id=target.id)
  );
end;
$$;

create or replace function public.delete_event_permanently(
  target_event_id bigint,
  expected_event_title text,
  second_confirmation boolean
) returns jsonb language plpgsql security definer
set search_path = public, auth, pg_catalog
as $$
declare target public.events%rowtype; summary jsonb;
begin
  if not public.is_active_admin() then raise exception 'Not authorized'; end if;
  if second_confirmation is not true then raise exception 'Confirmation required'; end if;
  select * into target from public.events where id=target_event_id for update;
  if not found then raise exception 'Event not found'; end if;
  if expected_event_title is distinct from coalesce(target.title,'') then
    raise exception 'Event title confirmation does not match';
  end if;
  summary := public.preview_event_permanent_deletion(target_event_id);

  delete from public.finance_receipt_verifications where payment_id in (
    select pay.id from public.pledge_payments pay join public.event_pledges p on p.id=pay.pledge_id where p.event_id=target_event_id
  );
  delete from public.finance_automation_delivery_logs where event_id=target_event_id;
  delete from public.pledge_reminders where event_id=target_event_id;
  delete from public.finance_audit_logs where event_id=target_event_id;

  -- meeting_invitation_deliveries.pledge_id is ON DELETE RESTRICT against
  -- event_pledges, and its meeting_id is ON DELETE RESTRICT against
  -- event_meetings -- must go before both.
  delete from public.meeting_invitation_deliveries where event_id=target_event_id;

  delete from public.pledge_payments where pledge_id in (select id from public.event_pledges where event_id=target_event_id);
  delete from public.event_pledges where event_id=target_event_id;
  delete from public.event_meetings where event_id=target_event_id;
  delete from public.event_finance_access_links where event_id=target_event_id;
  delete from public.event_finance_automation_settings where event_id=target_event_id;
  delete from public.event_finance_targets where event_id=target_event_id;
  delete from public.event_expenses where event_id=target_event_id;
  delete from public.event_expense_category_budgets where event_id=target_event_id;
  delete from public.whatsapp_message_logs where invitation_id in (select id from public.invitations where event_id=target_event_id);
  delete from public.event_wishes where event_id=target_event_id;
  -- guest_id is ON DELETE CASCADE against guests, so this would clear itself
  -- once guests are deleted below -- deleted explicitly here anyway to keep
  -- this function's own event_id-restrict FK satisfied without relying on
  -- that cascade ordering.
  delete from public.guest_thank_you_deliveries where event_id=target_event_id;
  delete from public.invitations where event_id=target_event_id;
  delete from public.guest_import_history where event_id=target_event_id;
  delete from public.guests where event_id=target_event_id;

  -- sms_campaign_deliveries.recipient_id is ON DELETE SET NULL against
  -- sms_campaign_recipients, so order between these two doesn't matter for
  -- FK safety; both must go before sms_campaigns (campaign_id is restrict).
  delete from public.sms_campaign_deliveries where event_id=target_event_id;
  delete from public.sms_campaign_recipients where campaign_id in (select id from public.sms_campaigns where event_id=target_event_id);
  delete from public.sms_campaigns where event_id=target_event_id;

  -- Newer workflow-automation / public-pledge-link tables (added after this
  -- function was first written). Reviews must go before links: reviews.link_id
  -- is ON DELETE RESTRICT against public_pledge_links.
  delete from public.public_pledge_reviews where event_id=target_event_id;
  delete from public.public_pledge_links where event_id=target_event_id;
  delete from public.event_pledge_reminder_settings where event_id=target_event_id;
  delete from public.workflow_events where event_id=target_event_id;

  insert into public.destructive_action_audit(
    action,event_id,event_title,actor_user_id,summary
  ) values (
    'event_deleted_permanently',target.id,coalesce(target.title,''),auth.uid(),summary
  );
  delete from public.events where id=target_event_id;

  return summary || jsonb_build_object('deleted',true);
end;
$$;
