-- Smart Event Pass Financial Suite V2
-- Deliberately not applied automatically. Existing application models use bigint
-- for events.id and guests.id, and uuid for auth/profile identifiers.

create extension if not exists pgcrypto;

create or replace function public.can_manage_event_finance(target_event_id bigint)
returns boolean language sql stable security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.profiles p
    join public.events e on e.id = target_event_id
    where p.id = auth.uid()
      and p.is_active
      and p.role in ('admin', 'administrator', 'organizer')
      and (p.role in ('admin', 'administrator') or e.organizer_id = auth.uid())
  );
$$;

revoke all on function public.can_manage_event_finance(bigint) from public;
grant execute on function public.can_manage_event_finance(bigint) to authenticated;

create table public.event_pledges (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete restrict,
  guest_id bigint references public.guests(id) on delete restrict,
  full_name text not null check (length(btrim(full_name)) > 0),
  phone text not null check (length(btrim(phone)) > 0),
  normalized_phone text not null check (normalized_phone ~ '^255[0-9]{9}$'),
  email text,
  pledged_amount numeric(18,2) not null check (pledged_amount > 0),
  currency_code varchar(3) not null default 'TZS' check (currency_code ~ '^[A-Z]{3}$'),
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  cancelled_at timestamptz,
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_pledges_cancel_reason_check check (
    (cancelled_at is null and cancellation_reason is null)
    or (cancelled_at is not null and length(btrim(cancellation_reason)) >= 3)
  )
);

create unique index event_pledges_one_active_guest
  on public.event_pledges(event_id, guest_id)
  where guest_id is not null and cancelled_at is null;
create index event_pledges_event_phone on public.event_pledges(event_id, normalized_phone);
create index event_pledges_event_created on public.event_pledges(event_id, created_at desc);

create table public.finance_receipt_counters (
  receipt_year integer primary key check (receipt_year between 2020 and 9999),
  last_value bigint not null default 0 check (last_value >= 0),
  updated_at timestamptz not null default now()
);

create table public.pledge_payments (
  id bigint generated by default as identity primary key,
  pledge_id bigint not null references public.event_pledges(id) on delete restrict,
  receipt_number text not null unique,
  amount numeric(18,2) not null check (amount > 0),
  currency_code varchar(3) not null default 'TZS' check (currency_code ~ '^[A-Z]{3}$'),
  payment_date date not null default current_date,
  payment_method text not null check (payment_method in ('cash','mobile_money','bank','card','other')),
  payment_reference text,
  provider text,
  notes text,
  recorded_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  voided_at timestamptz,
  voided_by uuid references auth.users(id) on delete set null,
  void_reason text,
  constraint pledge_payments_void_reason_check check (
    (voided_at is null and voided_by is null and void_reason is null)
    or (voided_at is not null and length(btrim(void_reason)) >= 3)
  )
);
create index pledge_payments_pledge_valid on public.pledge_payments(pledge_id, payment_date desc)
  where voided_at is null;

create table public.pledge_reminders (
  id bigint generated by default as identity primary key,
  pledge_id bigint not null references public.event_pledges(id) on delete restrict,
  event_id bigint not null references public.events(id) on delete restrict,
  reminder_type text not null check (reminder_type in ('pledge_reminder','partial_thank_you','completed_thank_you','custom')),
  channel text not null check (channel in ('sms','whatsapp')),
  recipient_phone text not null,
  message_body text not null,
  delivery_status text not null default 'queued' check (delivery_status in ('queued','sent','delivered','read','failed')),
  provider_message_id text,
  error_message text,
  requested_by uuid references auth.users(id) on delete set null default auth.uid(),
  scheduled_for timestamptz,
  sent_at timestamptz,
  idempotency_key text,
  created_at timestamptz not null default now()
);
create unique index pledge_reminders_idempotency on public.pledge_reminders(idempotency_key)
  where idempotency_key is not null;
create index pledge_reminders_pledge_created on public.pledge_reminders(pledge_id, created_at desc);

create table public.event_finance_access_links (
  id uuid primary key default gen_random_uuid(),
  event_id bigint not null references public.events(id) on delete restrict,
  token_hash text not null unique check (token_hash ~ '^[a-f0-9]{64}$'),
  label text,
  permissions jsonb not null default '{"view_pledges":true,"create_pledges":true,"edit_contributors":true,"record_payments":true,"view_payment_history":true,"send_reminders":true,"search":true}'::jsonb,
  expires_at timestamptz,
  revoked_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  check (jsonb_typeof(permissions) = 'object')
);
create index event_finance_access_links_event on public.event_finance_access_links(event_id, created_at desc);

create table public.finance_audit_logs (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete restrict,
  pledge_id bigint references public.event_pledges(id) on delete restrict,
  payment_id bigint references public.pledge_payments(id) on delete restrict,
  actor_type text not null check (actor_type in ('authenticated_user','organiser_link','system')),
  actor_user_id uuid references auth.users(id) on delete set null,
  organiser_access_link_id uuid references public.event_finance_access_links(id) on delete set null,
  action text not null check (action in (
    'pledge_created','pledge_updated','pledge_cancelled','payment_recorded','payment_voided',
    'reminder_requested','reminder_sent','reminder_failed','organiser_link_created',
    'organiser_link_revoked','pledge_import_completed'
  )),
  previous_data jsonb,
  new_data jsonb,
  metadata jsonb,
  created_at timestamptz not null default now()
);
create index finance_audit_logs_event_created on public.finance_audit_logs(event_id, created_at desc);
create index finance_audit_logs_pledge_created on public.finance_audit_logs(pledge_id, created_at desc);

create or replace function public.set_finance_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;
create trigger event_pledges_updated_at before update on public.event_pledges
for each row execute function public.set_finance_updated_at();

create or replace function public.validate_event_pledge()
returns trigger language plpgsql set search_path = public as $$
declare paid numeric;
begin
  if new.guest_id is not null and not exists (
    select 1 from public.guests g where g.id = new.guest_id and g.event_id = new.event_id
  ) then
    raise exception 'Selected guest does not belong to this event';
  end if;
  if tg_op = 'UPDATE' and new.pledged_amount is distinct from old.pledged_amount then
    select coalesce(sum(amount),0) into paid from public.pledge_payments
      where pledge_id = old.id and voided_at is null;
    if new.pledged_amount < paid then
      raise exception 'Pledged amount cannot be lower than valid payments';
    end if;
  end if;
  return new;
end;
$$;
create trigger validate_event_pledge before insert or update on public.event_pledges
for each row execute function public.validate_event_pledge();

create or replace function public.audit_event_pledge_change()
returns trigger language plpgsql security definer set search_path = public, auth as $$
begin
  if tg_op = 'INSERT' then
    insert into public.finance_audit_logs(event_id, pledge_id, actor_type, actor_user_id, action, new_data)
    values (new.event_id, new.id, 'authenticated_user', auth.uid(), 'pledge_created',
      jsonb_build_object('full_name',new.full_name,'phone',new.phone,'pledged_amount',new.pledged_amount,'currency_code',new.currency_code));
  elsif old.cancelled_at is null and new.cancelled_at is not null then
    insert into public.finance_audit_logs(event_id, pledge_id, actor_type, actor_user_id, action, previous_data, new_data)
    values (new.event_id, new.id, 'authenticated_user', auth.uid(), 'pledge_cancelled',
      jsonb_build_object('cancelled_at',old.cancelled_at),
      jsonb_build_object('cancelled_at',new.cancelled_at,'cancellation_reason',new.cancellation_reason));
  elsif row(old.full_name,old.phone,old.email,old.pledged_amount,old.notes)
        is distinct from row(new.full_name,new.phone,new.email,new.pledged_amount,new.notes) then
    insert into public.finance_audit_logs(event_id, pledge_id, actor_type, actor_user_id, action, previous_data, new_data)
    values (new.event_id, new.id, 'authenticated_user', auth.uid(), 'pledge_updated',
      jsonb_build_object('full_name',old.full_name,'phone',old.phone,'email',old.email,'pledged_amount',old.pledged_amount,'notes',old.notes),
      jsonb_build_object('full_name',new.full_name,'phone',new.phone,'email',new.email,'pledged_amount',new.pledged_amount,'notes',new.notes));
  end if;
  return new;
end;
$$;
create trigger audit_event_pledge after insert or update on public.event_pledges
for each row execute function public.audit_event_pledge_change();

create or replace view public.event_pledge_financial_summary
with (security_invoker = true) as
select
  p.id, p.event_id, p.guest_id, p.full_name, p.phone, p.normalized_phone, p.email,
  p.pledged_amount, p.currency_code, p.notes,
  coalesce(sum(pay.amount) filter (where pay.voided_at is null), 0::numeric) as total_paid,
  greatest(p.pledged_amount - coalesce(sum(pay.amount) filter (where pay.voided_at is null), 0::numeric), 0::numeric) as balance,
  case
    when p.cancelled_at is not null then 'cancelled'
    when coalesce(sum(pay.amount) filter (where pay.voided_at is null), 0::numeric) = 0 then 'pledged'
    when coalesce(sum(pay.amount) filter (where pay.voided_at is null), 0::numeric) < p.pledged_amount then 'partial'
    else 'completed'
  end as calculated_status,
  count(pay.id) filter (where pay.voided_at is null) as payment_count,
  max(pay.created_at) filter (where pay.voided_at is null) as last_payment_at,
  p.cancelled_at, p.cancellation_reason, p.created_at, p.updated_at
from public.event_pledges p
left join public.pledge_payments pay on pay.pledge_id = p.id
group by p.id;

create or replace function public.record_pledge_payment(
  target_pledge_id bigint, payment_amount numeric, paid_on date,
  method text, reference text default null, payment_provider text default null, payment_notes text default null
) returns public.event_pledge_financial_summary
language plpgsql security definer set search_path = public, auth as $$
declare p public.event_pledges%rowtype; paid numeric; counter_value bigint; receipt text; result public.event_pledge_financial_summary%rowtype;
begin
  if payment_amount is null or payment_amount <= 0 then raise exception 'Payment amount must be greater than zero'; end if;
  if method not in ('cash','mobile_money','bank','card','other') then raise exception 'Unsupported payment method'; end if;
  select * into p from public.event_pledges where id = target_pledge_id for update;
  if not found then raise exception 'Pledge not found'; end if;
  if not public.can_manage_event_finance(p.event_id) then raise exception 'Not authorized'; end if;
  if p.cancelled_at is not null then raise exception 'Cancelled pledges cannot receive payments'; end if;
  select coalesce(sum(amount),0) into paid from public.pledge_payments where pledge_id=p.id and voided_at is null;
  if paid + payment_amount > p.pledged_amount then raise exception 'Payment exceeds the remaining pledge balance'; end if;
  insert into public.finance_receipt_counters(receipt_year,last_value)
  values (extract(year from coalesce(paid_on,current_date))::int,1)
  on conflict (receipt_year) do update set last_value=public.finance_receipt_counters.last_value+1, updated_at=now()
  returning last_value into counter_value;
  receipt := 'SEP-PAY-' || extract(year from coalesce(paid_on,current_date))::int || '-' || lpad(counter_value::text,6,'0');
  insert into public.pledge_payments(pledge_id,receipt_number,amount,currency_code,payment_date,payment_method,payment_reference,provider,notes)
  values (p.id,receipt,payment_amount,p.currency_code,coalesce(paid_on,current_date),method,nullif(btrim(reference),''),nullif(btrim(payment_provider),''),nullif(btrim(payment_notes),''))
  returning id into counter_value;
  insert into public.finance_audit_logs(event_id,pledge_id,payment_id,actor_type,actor_user_id,action,new_data)
  values(p.event_id,p.id,counter_value,'authenticated_user',auth.uid(),'payment_recorded',
    jsonb_build_object('amount',payment_amount,'receipt_number',receipt,'payment_method',method));
  select * into result from public.event_pledge_financial_summary where id=p.id; return result;
end;
$$;

create or replace function public.void_pledge_payment(target_payment_id bigint, reason text)
returns public.event_pledge_financial_summary language plpgsql security definer set search_path=public,auth as $$
declare pay public.pledge_payments%rowtype; p public.event_pledges%rowtype; result public.event_pledge_financial_summary%rowtype;
begin
  if length(btrim(coalesce(reason,''))) < 3 then raise exception 'A clear void reason is required'; end if;
  select * into pay from public.pledge_payments where id=target_payment_id for update;
  if not found then raise exception 'Payment not found'; end if;
  if pay.voided_at is not null then raise exception 'Payment is already voided'; end if;
  select * into p from public.event_pledges where id=pay.pledge_id;
  if not public.can_manage_event_finance(p.event_id) then raise exception 'Not authorized'; end if;
  update public.pledge_payments set voided_at=now(),voided_by=auth.uid(),void_reason=btrim(reason) where id=pay.id;
  insert into public.finance_audit_logs(event_id,pledge_id,payment_id,actor_type,actor_user_id,action,previous_data,new_data)
  values(p.event_id,p.id,pay.id,'authenticated_user',auth.uid(),'payment_voided',
    jsonb_build_object('voided_at',pay.voided_at),jsonb_build_object('voided_at',now(),'void_reason',btrim(reason)));
  select * into result from public.event_pledge_financial_summary where id=p.id; return result;
end;
$$;

create or replace function public.cancel_event_pledge(target_pledge_id bigint, reason text)
returns public.event_pledge_financial_summary language plpgsql security definer set search_path=public,auth as $$
declare p public.event_pledges%rowtype; result public.event_pledge_financial_summary%rowtype;
begin
  if length(btrim(coalesce(reason,''))) < 3 then raise exception 'A clear cancellation reason is required'; end if;
  select * into p from public.event_pledges where id=target_pledge_id for update;
  if not found then raise exception 'Pledge not found'; end if;
  if not public.can_manage_event_finance(p.event_id) then raise exception 'Not authorized'; end if;
  if p.cancelled_at is not null then raise exception 'Pledge is already cancelled'; end if;
  update public.event_pledges set cancelled_at=now(),cancellation_reason=btrim(reason) where id=p.id;
  select * into result from public.event_pledge_financial_summary where id=p.id; return result;
end;
$$;

create or replace function public.get_event_finance_summary(target_event_id bigint)
returns table(total_pledged numeric,total_collected numeric,remaining_balance numeric,active_pledge_count bigint,
 pledged_count bigint,partial_count bigint,completed_count bigint,cancelled_count bigint,completion_percentage numeric)
language plpgsql security definer set search_path=public,auth as $$
begin
  if not public.can_manage_event_finance(target_event_id) then raise exception 'Not authorized'; end if;
  return query select
    coalesce(sum(s.pledged_amount) filter(where s.calculated_status<>'cancelled'),0),
    coalesce(sum(s.total_paid) filter(where s.calculated_status<>'cancelled'),0),
    coalesce(sum(s.balance) filter(where s.calculated_status<>'cancelled'),0),
    count(*) filter(where s.calculated_status<>'cancelled'),
    count(*) filter(where s.calculated_status='pledged'), count(*) filter(where s.calculated_status='partial'),
    count(*) filter(where s.calculated_status='completed'), count(*) filter(where s.calculated_status='cancelled'),
    case when coalesce(sum(s.pledged_amount) filter(where s.calculated_status<>'cancelled'),0)=0 then 0
      else round(100*sum(s.total_paid) filter(where s.calculated_status<>'cancelled')/
        sum(s.pledged_amount) filter(where s.calculated_status<>'cancelled'),2) end
  from public.event_pledge_financial_summary s where s.event_id=target_event_id;
end;
$$;

alter table public.event_pledges enable row level security;
alter table public.pledge_payments enable row level security;
alter table public.finance_receipt_counters enable row level security;
alter table public.pledge_reminders enable row level security;
alter table public.event_finance_access_links enable row level security;
alter table public.finance_audit_logs enable row level security;

create policy finance_pledges_manage on public.event_pledges for all to authenticated
using (public.can_manage_event_finance(event_id)) with check (public.can_manage_event_finance(event_id));
create policy finance_payments_select on public.pledge_payments for select to authenticated
using (exists(select 1 from public.event_pledges p where p.id=pledge_id and public.can_manage_event_finance(p.event_id)));
create policy finance_reminders_manage on public.pledge_reminders for all to authenticated
using (public.can_manage_event_finance(event_id)) with check (public.can_manage_event_finance(event_id));
create policy finance_links_manage on public.event_finance_access_links for all to authenticated
using (public.can_manage_event_finance(event_id)) with check (public.can_manage_event_finance(event_id));
create policy finance_audit_select on public.finance_audit_logs for select to authenticated
using (public.can_manage_event_finance(event_id));

revoke all on public.finance_receipt_counters from anon, authenticated;
revoke delete on public.event_pledges from anon, authenticated;
revoke delete on public.pledge_reminders from anon, authenticated;
revoke delete on public.event_finance_access_links from anon, authenticated;
revoke insert, update, delete on public.pledge_payments from anon, authenticated;
revoke insert, update, delete on public.finance_audit_logs from anon, authenticated;
revoke all on function public.record_pledge_payment(bigint,numeric,date,text,text,text,text) from public;
revoke all on function public.void_pledge_payment(bigint,text) from public;
revoke all on function public.cancel_event_pledge(bigint,text) from public;
revoke all on function public.get_event_finance_summary(bigint) from public;
grant execute on function public.record_pledge_payment(bigint,numeric,date,text,text,text,text) to authenticated;
grant execute on function public.void_pledge_payment(bigint,text) to authenticated;
grant execute on function public.cancel_event_pledge(bigint,text) to authenticated;
grant execute on function public.get_event_finance_summary(bigint) to authenticated;
