-- Workflow Automation V2 foundation and public pledge capture.
-- Forward-only. Deliberately not applied automatically.

create table public.workflow_events (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete restrict,
  event_type text not null check (event_type in ('pledge.submitted','pledge.updated','payment.recorded','payment.completed','message.acknowledgement.requested')),
  entity_type text not null,
  entity_id text,
  source text not null,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  idempotency_key text not null unique,
  status text not null default 'pending' check (status in ('pending','processing','processed','failed')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  available_at timestamptz not null default now(), processed_at timestamptz, last_error text,
  created_at timestamptz not null default now()
);
create index workflow_events_event_created on public.workflow_events(event_id,created_at desc);
create index workflow_events_claim on public.workflow_events(status,available_at,id) where status in ('pending','failed');

create table public.public_pledge_links (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete restrict,
  token_hash text not null unique check (token_hash ~ '^[a-f0-9]{64}$'),
  title text, message text, default_language text not null default 'sw' check (default_language in ('sw','en')),
  expires_at timestamptz, is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  last_used_at timestamptz, submission_count integer not null default 0 check (submission_count >= 0),
  check (title is null or length(title) <= 120), check (message is null or length(message) <= 500)
);
create index public_pledge_links_event_created on public.public_pledge_links(event_id,created_at desc);
create trigger public_pledge_links_updated_at before update on public.public_pledge_links
for each row execute function public.set_finance_updated_at();

create table public.public_pledge_reviews (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete restrict,
  link_id bigint not null references public.public_pledge_links(id) on delete restrict,
  matched_pledge_ids bigint[] not null default '{}', submitted_data jsonb not null,
  reason text not null check (reason in ('ambiguous_match','adjustment_requested')),
  status text not null default 'pending' check (status in ('pending','resolved','dismissed')),
  idempotency_key text not null unique, created_at timestamptz not null default now(), resolved_at timestamptz
);
create index public_pledge_reviews_event_status on public.public_pledge_reviews(event_id,status,created_at desc);

create table public.public_pledge_rate_limits (
  token_hash text not null, ip_hash text not null, window_started_at timestamptz not null,
  request_count integer not null default 1, primary key(token_hash,ip_hash,window_started_at)
);
revoke all on public.public_pledge_rate_limits from anon,authenticated;

alter table public.event_pledges add column source text not null default 'internal'
  check (source in ('internal','import','organiser_link','public_pledge_link'));
alter table public.event_pledges add column public_pledge_link_id bigint references public.public_pledge_links(id) on delete set null;
alter table public.event_pledges add column expected_completion_date date;

alter table public.finance_audit_logs drop constraint if exists finance_audit_logs_action_check;
alter table public.finance_audit_logs add constraint finance_audit_logs_action_check check (action in (
  'pledge_created','pledge_updated','pledge_cancelled','pledge_restored','pledge_deleted_permanently',
  'payment_recorded','payment_voided','payment_corrected',
  'reminder_requested','reminder_sent','reminder_failed','organiser_link_created','organiser_link_revoked',
  'pledge_import_completed','bulk_contributions_cleanup','contributor_guest_linked','contributor_guest_created',
  'contributor_guest_card_upgraded','contributor_guest_card_downgrade_requested','contributor_guest_eligibility_lost','contributor_guest_sync_failed',
  'pledge_thank_you_requested','public_pledge_link_created','public_pledge_link_updated','public_pledge_link_revoked',
  'public_pledge_submitted','public_pledge_matched','public_pledge_review_required','acknowledgement_queued',
  'acknowledgement_sent','acknowledgement_failed'
));

create or replace view public.event_pledge_financial_summary with (security_invoker=true) as
select p.id,p.event_id,p.guest_id,p.full_name,p.phone,p.normalized_phone,p.email,p.pledged_amount,p.currency_code,p.notes,
 coalesce(sum(pay.amount) filter(where pay.voided_at is null),0::numeric) total_paid,
 greatest(p.pledged_amount-coalesce(sum(pay.amount) filter(where pay.voided_at is null),0::numeric),0::numeric) balance,
 case when p.cancelled_at is not null then 'cancelled' when coalesce(sum(pay.amount) filter(where pay.voided_at is null),0)=0 then 'pledged' when coalesce(sum(pay.amount) filter(where pay.voided_at is null),0)<p.pledged_amount then 'partial' else 'completed' end calculated_status,
 count(pay.id) filter(where pay.voided_at is null) payment_count,max(pay.created_at) filter(where pay.voided_at is null) last_payment_at,
 p.cancelled_at,p.cancellation_reason,p.created_at,p.updated_at,count(pay.id) payment_row_count,
 (count(pay.id)>0 or exists(select 1 from public.finance_receipt_verifications r join public.pledge_payments rp on rp.id=r.payment_id where rp.pledge_id=p.id)) has_protected_financial_history,
 p.guest_eligibility_status,g.allowed_guests linked_guest_allowed_guests,p.source,p.public_pledge_link_id,p.expected_completion_date
from public.event_pledges p left join public.pledge_payments pay on pay.pledge_id=p.id left join public.guests g on g.id=p.guest_id and g.event_id=p.event_id
group by p.id,g.allowed_guests;

alter table public.workflow_events enable row level security;
alter table public.public_pledge_links enable row level security;
alter table public.public_pledge_reviews enable row level security;
alter table public.public_pledge_rate_limits enable row level security;
create policy workflow_events_manager_read on public.workflow_events for select to authenticated using (public.can_manage_event_finance(event_id));
create policy public_pledge_links_manager_read on public.public_pledge_links for select to authenticated using (public.can_manage_event_finance(event_id));
create policy public_pledge_reviews_manager_read on public.public_pledge_reviews for select to authenticated using (public.can_manage_event_finance(event_id));
revoke insert,update,delete on public.workflow_events,public.public_pledge_links,public.public_pledge_reviews from anon,authenticated;

create or replace function public.create_public_pledge_link(target_event_id bigint,supplied_token_hash text,link_title text,link_message text,link_language text,link_expires_at timestamptz)
returns public.public_pledge_links language plpgsql security definer set search_path=public,auth,pg_catalog as $$
declare result public.public_pledge_links%rowtype;
begin
  if not public.can_manage_event_finance(target_event_id) then raise exception 'Not authorized'; end if;
  if supplied_token_hash is null or supplied_token_hash !~ '^[a-f0-9]{64}$' then raise exception 'Invalid token'; end if;
  if link_language not in ('sw','en') or (link_expires_at is not null and link_expires_at <= now()) then raise exception 'Invalid link settings'; end if;
  insert into public.public_pledge_links(event_id,token_hash,title,message,default_language,expires_at)
  values(target_event_id,supplied_token_hash,nullif(btrim(link_title),''),nullif(btrim(link_message),''),link_language,link_expires_at) returning * into result;
  insert into public.finance_audit_logs(event_id,actor_type,actor_user_id,action,new_data)
  values(target_event_id,'authenticated_user',auth.uid(),'public_pledge_link_created',jsonb_build_object('link_id',result.id,'expires_at',result.expires_at,'language',result.default_language));
  return result;
end $$;

create or replace function public.update_public_pledge_link(target_link_id bigint,link_active boolean,link_expires_at timestamptz,link_title text,link_message text,link_language text)
returns public.public_pledge_links language plpgsql security definer set search_path=public,auth,pg_catalog as $$
declare current_link public.public_pledge_links%rowtype; result public.public_pledge_links%rowtype;
begin
  select * into current_link from public.public_pledge_links where id=target_link_id for update;
  if not found or not public.can_manage_event_finance(current_link.event_id) then raise exception 'Not authorized'; end if;
  if link_language not in ('sw','en') then raise exception 'Invalid link settings'; end if;
  update public.public_pledge_links set is_active=link_active,expires_at=link_expires_at,title=nullif(btrim(link_title),''),message=nullif(btrim(link_message),''),default_language=link_language where id=target_link_id returning * into result;
  insert into public.finance_audit_logs(event_id,actor_type,actor_user_id,action,new_data)
  values(result.event_id,'authenticated_user',auth.uid(),case when link_active then 'public_pledge_link_updated' else 'public_pledge_link_revoked' end,jsonb_build_object('link_id',result.id,'is_active',result.is_active,'expires_at',result.expires_at));
  return result;
end $$;

create or replace function public.get_public_pledge_link(supplied_token_hash text)
returns jsonb language sql stable security definer set search_path=public,pg_catalog as $$
  select case when l.id is null then null else jsonb_build_object('valid',l.is_active and (l.expires_at is null or l.expires_at>now()),'event_name',e.title,'title',l.title,'message',l.message,'language',l.default_language) end
  from public.public_pledge_links l join public.events e on e.id=l.event_id where l.token_hash=supplied_token_hash limit 1
$$;

create or replace function public.submit_public_pledge(supplied_token_hash text,submission_key text,submitter_name text,submitter_phone text,submitter_email text,amount numeric,expected_date date,submitter_note text,request_ip_hash text)
returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$
declare link public.public_pledge_links%rowtype; normalized_name text; matches bigint[]; match_count int; new_pledge_id bigint; review_id bigint; window_start timestamptz; existing_result jsonb;
begin
  if supplied_token_hash is null or supplied_token_hash !~ '^[a-f0-9]{64}$' or submission_key is null or length(submission_key) not between 16 and 100 then raise exception 'LINK_UNAVAILABLE'; end if;
  select payload->'public_receipt' into existing_result from public.workflow_events where idempotency_key='public:'||submission_key;
  if existing_result is not null then return existing_result; end if;
  select * into link from public.public_pledge_links where token_hash=supplied_token_hash for update;
  if not found or not link.is_active or (link.expires_at is not null and link.expires_at<=now()) then raise exception 'LINK_UNAVAILABLE'; end if;
  window_start := date_trunc('hour',now());
  insert into public.public_pledge_rate_limits(token_hash,ip_hash,window_started_at) values(supplied_token_hash,request_ip_hash,window_start)
  on conflict(token_hash,ip_hash,window_started_at) do update set request_count=public.public_pledge_rate_limits.request_count+1 returning request_count into match_count;
  if match_count>10 then raise exception 'RATE_LIMITED'; end if;
  normalized_name:=lower(regexp_replace(btrim(coalesce(submitter_name,'')),'\s+',' ','g'));
  if length(normalized_name)<2 or amount is null or amount<=0 or amount>1000000000 then raise exception 'INVALID_SUBMISSION'; end if;
  if submitter_phone is not null and submitter_phone !~ '^255[67][0-9]{8}$' then raise exception 'INVALID_SUBMISSION'; end if;
  if submitter_email is not null and (length(submitter_email)>254 or submitter_email !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$') then raise exception 'INVALID_SUBMISSION'; end if;
  if expected_date is not null and expected_date<current_date-interval '31 days' then raise exception 'INVALID_SUBMISSION'; end if;
  if submitter_phone is not null then select array_agg(id) into matches from public.event_pledges where event_id=link.event_id and normalized_phone=submitter_phone and cancelled_at is null;
  else select array_agg(id) into matches from public.event_pledges where event_id=link.event_id and lower(regexp_replace(btrim(full_name),'\s+',' ','g'))=normalized_name and cancelled_at is null; end if;
  match_count:=coalesce(cardinality(matches),0);
  if match_count=0 then
    insert into public.event_pledges(event_id,full_name,phone,normalized_phone,email,pledged_amount,notes,created_by,source,public_pledge_link_id,expected_completion_date)
    values(link.event_id,btrim(submitter_name),submitter_phone,submitter_phone,nullif(lower(btrim(submitter_email)),''),amount,nullif(btrim(submitter_note),''),null,'public_pledge_link',link.id,expected_date) returning id into new_pledge_id;
    delete from public.finance_audit_logs audit where audit.pledge_id=new_pledge_id and audit.actor_user_id is null and audit.action='pledge_created' and audit.created_at>=transaction_timestamp();
  else
    new_pledge_id:=case when match_count=1 then matches[1] else null end;
    insert into public.public_pledge_reviews(event_id,link_id,matched_pledge_ids,submitted_data,reason,idempotency_key)
    values(link.event_id,link.id,matches,jsonb_build_object('full_name',btrim(submitter_name),'phone',submitter_phone,'email',submitter_email,'amount',amount,'expected_date',expected_date,'note',submitter_note),case when match_count>1 then 'ambiguous_match' else 'adjustment_requested' end,submission_key) returning id into review_id;
  end if;
  update public.public_pledge_links set submission_count=submission_count+1,last_used_at=now() where id=link.id;
  insert into public.finance_audit_logs(event_id,pledge_id,actor_type,action,new_data,metadata)
  values(link.event_id,new_pledge_id,'system',case when review_id is null then 'public_pledge_submitted' else 'public_pledge_review_required' end,jsonb_build_object('amount',amount,'source','public_pledge_link'),jsonb_build_object('link_id',link.id,'review_id',review_id));
  existing_result := jsonb_build_object(
    'status',
    case
      when review_id is null then 'received'
      else 'review'
    end,
    'receipt',
    encode(extensions.gen_random_bytes(9), 'hex')
  );
  insert into public.workflow_events(event_id,event_type,entity_type,entity_id,source,payload,idempotency_key)
  values(link.event_id,'pledge.submitted',case when review_id is null then 'pledge' else 'pledge_review' end,coalesce(new_pledge_id,review_id)::text,'public_pledge_link',jsonb_build_object('pledge_id',new_pledge_id,'review_id',review_id,'public_receipt',existing_result),'public:'||submission_key);
  if new_pledge_id is not null and submitter_phone is not null then
    insert into public.workflow_events(event_id,event_type,entity_type,entity_id,source,payload,idempotency_key)
    values(link.event_id,'message.acknowledgement.requested','pledge',new_pledge_id::text,'public_pledge_link',jsonb_build_object('pledge_id',new_pledge_id,'language',link.default_language),'ack:'||submission_key);
    insert into public.finance_audit_logs(event_id,pledge_id,actor_type,action,metadata) values(link.event_id,new_pledge_id,'system','acknowledgement_queued',jsonb_build_object('workflow_key','ack:'||submission_key));
  end if;
  return existing_result;
end $$;

create or replace function public.claim_workflow_events(batch_size int default 20)
returns setof public.workflow_events language plpgsql security definer set search_path=public,pg_catalog as $$
begin
  return query update public.workflow_events w set status='processing',attempt_count=w.attempt_count+1,last_error=null
  where w.id in (select id from public.workflow_events where status in ('pending','failed') and available_at<=now() and attempt_count<5 order by available_at,id for update skip locked limit least(greatest(batch_size,1),100)) returning w.*;
end $$;

create or replace function public.finish_workflow_event(target_id bigint,succeeded boolean,error_text text default null)
returns void language plpgsql security definer set search_path=public,pg_catalog as $$
begin update public.workflow_events set status=case when succeeded then 'processed' else 'failed' end,processed_at=case when succeeded then now() else null end,last_error=case when succeeded then null else left(error_text,1000) end,available_at=case when succeeded then available_at else now()+(least(attempt_count,5)^2||' minutes')::interval end where id=target_id and status='processing'; end $$;

revoke all on function public.create_public_pledge_link(bigint,text,text,text,text,timestamptz),public.update_public_pledge_link(bigint,boolean,timestamptz,text,text,text),public.get_public_pledge_link(text),public.submit_public_pledge(text,text,text,text,text,numeric,date,text,text),public.claim_workflow_events(int),public.finish_workflow_event(bigint,boolean,text) from public;
grant execute on function public.create_public_pledge_link(bigint,text,text,text,text,timestamptz),public.update_public_pledge_link(bigint,boolean,timestamptz,text,text,text) to authenticated;
grant execute on function public.get_public_pledge_link(text),public.submit_public_pledge(text,text,text,text,text,numeric,date,text,text) to anon;
grant execute on function public.claim_workflow_events(int),public.finish_workflow_event(bigint,boolean,text) to service_role;
grant select on public.workflow_events,public.public_pledge_links,public.public_pledge_reviews to service_role;
