-- Hybrid and date-driven pledge reminder scheduling.
-- Forward-only. Deliberately not applied automatically.

create table public.event_pledge_reminder_settings (
  event_id bigint primary key references public.events(id) on delete restrict,
  reminder_mode text not null default 'manual' check (reminder_mode in ('manual','automatic','hybrid')),
  date_based_enabled boolean not null default true,
  before_due_days integer not null default 3 check (before_due_days between 1 and 365),
  on_due_date_enabled boolean not null default true,
  after_due_days integer not null default 3 check (after_due_days between 1 and 365),
  repeat_after_due_days integer check (repeat_after_due_days between 3 and 365),
  maximum_automatic_reminders integer not null default 3 check (maximum_automatic_reminders between 1 and 12),
  no_date_behavior text not null default 'manual_only' check (no_date_behavior in ('manual_only','recommend_after_days','automatic_after_days')),
  no_date_delay_days integer not null default 14 check (no_date_delay_days between 3 and 365),
  stop_after_event boolean not null default true,
  is_enabled boolean not null default false,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check (no_date_behavior <> 'automatic_after_days' or reminder_mode = 'automatic')
);
create trigger event_pledge_reminder_settings_updated_at before update on public.event_pledge_reminder_settings
for each row execute function public.set_finance_updated_at();

alter table public.event_pledges add column reminder_paused_at timestamptz;
alter table public.event_pledges add column reminder_pause_reason text;
alter table public.event_pledges add constraint event_pledges_reminder_pause_check check (
  (reminder_paused_at is null and reminder_pause_reason is null) or
  (reminder_paused_at is not null and length(btrim(reminder_pause_reason)) >= 3)
);

create table public.pledge_reminder_schedules (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete restrict,
  pledge_id bigint not null references public.event_pledges(id) on delete cascade,
  schedule_type text not null check (schedule_type in ('before_due','due_date','after_due','repeat_after_due','no_date_follow_up','manual')),
  scheduled_for timestamptz not null,
  status text not null check (status in ('scheduled','recommended','queued','processing','sent','delivered','failed','cancelled','skipped')),
  sequence_number integer not null check (sequence_number > 0),
  workflow_event_id bigint references public.workflow_events(id) on delete set null,
  delivery_id bigint references public.pledge_reminders(id) on delete set null,
  source text not null check (source in ('policy','public_pledge','internal','payment','manager')),
  logical_key text not null unique,
  cancelled_at timestamptz, cancel_reason text, last_error text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index pledge_reminder_schedules_event_status on public.pledge_reminder_schedules(event_id,status,scheduled_for);
create index pledge_reminder_schedules_pledge_created on public.pledge_reminder_schedules(pledge_id,created_at desc);
create trigger pledge_reminder_schedules_updated_at before update on public.pledge_reminder_schedules
for each row execute function public.set_finance_updated_at();

create or replace function public.audit_pledge_reminder_schedule()
returns trigger language plpgsql security definer set search_path=public,pg_catalog as $$
declare audit_action text;
begin
  if tg_op='INSERT' then audit_action:=case when new.status='skipped' then 'reminder_skipped' else 'reminder_schedule_created' end;
  elsif new.status is distinct from old.status then audit_action:=case new.status when 'recommended' then 'reminder_recommended' when 'queued' then 'reminder_queued' when 'failed' then 'reminder_failed' when 'skipped' then 'reminder_skipped' when 'cancelled' then 'reminder_schedules_cancelled' else null end;
  end if;
  if audit_action is not null then insert into public.finance_audit_logs(event_id,pledge_id,actor_type,action,metadata) values(new.event_id,new.pledge_id,'system',audit_action,jsonb_build_object('schedule_id',new.id,'schedule_type',new.schedule_type,'status',new.status,'scheduled_for',new.scheduled_for,'reason',coalesce(new.cancel_reason,new.last_error)));end if;
  return new;
end $$;
create trigger audit_pledge_reminder_schedule_change after insert or update of status on public.pledge_reminder_schedules for each row execute function public.audit_pledge_reminder_schedule();

alter table public.event_pledge_reminder_settings enable row level security;
alter table public.pledge_reminder_schedules enable row level security;
create policy pledge_reminder_settings_manager_read on public.event_pledge_reminder_settings for select to authenticated using (public.can_manage_event_finance(event_id));
create policy pledge_reminder_schedules_manager_read on public.pledge_reminder_schedules for select to authenticated using (public.can_manage_event_finance(event_id));
revoke insert,update,delete on public.event_pledge_reminder_settings,public.pledge_reminder_schedules from anon,authenticated;
grant select on public.event_pledge_reminder_settings,public.pledge_reminder_schedules to authenticated;
grant select,insert,update on public.event_pledge_reminder_settings,public.pledge_reminder_schedules to service_role;
grant usage,select on sequence public.pledge_reminder_schedules_id_seq to service_role;

alter table public.workflow_events drop constraint if exists workflow_events_event_type_check;
alter table public.workflow_events add constraint workflow_events_event_type_check check (event_type in (
  'pledge.submitted','pledge.updated','payment.recorded','payment.completed','message.acknowledgement.requested',
  'pledge.reminder.schedule_requested','pledge.reminder.ready','pledge.reminder.send_requested','pledge.reminder.cancel_requested'
));

alter table public.finance_audit_logs drop constraint if exists finance_audit_logs_action_check;
alter table public.finance_audit_logs add constraint finance_audit_logs_action_check check (action in (
  'pledge_created','pledge_updated','pledge_cancelled','pledge_restored','pledge_deleted_permanently','payment_recorded','payment_voided','payment_corrected',
  'reminder_requested','reminder_sent','reminder_failed','organiser_link_created','organiser_link_revoked','pledge_import_completed','bulk_contributions_cleanup',
  'contributor_guest_linked','contributor_guest_created','contributor_guest_card_upgraded','contributor_guest_card_downgrade_requested','contributor_guest_eligibility_lost','contributor_guest_sync_failed',
  'pledge_thank_you_requested','public_pledge_link_created','public_pledge_link_updated','public_pledge_link_revoked','public_pledge_submitted','public_pledge_matched','public_pledge_review_required',
  'acknowledgement_queued','acknowledgement_sent','acknowledgement_failed','reminder_schedule_created','reminder_schedule_recalculated','reminder_recommended',
  'reminder_queued','reminder_skipped','reminder_paused','reminder_resumed','reminder_schedules_cancelled','reminder_no_date_manual'
));

create or replace function public.save_pledge_reminder_settings(target_event_id bigint,settings jsonb)
returns public.event_pledge_reminder_settings language plpgsql security definer set search_path=public,auth,pg_catalog as $$
declare result public.event_pledge_reminder_settings%rowtype;
begin
  if not public.can_manage_event_finance(target_event_id) then raise exception 'Not authorized'; end if;
  insert into public.event_pledge_reminder_settings(event_id,reminder_mode,date_based_enabled,before_due_days,on_due_date_enabled,after_due_days,repeat_after_due_days,maximum_automatic_reminders,no_date_behavior,no_date_delay_days,stop_after_event,is_enabled)
  values(target_event_id,coalesce(settings->>'reminder_mode','manual'),coalesce((settings->>'date_based_enabled')::boolean,true),coalesce((settings->>'before_due_days')::int,3),coalesce((settings->>'on_due_date_enabled')::boolean,true),coalesce((settings->>'after_due_days')::int,3),nullif(settings->>'repeat_after_due_days','')::int,coalesce((settings->>'maximum_automatic_reminders')::int,3),coalesce(settings->>'no_date_behavior','manual_only'),coalesce((settings->>'no_date_delay_days')::int,14),coalesce((settings->>'stop_after_event')::boolean,true),coalesce((settings->>'is_enabled')::boolean,false))
  on conflict(event_id) do update set reminder_mode=excluded.reminder_mode,date_based_enabled=excluded.date_based_enabled,before_due_days=excluded.before_due_days,on_due_date_enabled=excluded.on_due_date_enabled,after_due_days=excluded.after_due_days,repeat_after_due_days=excluded.repeat_after_due_days,maximum_automatic_reminders=excluded.maximum_automatic_reminders,no_date_behavior=excluded.no_date_behavior,no_date_delay_days=excluded.no_date_delay_days,stop_after_event=excluded.stop_after_event,is_enabled=excluded.is_enabled
  returning * into result;
  insert into public.workflow_events(event_id,event_type,entity_type,source,payload,idempotency_key)
  values(target_event_id,'pledge.reminder.schedule_requested','event','manager',jsonb_build_object('event_id',target_event_id,'source','manager'),'reminder-settings:'||target_event_id||':'||extract(epoch from result.updated_at)::bigint)
  on conflict(idempotency_key) do nothing;
  return result;
end $$;

create or replace function public.set_pledge_reminder_pause(target_pledge_id bigint,paused boolean,reason text default null)
returns public.event_pledges language plpgsql security definer set search_path=public,auth,pg_catalog as $$
declare pledge public.event_pledges%rowtype;
begin
  select * into pledge from public.event_pledges where id=target_pledge_id for update;
  if not found or not public.can_manage_event_finance(pledge.event_id) then raise exception 'Not authorized'; end if;
  if paused and length(btrim(coalesce(reason,'')))<3 then raise exception 'A pause reason is required'; end if;
  update public.event_pledges set reminder_paused_at=case when paused then now() else null end,reminder_pause_reason=case when paused then btrim(reason) else null end where id=pledge.id returning * into pledge;
  insert into public.finance_audit_logs(event_id,pledge_id,actor_type,actor_user_id,action,metadata) values(pledge.event_id,pledge.id,'authenticated_user',auth.uid(),case when paused then 'reminder_paused' else 'reminder_resumed' end,jsonb_build_object('reason',reason));
  insert into public.workflow_events(event_id,event_type,entity_type,entity_id,source,payload,idempotency_key) values(pledge.event_id,case when paused then 'pledge.reminder.cancel_requested' else 'pledge.reminder.schedule_requested' end,'pledge',pledge.id::text,'manager',jsonb_build_object('pledge_id',pledge.id,'reason',reason),'reminder-pause:'||pledge.id||':'||txid_current()) on conflict(idempotency_key) do nothing;
  return pledge;
end $$;

create or replace function public.manage_pledge_reminder_schedule(target_schedule_id bigint,requested_action text,requested_for timestamptz default null,reason text default null)
returns public.pledge_reminder_schedules language plpgsql security definer set search_path=public,auth,pg_catalog as $$
declare schedule public.pledge_reminder_schedules%rowtype;
begin
  select * into schedule from public.pledge_reminder_schedules where id=target_schedule_id for update;
  if not found or not public.can_manage_event_finance(schedule.event_id) then raise exception 'Not authorized'; end if;
  if requested_action='approve' and schedule.status='recommended' then update public.pledge_reminder_schedules set status='queued',scheduled_for=now() where id=schedule.id returning * into schedule;
  elsif requested_action='reschedule' and schedule.status in ('scheduled','recommended','queued','failed') and requested_for>now() then update public.pledge_reminder_schedules set status='scheduled',scheduled_for=requested_for,last_error=null,cancel_reason=null where id=schedule.id returning * into schedule;
  elsif requested_action='skip' and schedule.status in ('scheduled','recommended','queued','failed') and length(btrim(coalesce(reason,'')))>=3 then update public.pledge_reminder_schedules set status='skipped',cancel_reason=btrim(reason) where id=schedule.id returning * into schedule;
  else raise exception 'Invalid schedule action'; end if;
  insert into public.finance_audit_logs(event_id,pledge_id,actor_type,actor_user_id,action,metadata) values(schedule.event_id,schedule.pledge_id,'authenticated_user',auth.uid(),case when requested_action='approve' then 'reminder_queued' else 'reminder_skipped' end,jsonb_build_object('schedule_id',schedule.id,'action',requested_action,'reason',reason,'scheduled_for',schedule.scheduled_for));
  return schedule;
end $$;

create or replace function public.recalculate_pledge_reminder_schedules(target_pledge_id bigint,recalculation_source text default 'policy')
returns integer language plpgsql security definer set search_path=public,pg_catalog as $$
declare pledge public.event_pledges%rowtype; setting public.event_pledge_reminder_settings%rowtype; event_date date; paid numeric; occurrence date; kind text; seq int:=0; eligible_count int:=0; created_count int:=0; repeat_index int:=0; desired_status text; key text;
begin
  select * into pledge from public.event_pledges where id=target_pledge_id for update;
  if not found then return 0; end if;
  select * into setting from public.event_pledge_reminder_settings where event_id=pledge.event_id;
  select e.event_date into event_date from public.events e where e.id=pledge.event_id;
  select coalesce(sum(p.amount),0) into paid from public.pledge_payments p where p.pledge_id=pledge.id and p.voided_at is null;
  if setting.event_id is null or not setting.is_enabled or setting.reminder_mode='manual' or pledge.cancelled_at is not null or pledge.reminder_paused_at is not null or paid>=pledge.pledged_amount or (setting.stop_after_event and event_date<current_date) then
    update public.pledge_reminder_schedules set status='cancelled',cancelled_at=now(),cancel_reason=case when pledge.reminder_paused_at is not null then 'paused' when pledge.cancelled_at is not null then 'pledge_cancelled' when paid>=pledge.pledged_amount then 'completed' when setting.event_id is null or not setting.is_enabled then 'automation_disabled' when setting.reminder_mode='manual' then 'manual_mode' else 'event_passed' end where pledge_id=pledge.id and status in ('scheduled','recommended','queued');
    return 0;
  end if;
  update public.pledge_reminder_schedules set status='cancelled',cancelled_at=now(),cancel_reason='schedule_recalculated' where pledge_id=pledge.id and status in ('scheduled','recommended','queued');
  desired_status:='scheduled';
  if pledge.expected_completion_date is null then
    if setting.no_date_behavior='manual_only' then insert into public.finance_audit_logs(event_id,pledge_id,actor_type,action,metadata) values(pledge.event_id,pledge.id,'system','reminder_no_date_manual','{}'); return 0; end if;
    occurrence:=greatest((pledge.created_at::date+setting.no_date_delay_days),current_date);
    kind:='no_date_follow_up';seq:=1;
    if setting.no_date_behavior='recommend_after_days' or setting.reminder_mode='hybrid' then desired_status:='scheduled'; end if;
    key:='reminder:'||pledge.id||':'||kind||':'||occurrence;
    insert into public.pledge_reminder_schedules(event_id,pledge_id,schedule_type,scheduled_for,status,sequence_number,source,logical_key) values(pledge.event_id,pledge.id,kind,occurrence::timestamptz+interval '09:00',desired_status,seq,recalculation_source,key) on conflict(logical_key) do update set scheduled_for=excluded.scheduled_for,status=case when public.pledge_reminder_schedules.status in ('sent','delivered') then public.pledge_reminder_schedules.status else excluded.status end,cancelled_at=null,cancel_reason=null;
    return 1;
  end if;
  if not setting.date_based_enabled then return 0; end if;
  for occurrence,kind in select * from (values (pledge.expected_completion_date-setting.before_due_days,'before_due'),(pledge.expected_completion_date,'due_date'),(pledge.expected_completion_date+setting.after_due_days,'after_due')) candidate(day,typ) loop
    if kind='due_date' and not setting.on_due_date_enabled then continue; end if;
    seq:=seq+1;if occurrence>=current_date then eligible_count:=eligible_count+1;if eligible_count>setting.maximum_automatic_reminders then continue;end if;end if;
    key:='reminder:'||pledge.id||':'||kind||':'||occurrence;
    insert into public.pledge_reminder_schedules(event_id,pledge_id,schedule_type,scheduled_for,status,sequence_number,source,logical_key,cancel_reason)
    values(pledge.event_id,pledge.id,kind,occurrence::timestamptz+interval '09:00',case when occurrence<current_date then 'skipped' else 'scheduled' end,seq,recalculation_source,key,case when occurrence<current_date then 'past_occurrence' else null end)
    on conflict(logical_key) do update set status=case when public.pledge_reminder_schedules.status in ('sent','delivered') then public.pledge_reminder_schedules.status else excluded.status end,cancel_reason=excluded.cancel_reason,cancelled_at=null;
    created_count:=created_count+1;
  end loop;
  while setting.repeat_after_due_days is not null and eligible_count<setting.maximum_automatic_reminders and repeat_index<24 loop
    repeat_index:=repeat_index+1;seq:=seq+1;occurrence:=pledge.expected_completion_date+setting.after_due_days+(setting.repeat_after_due_days*repeat_index);key:='reminder:'||pledge.id||':repeat_after_due:'||occurrence;
    insert into public.pledge_reminder_schedules(event_id,pledge_id,schedule_type,scheduled_for,status,sequence_number,source,logical_key) values(pledge.event_id,pledge.id,'repeat_after_due',occurrence::timestamptz+interval '09:00',case when occurrence<current_date then 'skipped' else 'scheduled' end,seq,recalculation_source,key) on conflict(logical_key) do nothing;created_count:=created_count+1;if occurrence>=current_date then eligible_count:=eligible_count+1;end if;
  end loop;
  insert into public.finance_audit_logs(event_id,pledge_id,actor_type,action,metadata) values(pledge.event_id,pledge.id,'system','reminder_schedule_recalculated',jsonb_build_object('schedule_count',created_count,'source',recalculation_source));
  return created_count;
end $$;

create or replace function public.enqueue_pledge_reminder_recalculation()
returns trigger language plpgsql security definer set search_path=public,pg_catalog as $$
declare target public.event_pledges%rowtype;
begin
  if tg_table_name='pledge_payments' then select * into target from public.event_pledges where id=new.pledge_id; else target:=new; end if;
  insert into public.workflow_events(event_id,event_type,entity_type,entity_id,source,payload,idempotency_key) values(target.event_id,'pledge.reminder.schedule_requested','pledge',target.id::text,'system',jsonb_build_object('pledge_id',target.id,'source',case when tg_table_name='pledge_payments' then 'payment' else 'internal' end),'reminder-recalc:'||target.id||':'||txid_current()) on conflict(idempotency_key) do nothing;
  return new;
end $$;
create trigger enqueue_reminder_after_pledge_change after insert or update of expected_completion_date,cancelled_at,reminder_paused_at,pledged_amount on public.event_pledges for each row execute function public.enqueue_pledge_reminder_recalculation();
create trigger enqueue_reminder_after_payment_change after insert or update of voided_at,amount on public.pledge_payments for each row execute function public.enqueue_pledge_reminder_recalculation();

revoke all on function public.save_pledge_reminder_settings(bigint,jsonb),public.set_pledge_reminder_pause(bigint,boolean,text),public.manage_pledge_reminder_schedule(bigint,text,timestamptz,text),public.recalculate_pledge_reminder_schedules(bigint,text) from public;
grant execute on function public.save_pledge_reminder_settings(bigint,jsonb),public.set_pledge_reminder_pause(bigint,boolean,text),public.manage_pledge_reminder_schedule(bigint,text,timestamptz,text) to authenticated;
grant execute on function public.recalculate_pledge_reminder_schedules(bigint,text) to service_role;
