-- Audit trail for how each check-in happened (QR scan, typed Pass ID, name search on the
-- check-in page, or the Guests page button). Name search is the weakest path -- staff pick a
-- person from a list instead of the guest presenting a pass -- so every successful check-in now
-- records its method and the staff member who did it.
--
-- One row per successful check-in increment (a Double pass checked in twice gets two rows), written
-- only by secure_guest_check_in inside the same transaction as the guests update, so the log can
-- never disagree with checked_in_count. Rejected scans (invalid / wrong_event / already checked in)
-- are not logged.
--
-- secure_guest_check_in gains check_in_method. Its signature changes again, so it is dropped and
-- recreated in one transaction. The parameter defaults to null (logged as 'unknown') so the
-- currently deployed frontend keeps working until the new build is live.
--
-- Both foreign keys cascade, so the log never blocks permanent event/guest deletion and the
-- deletion functions need no changes.
--
-- Deliberately not applied automatically.

begin;

create table public.guest_check_in_log (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  guest_id bigint not null references public.guests(id) on delete cascade,
  method text not null check (method in ('qr', 'event_pass', 'name_search', 'guest_list', 'unknown')),
  checked_in_count_after integer not null,
  checked_in_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index guest_check_in_log_event_idx on public.guest_check_in_log(event_id, created_at desc);
create index guest_check_in_log_guest_idx on public.guest_check_in_log(guest_id);

alter table public.guest_check_in_log enable row level security;

-- Read-only for admin/organizer. Nobody writes directly: the only writer is the security definer
-- secure_guest_check_in below.
create policy guest_check_in_log_admin_organizer_read on public.guest_check_in_log for select to authenticated
using (
  exists (
    select 1 from public.profiles
    where id = auth.uid() and is_active and role in ('admin', 'organizer')
  )
);

revoke all on public.guest_check_in_log from anon, authenticated, service_role;
revoke all on sequence public.guest_check_in_log_id_seq from anon, authenticated, service_role;

grant select on public.guest_check_in_log to authenticated;
grant select on public.guest_check_in_log to service_role;

drop function if exists public.secure_guest_check_in(text, text, bigint);

create function public.secure_guest_check_in(
  qr_token_input text default null::text,
  event_pass_id_input text default null::text,
  expected_event_id bigint default null::bigint,
  check_in_method text default null::text
)
 returns jsonb
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  guest_record public.guests%rowtype;
  normalized_qr_token text;
  normalized_qr_uuid uuid;
  normalized_event_pass_id text;
  normalized_method text;
  guest_event_title text;
  new_count integer;
begin
  if not public.has_active_role(
    array['admin','organizer','scanner']
  ) then
    raise exception 'You are not authorized to check in guests.'
      using errcode = '42501';
  end if;

  normalized_qr_token := nullif(trim(qr_token_input), '');
  normalized_event_pass_id := nullif(upper(trim(event_pass_id_input)), '');
  -- Client-reported, so anything unrecognised is stored as 'unknown' rather than failing the
  -- check-in at the door.
  normalized_method := lower(trim(coalesce(check_in_method, '')));
  if normalized_method not in ('qr', 'event_pass', 'name_search', 'guest_list') then
    normalized_method := 'unknown';
  end if;

  if normalized_qr_token is null and normalized_event_pass_id is null then
    return jsonb_build_object('success', false, 'status', 'invalid',
      'message', 'QR Code or Event Pass ID is required.', 'guest', null);
  end if;

  if normalized_qr_token is not null and normalized_event_pass_id is not null then
    return jsonb_build_object('success', false, 'status', 'invalid',
      'message', 'Use either QR Code or Event Pass ID.', 'guest', null);
  end if;

  if normalized_qr_token is not null then
    begin
      normalized_qr_uuid := normalized_qr_token::uuid;
    exception
      when invalid_text_representation then
        return jsonb_build_object('success', false, 'status', 'invalid',
          'message', 'Invalid QR Code', 'guest', null);
    end;
    select * into guest_record from public.guests
      where qr_token = normalized_qr_uuid for update;
  else
    select * into guest_record from public.guests
      where upper(event_pass_id) = normalized_event_pass_id for update;
  end if;

  if not found then
    return jsonb_build_object('success', false, 'status', 'invalid',
      'message', case when normalized_qr_token is not null
        then 'Invalid QR Code' else 'Invalid Event Pass ID' end,
      'guest', null);
  end if;

  -- Must run before the already-checked-in check and the update: a pass from another event is
  -- rejected outright and its row is never modified.
  if expected_event_id is not null and guest_record.event_id <> expected_event_id then
    select title into guest_event_title from public.events where id = guest_record.event_id;
    return jsonb_build_object('success', false, 'status', 'wrong_event',
      'message', format('Pass hii ni ya event nyingine: %s', coalesce(guest_event_title, 'event isiyojulikana')),
      'guest', to_jsonb(guest_record));
  end if;

  if guest_record.checked_in_count >= guest_record.allowed_guests then
    return jsonb_build_object('success', false, 'status', 'already_checked_in',
      'message', format('All %s guests already checked in', guest_record.allowed_guests),
      'guest', to_jsonb(guest_record));
  end if;

  new_count := guest_record.checked_in_count + 1;

  update public.guests set
    checked_in_count = new_count,
    checked_in_at = coalesce(checked_in_at, now()),
    last_checked_in_at = now(),
    status = case when new_count >= allowed_guests then 'checked_in' else 'partially_checked_in' end
    where id = guest_record.id returning * into guest_record;

  insert into public.guest_check_in_log (event_id, guest_id, method, checked_in_count_after, checked_in_by)
    values (guest_record.event_id, guest_record.id, normalized_method, new_count, auth.uid());

  return jsonb_build_object(
    'success', true,
    'status', guest_record.status,
    'message', format('%s of %s guests checked in', new_count, guest_record.allowed_guests),
    'guest', to_jsonb(guest_record)
  );
end;
$function$;

-- A dropped function loses its grants; only signed-in users may call it (the role check inside
-- then restricts it to admin/organizer/scanner).
revoke execute on function public.secure_guest_check_in(text, text, bigint, text) from public, anon;
grant execute on function public.secure_guest_check_in(text, text, bigint, text) to authenticated;

-- Refresh PostgREST's schema cache so the new 4-argument signature is callable immediately.
notify pgrst, 'reload schema';

commit;
