-- Financial automation and receipt verification. Do not apply automatically.

create table public.finance_receipt_verifications (
  payment_id bigint primary key references public.pledge_payments(id) on delete restrict,
  token_hash text not null unique check (token_hash ~ '^[a-f0-9]{64}$'),
  issued_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index finance_receipt_verifications_hash on public.finance_receipt_verifications(token_hash);

create table public.event_finance_automation_settings (
  event_id bigint primary key references public.events(id) on delete restrict,
  reminders_enabled boolean not null default false,
  reminder_channel text not null default 'sms' check (reminder_channel in ('sms','whatsapp','both')),
  reminder_frequency text not null default 'manual' check (reminder_frequency in ('manual','weekly','custom')),
  custom_interval_days integer check (custom_interval_days between 1 and 365),
  stop_after_completion boolean not null default true,
  stop_after_event_date boolean not null default true,
  allow_after_event_date boolean not null default false,
  next_reminder_at timestamptz,
  reminder_cooldown_hours integer not null default 24 check (reminder_cooldown_hours between 1 and 720),
  owner_summary_phone text,
  daily_summary_enabled boolean not null default false,
  daily_summary_channel text not null default 'sms' check (daily_summary_channel in ('sms','whatsapp','both')),
  daily_summary_time time not null default '18:00',
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (reminder_frequency <> 'custom' or custom_interval_days is not null),
  check (owner_summary_phone is null or owner_summary_phone ~ '^255[67][0-9]{8}$')
);

create table public.finance_automation_delivery_logs (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete restrict,
  delivery_type text not null check (delivery_type in ('daily_summary')),
  channel text not null check (channel in ('sms','whatsapp')),
  recipient_phone text not null,
  message_body text not null,
  delivery_status text not null check (delivery_status in ('queued','sent','failed')),
  provider_message_id text,
  error_message text,
  idempotency_key text not null unique,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);
create index finance_automation_delivery_event_created
on public.finance_automation_delivery_logs(event_id,created_at desc);

create trigger finance_receipt_verifications_updated_at
before update on public.finance_receipt_verifications
for each row execute function public.set_finance_updated_at();
create trigger event_finance_automation_settings_updated_at
before update on public.event_finance_automation_settings
for each row execute function public.set_finance_updated_at();

alter table public.finance_receipt_verifications enable row level security;
alter table public.event_finance_automation_settings enable row level security;
alter table public.finance_automation_delivery_logs enable row level security;

create policy finance_receipt_verifications_select on public.finance_receipt_verifications
for select to authenticated using (
  exists (
    select 1 from public.pledge_payments pay
    join public.event_pledges pledge on pledge.id=pay.pledge_id
    where pay.id=payment_id and public.can_manage_event_finance(pledge.event_id)
  )
);
create policy finance_automation_settings_manage on public.event_finance_automation_settings
for all to authenticated
using (public.can_manage_event_finance(event_id))
with check (public.can_manage_event_finance(event_id));
create policy finance_automation_delivery_select on public.finance_automation_delivery_logs
for select to authenticated using (public.can_manage_event_finance(event_id));

revoke all on public.event_finance_automation_settings from anon,authenticated,service_role;
revoke all on public.finance_receipt_verifications from anon,authenticated,service_role;
revoke all on public.finance_automation_delivery_logs from anon,authenticated,service_role;
revoke all on sequence public.finance_automation_delivery_logs_id_seq from anon,authenticated,service_role;

grant select,insert,update on public.event_finance_automation_settings to authenticated;
grant select on public.finance_receipt_verifications to authenticated;
grant select on public.finance_automation_delivery_logs to authenticated;

-- The cron reads and advances reminder settings, writes delivery logs, records
-- reminder attempts/audits, and reads only the event/accounting data it needs.
grant select,update on public.event_finance_automation_settings to service_role;
grant select,insert,update on public.finance_automation_delivery_logs to service_role;
grant select on public.events,public.event_pledges,public.pledge_payments to service_role;
grant select on public.event_pledge_financial_summary to service_role;
grant select,insert,update on public.pledge_reminders to service_role;
grant insert on public.finance_audit_logs to service_role;
grant usage,select on sequence public.finance_automation_delivery_logs_id_seq to service_role;
grant usage,select on sequence public.pledge_reminders_id_seq to service_role;
grant usage,select on sequence public.finance_audit_logs_id_seq to service_role;

create or replace function public.is_valid_receipt_token_hash(supplied_token_hash text)
returns boolean language sql immutable set search_path=pg_catalog as $$
  select supplied_token_hash is not null and supplied_token_hash ~ '^[a-f0-9]{64}$';
$$;
revoke all on function public.is_valid_receipt_token_hash(text) from public;

create or replace function public.finance_receipt_json(target_payment_id bigint)
returns jsonb language sql stable security definer set search_path=public,auth,pg_catalog as $$
  select jsonb_build_object(
    'receipt_number',pay.receipt_number,
    'event_name',event.title,
    'contributor_name',pledge.full_name,
    'contributor_phone',pledge.phone,
    'pledged_amount',pledge.pledged_amount,
    'payment_amount',pay.amount,
    'total_paid',coalesce((
      select sum(p2.amount) from public.pledge_payments p2
      where p2.pledge_id=pledge.id and p2.voided_at is null
    ),0),
    'remaining_balance',greatest(pledge.pledged_amount-coalesce((
      select sum(p3.amount) from public.pledge_payments p3
      where p3.pledge_id=pledge.id and p3.voided_at is null
    ),0),0),
    'payment_date',pay.payment_date,
    'payment_method',pay.payment_method,
    'payment_reference',pay.payment_reference,
    'recorded_by',coalesce(profile.full_name,case when pay.recorded_by is null then 'Committee organiser' else 'Smart Event Pass user' end),
    'payment_status',case when pay.voided_at is null then 'valid' else 'voided' end
  )
  from public.pledge_payments pay
  join public.event_pledges pledge on pledge.id=pay.pledge_id
  join public.events event on event.id=pledge.event_id
  left join public.profiles profile on profile.id=pay.recorded_by
  where pay.id=target_payment_id;
$$;
revoke all on function public.finance_receipt_json(bigint) from public;

create or replace function public.issue_receipt_verification(
  target_receipt_number text,supplied_token_hash text
) returns jsonb language plpgsql security definer set search_path=public,auth,pg_catalog as $$
declare pay public.pledge_payments%rowtype; target_event_id bigint;
begin
  if not public.is_valid_receipt_token_hash(supplied_token_hash) then raise exception 'Receipt not found'; end if;
  select payment.* into pay
  from public.pledge_payments payment
  where payment.receipt_number=target_receipt_number
  for update of payment;
  if not found then raise exception 'Receipt not found'; end if;
  select pledge.event_id into target_event_id
  from public.event_pledges pledge
  where pledge.id=pay.pledge_id;
  if target_event_id is null or not public.can_manage_event_finance(target_event_id)
  then raise exception 'Receipt not found'; end if;
  insert into public.finance_receipt_verifications(payment_id,token_hash,issued_by)
  values(pay.id,supplied_token_hash,auth.uid())
  on conflict(payment_id) do update set token_hash=excluded.token_hash,issued_by=auth.uid(),updated_at=now();
  return public.finance_receipt_json(pay.id);
end;
$$;

create or replace function public.record_pledge_payment_with_verification(
  target_pledge_id bigint,payment_amount numeric,paid_on date,method text,
  reference text,payment_provider text,payment_notes text,supplied_receipt_token_hash text
) returns jsonb language plpgsql security definer set search_path=public,auth,pg_catalog as $$
declare pledge public.event_pledges%rowtype; paid numeric; counter_value bigint;
  receipt_number text; payment_id bigint; pledge_summary jsonb;
begin
  if not public.is_valid_receipt_token_hash(supplied_receipt_token_hash) then raise exception 'Invalid receipt token'; end if;
  if payment_amount is null or payment_amount<=0 or method not in ('cash','mobile_money','bank','card','other')
  then raise exception 'Invalid payment'; end if;
  select * into pledge from public.event_pledges where id=target_pledge_id for update;
  if not found or not public.can_manage_event_finance(pledge.event_id) then raise exception 'Not authorized'; end if;
  if pledge.cancelled_at is not null then raise exception 'Cancelled pledges cannot receive payments'; end if;
  select coalesce(sum(amount),0) into paid from public.pledge_payments
  where pledge_id=pledge.id and voided_at is null;
  if paid+payment_amount>pledge.pledged_amount then raise exception 'Payment exceeds the remaining pledge balance'; end if;
  insert into public.finance_receipt_counters(receipt_year,last_value)
  values(extract(year from coalesce(paid_on,current_date))::int,1)
  on conflict(receipt_year) do update
    set last_value=public.finance_receipt_counters.last_value+1,updated_at=now()
  returning last_value into counter_value;
  receipt_number:='SEP-PAY-'||extract(year from coalesce(paid_on,current_date))::int||'-'||lpad(counter_value::text,6,'0');
  insert into public.pledge_payments(pledge_id,receipt_number,amount,currency_code,payment_date,
    payment_method,payment_reference,provider,notes,recorded_by)
  values(pledge.id,receipt_number,payment_amount,pledge.currency_code,coalesce(paid_on,current_date),
    method,nullif(btrim(reference),''),nullif(btrim(payment_provider),''),nullif(btrim(payment_notes),''),auth.uid())
  returning id into payment_id;
  insert into public.finance_receipt_verifications(payment_id,token_hash,issued_by)
  values(payment_id,supplied_receipt_token_hash,auth.uid());
  -- Earlier Financial Suite migrations define no audit trigger on
  -- pledge_payments or finance_audit_logs. This is the single authoritative
  -- payment_recorded audit entry for this transactional wrapper.
  insert into public.finance_audit_logs(event_id,pledge_id,payment_id,actor_type,actor_user_id,action,new_data)
  values(pledge.event_id,pledge.id,payment_id,'authenticated_user',auth.uid(),'payment_recorded',
    jsonb_build_object('amount',payment_amount,'receipt_number',receipt_number,'payment_method',method));
  select to_jsonb(summary) into pledge_summary from public.event_pledge_financial_summary summary where summary.id=pledge.id;
  return jsonb_build_object('receipt',public.finance_receipt_json(payment_id),'pledge',pledge_summary);
end;
$$;

create or replace function public.organiser_issue_receipt_verification(
  supplied_organiser_token_hash text,target_receipt_number text,supplied_receipt_token_hash text
) returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$
declare link public.event_finance_access_links%rowtype; pay public.pledge_payments%rowtype;
begin
  if not public.is_valid_organiser_token_hash(supplied_organiser_token_hash)
    or not public.is_valid_receipt_token_hash(supplied_receipt_token_hash)
  then raise exception 'Invalid access link'; end if;
  select * into link from public.event_finance_access_links
  where token_hash=supplied_organiser_token_hash for update;
  if not found or not public.finance_link_is_valid(link,'view_payment_history') then raise exception 'Access denied'; end if;
  select payment.* into pay from public.pledge_payments payment
  join public.event_pledges pledge on pledge.id=payment.pledge_id
  where payment.receipt_number=target_receipt_number and pledge.event_id=link.event_id
  for update of payment;
  if not found then raise exception 'Receipt not found'; end if;
  if not public.finance_link_is_valid(link,'view_payment_history') then raise exception 'Access denied'; end if;
  insert into public.finance_receipt_verifications(payment_id,token_hash,issued_by)
  values(pay.id,supplied_receipt_token_hash,null)
  on conflict(payment_id) do update set token_hash=excluded.token_hash,issued_by=null,updated_at=now();
  update public.event_finance_access_links set last_used_at=now() where id=link.id;
  return public.finance_receipt_json(pay.id);
exception when others then
  if sqlerrm in ('Invalid access link','Access denied','Receipt not found') then raise exception '%',sqlerrm; end if;
  raise exception 'Access denied';
end;
$$;

create or replace function public.verify_finance_receipt(supplied_token_hash text)
returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$
declare payment_id bigint; receipt jsonb;
begin
  if not public.is_valid_receipt_token_hash(supplied_token_hash) then
    return jsonb_build_object('verification_status','invalid');
  end if;
  select verification.payment_id into payment_id from public.finance_receipt_verifications verification
  where verification.token_hash=supplied_token_hash;
  if not found then return jsonb_build_object('verification_status','invalid'); end if;
  select jsonb_build_object(
    'verification_status','verified',
    'receipt_number',payment.receipt_number,
    'contributor',pledge.full_name,
    'event',event.title,
    'amount_paid',payment.amount,
    'currency_code',payment.currency_code,
    'payment_date',payment.payment_date,
    'payment_method',payment.payment_method,
    'status',case when payment.voided_at is null then 'valid' else 'voided' end
  ) into receipt
  from public.pledge_payments payment
  join public.event_pledges pledge on pledge.id=payment.pledge_id
  join public.events event on event.id=pledge.event_id
  where payment.id=payment_id;
  return coalesce(receipt,jsonb_build_object('verification_status','invalid'));
exception when others then
  return jsonb_build_object('verification_status','invalid');
end;
$$;

revoke all on function public.issue_receipt_verification(text,text) from public;
revoke all on function public.record_pledge_payment_with_verification(bigint,numeric,date,text,text,text,text,text) from public;
revoke all on function public.organiser_issue_receipt_verification(text,text,text) from public;
revoke all on function public.verify_finance_receipt(text) from public;
grant execute on function public.issue_receipt_verification(text,text) to authenticated;
grant execute on function public.record_pledge_payment_with_verification(bigint,numeric,date,text,text,text,text,text) to authenticated;
grant execute on function public.organiser_issue_receipt_verification(text,text,text) to anon;
grant execute on function public.verify_finance_receipt(text) to anon;
