"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { getClosingReport, previewDailySummary, type AuthoritativeDailySummary, type ClosingReport } from "@/services/financialAutomationService";
import type { FinancialPledge, PledgePayment } from "@/services/financialSuiteService";
import type { FinanceReceipt } from "@/services/receiptMessageService";
import { formatTzs } from "@/services/pledgeMessageService";

type IssuedReceipt={receipt:FinanceReceipt;verificationUrl:string};

export default function FinancialPaymentsTab({eventId,pledges,issueReceipt,onViewReceipt,onEdit,onVoid}:{eventId:number;pledges:FinancialPledge[];issueReceipt:(receiptNumber:string)=>Promise<IssuedReceipt>;onViewReceipt:(issued:IssuedReceipt)=>void;onEdit:(pledge:FinancialPledge,payment:PledgePayment)=>void;onVoid:(pledge:FinancialPledge,payment:PledgePayment)=>void}) {
  const [report,setReport]=useState<ClosingReport|null>(null);const [filter,setFilter]=useState<"all"|"valid"|"voided">("all");const [selectedDate,setSelectedDate]=useState(new Date().toISOString().slice(0,10));const [daily,setDaily]=useState<AuthoritativeDailySummary|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState("");
  const load=useCallback(async()=>{try{setError("");setReport(await getClosingReport(eventId));}catch(err){setError(err instanceof Error?err.message:"Payments could not be loaded.");}},[eventId]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  const contributors=useMemo(()=>new Map(pledges.map(item=>[item.id,item])),[pledges]);
  const payments=useMemo(()=>(report?.payments??[]).filter(payment=>filter==="all"||(filter==="voided"?Boolean(payment.voided_at):!payment.voided_at)).sort((a,b)=>b.created_at.localeCompare(a.created_at)),[filter,report]);
  async function receiptAction(payment:PledgePayment,action:"view"|"copy"){try{setBusy(`${action}-${payment.id}`);const issued=await issueReceipt(payment.receipt_number);if(action==="view")onViewReceipt(issued);else{await navigator.clipboard.writeText(issued.verificationUrl);setNotice("Verification link copied.");}}catch(err){setError(err instanceof Error?err.message:"Receipt could not be prepared.");}finally{setBusy("");}}
  async function preview(){try{setBusy("daily");setDaily(await previewDailySummary(eventId,selectedDate));}catch(err){setError(err instanceof Error?err.message:"Daily summary preview failed.");}finally{setBusy("");}}
  return <div className="space-y-6">{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-700">{notice}</p>}
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="text-xl font-bold">Recent Payments</h2><p className="text-sm text-slate-500">Valid and voided transactions are shown distinctly.</p></div><div className="flex rounded-xl bg-slate-100 p-1">{(["all","valid","voided"] as const).map(value=><button key={value} onClick={()=>setFilter(value)} className={`min-h-10 rounded-lg px-3 text-sm font-semibold capitalize ${filter===value?"bg-white text-slate-900 shadow-sm":"text-slate-600"}`}>{value}</button>)}</div></div>
      {!report?<p className="p-8 text-center text-slate-500">Loading payments…</p>:!payments.length?<p className="p-8 text-center text-slate-500">No payments match this filter.</p>:<><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{["Contributor","Amount","Receipt","Payment date","Method","Status","Actions"].map(label=><th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y">{payments.map(payment=>{const pledge=contributors.get(payment.pledge_id);return <tr key={payment.id} className={payment.voided_at?"bg-red-50/50":""}><td className="px-4 py-3 font-semibold">{pledge?.full_name??"Contributor"}</td><td className="px-4 py-3">{formatTzs(payment.amount)}</td><td className="px-4 py-3">{payment.receipt_number}</td><td className="px-4 py-3">{payment.payment_date}</td><td className="px-4 py-3 capitalize">{payment.payment_method.replaceAll("_"," ")}</td><td className={`px-4 py-3 font-semibold ${payment.voided_at?"text-red-700":"text-emerald-700"}`}>{payment.voided_at?"Voided":"Valid"}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-3"><button disabled={busy===`view-${payment.id}`} onClick={()=>void receiptAction(payment,"view")} className="font-semibold text-blue-700">View / PDF</button><button onClick={()=>void receiptAction(payment,"copy")} className="font-semibold text-slate-700">Copy verification link</button>{pledge&&!payment.voided_at&&<><button onClick={()=>onEdit(pledge,payment)} className="font-semibold text-amber-700">Edit</button><button onClick={()=>onVoid(pledge,payment)} className="font-semibold text-red-700">Void</button></>}</div></td></tr>})}</tbody></table></div>
      <div className="grid gap-3 p-3 md:hidden">{payments.map(payment=>{const pledge=contributors.get(payment.pledge_id);return <article key={payment.id} className={`rounded-xl border p-4 ${payment.voided_at?"border-red-200 bg-red-50/50":""}`}><div className="flex justify-between gap-3"><div><h3 className="font-bold">{pledge?.full_name??"Contributor"}</h3><p className="text-sm text-slate-500">{payment.receipt_number} · {payment.payment_date}</p></div><b>{formatTzs(payment.amount)}</b></div><p className={`mt-2 text-sm font-semibold ${payment.voided_at?"text-red-700":"text-emerald-700"}`}>{payment.voided_at?"Voided":"Valid"} · {payment.payment_method.replaceAll("_"," ")}</p><div className="mt-3 flex flex-wrap gap-3 text-sm"><button onClick={()=>void receiptAction(payment,"view")} className="font-semibold text-blue-700">View / PDF</button><button onClick={()=>void receiptAction(payment,"copy")} className="font-semibold">Copy link</button>{pledge&&!payment.voided_at&&<><button onClick={()=>onEdit(pledge,payment)} className="font-semibold text-amber-700">Edit</button><button onClick={()=>onVoid(pledge,payment)} className="font-semibold text-red-700">Void</button></>}</div></article>})}</div></>}</section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Daily Collection Summary</h2><div className="mt-3 flex flex-wrap gap-2"><input type="date" value={selectedDate} onChange={e=>{setSelectedDate(e.target.value);setDaily(null);}} className="rounded-xl border px-3 py-2"/><button disabled={busy==="daily"} onClick={()=>void preview()} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Generate preview</button></div>{daily&&<><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div>Collected<br/><b>{formatTzs(daily.summary.dailyCollected)}</b></div><div>Transactions<br/><b>{daily.summary.transactionCount}</b></div><div>Contributors who paid<br/><b>{daily.summary.contributorsCount}</b></div><div>Outstanding<br/><b>{formatTzs(daily.summary.outstandingBalance)}</b></div></div><pre className="mt-4 max-h-52 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-xs">{daily.message}</pre><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void navigator.clipboard.writeText(daily.message)} className="rounded-xl border px-3 py-2 text-sm font-semibold">Copy summary</button><button onClick={()=>setNotice(`WhatsApp preview:\n${daily.message}`)} className="rounded-xl border px-3 py-2 text-sm font-semibold">WhatsApp preview</button><button onClick={()=>setNotice(`SMS preview:\n${daily.message}`)} className="rounded-xl border px-3 py-2 text-sm font-semibold">SMS preview</button></div></>}</div>
      <div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Payment Methods</h2><p className="text-sm text-slate-500">Valid transactions only.</p><div className="mt-4 space-y-3">{report?.paymentMethods.length?report.paymentMethods.sort((a,b)=>b.amount-a.amount).map(item=><div key={item.method} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className="capitalize">{item.method.replaceAll("_"," ")}</span><b>{formatTzs(item.amount)}</b></div>):<p className="text-sm text-slate-500">No payment-method data yet.</p>}</div></div></section>
  </div>;
}
