"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { pdf } from "@react-pdf/renderer";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { exportClosingWorkbook, getClosingReport, type ClosingReport } from "@/services/financialAutomationService";
import { formatTzs } from "@/services/pledgeMessageService";
import FinancialClosingPDF from "../FinancialClosingPDF";

export default function FinancialReportsTab({eventId}:{eventId:number}) {
  const [report,setReport]=useState<ClosingReport|null>(null);const [range,setRange]=useState<7|30|0>(7);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{setError("");setReport(await getClosingReport(eventId));}catch(err){setError(err instanceof Error?err.message:"Report data could not be loaded.");}},[eventId]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  const trend=useMemo(()=>{if(!report)return[];if(!range)return report.trend;const cutoff=new Date();cutoff.setDate(cutoff.getDate()-range+1);return report.trend.filter(point=>new Date(`${point.date}T00:00:00`)>=cutoff);},[range,report]);
  async function downloadPdf(){if(!report)return;try{setBusy(true);const blob=await pdf(<FinancialClosingPDF report={report} generatedBy="Authenticated event manager"/>).toBlob();const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`${report.event.title.replace(/\W+/g,"_")}_Financial_Closing.pdf`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}finally{setBusy(false);}}
  if(error)return <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>;
  if(!report)return <p role="status" className="rounded-2xl bg-white p-8 text-center text-slate-500">Loading reports…</p>;
  const closingText=`${report.event.title} Financial Closing\nTotal Contributors: ${report.financial.totalContributors}\nPledged: ${formatTzs(report.financial.totalPledged)}\nCollected: ${formatTzs(report.financial.totalCollected)}\nOutstanding: ${formatTzs(report.financial.outstanding)}\nBudget: ${report.financial.target.budget===null?"Not set":formatTzs(report.financial.target.budget)}\nCollection: ${report.financial.percentage.toFixed(1)}%`;
  const top=[...report.pledges].filter(item=>item.calculated_status!=="cancelled").sort((a,b)=>Number(b.total_paid)-Number(a.total_paid)).slice(0,5);
  const outstanding=[...report.pledges].filter(item=>item.calculated_status!=="cancelled"&&Number(item.balance)>0).sort((a,b)=>Number(b.balance)-Number(a.balance)).slice(0,5);
  return <div className="space-y-6"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Financial Closing Report</h2><p className="text-sm text-slate-600">{report.event.title} · current financial position</p></div><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void downloadPdf()} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Download PDF</button><button onClick={()=>exportClosingWorkbook(report)} className="rounded-xl border px-4 py-2 text-sm font-semibold">Export Excel</button><button onClick={()=>window.print()} className="rounded-xl border px-4 py-2 text-sm font-semibold">Print</button><button onClick={()=>void navigator.clipboard.writeText(closingText)} className="rounded-xl border px-4 py-2 text-sm font-semibold">Copy summary</button></div></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Total contributors",report.financial.totalContributors],["Total pledged",formatTzs(report.financial.totalPledged)],["Total collected",formatTzs(report.financial.totalCollected)],["Outstanding",formatTzs(report.financial.outstanding)],["Event budget",report.financial.target.budget===null?"Not set":formatTzs(report.financial.target.budget)],["Remaining to budget",report.financial.target.remaining===null?"—":formatTzs(report.financial.target.remaining)],["Budget progress",report.financial.target.progress===null?"—":`${report.financial.target.progress.toFixed(1)}%`],["Pledge collection",`${report.financial.percentage.toFixed(1)}%`],["Deadline",report.financial.target.deadline??"No deadline"],["Guests",report.guestStats.totalGuests],["Invitations",report.guestStats.totalInvitations],["Valid transactions",report.financial.validTransactions],["Voided transactions",report.financial.voidedTransactions]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3 text-sm"><span className="text-slate-500">{label}</span><br/><b className="text-lg">{value}</b></div>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="text-xl font-bold">Collection Trend</h2><p className="text-sm text-slate-500">Valid transactions only</p></div><select value={range} onChange={e=>setRange(Number(e.target.value) as 7|30|0)} className="rounded-xl border px-3 py-2"><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={0}>Entire period</option></select></div><div className="mt-4 h-64">{trend.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tickFormatter={value=>`${Math.round(Number(value)/1000)}k`} tick={{fontSize:10}}/><Tooltip formatter={value=>formatTzs(String(value))}/><Area dataKey="amount" stroke="#059669" fill="#d1fae5"/></AreaChart></ResponsiveContainer>:<div className="flex h-full items-center justify-center rounded-xl bg-slate-50 text-slate-500">No collection data in this period.</div>}</div></div>
    <div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Status &amp; Methods</h2><div className="mt-4 grid grid-cols-2 gap-3">{[["Completed",report.financial.completed],["Partial",report.financial.partial],["Pending",report.financial.pending],["Cancelled",report.financial.cancelled]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3"><span className="text-sm text-slate-500">{label}</span><br/><b className="text-xl">{value}</b></div>)}</div><div className="mt-4 space-y-2">{report.paymentMethods.map(item=><div key={item.method} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span className="capitalize">{item.method.replaceAll("_"," ")}</span><b>{formatTzs(item.amount)}</b></div>)}</div></div></section>
    <section className="grid gap-6 lg:grid-cols-2">{[["Top contributors",top,"total_paid"],["Largest outstanding balances",outstanding,"balance"]].map(([title,rows,key])=><div key={String(title)} className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">{String(title)}</h2><div className="mt-4 space-y-2">{(rows as typeof top).length?(rows as typeof top).map((item,index)=><div key={item.id} className="flex justify-between gap-3 rounded-xl bg-slate-50 p-3 text-sm"><span>{index+1}. {item.full_name}</span><b>{formatTzs(item[key as "total_paid"|"balance"])}</b></div>):<p className="text-sm text-slate-500">No data available.</p>}</div></div>)}</section>
  </div>;
}
