"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import MessagePreviewDialog from "../reminders/MessagePreviewDialog";
import { cancelMeeting,getMeetings,previewMeetingInvitations,saveMeeting,sendMeetingInvitations,type Meeting,type MeetingAudience,type MeetingInvitationPreview,type ReminderChannel } from "@/services/financialAutomationService";
import type { FinancialPledge } from "@/services/financialSuiteService";

type DeliveryMode="whatsapp"|"sms"|"both";
type PreviewRow=MeetingInvitationPreview["rows"][number];
const emptyForm={title:"",meetingDate:"",meetingTime:"",venue:"",mapUrl:"",note:""};
const statusLabel=(value:string|null)=>({pledged:"Not Started",partial:"Partially Paid",completed:"Completed",missing_phone:"Missing Phone",invalid_phone:"Invalid Phone",provider_unavailable:"Provider Unavailable",already_sent:"Already Sent",in_progress:"In Progress"} as Record<string,string>)[value??""]??(value?value.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase()):"Not Sent");
function Badge({value}:{value:string}){const lower=value.toLowerCase(),style=lower.includes("failed")?"bg-red-50 text-red-700":lower.includes("ready")||lower.includes("delivered")||lower.includes("read")?"bg-emerald-50 text-emerald-700":lower.includes("missing")||lower.includes("invalid")||lower.includes("unavailable")||lower.includes("skipped")?"bg-amber-50 text-amber-800":"bg-stone-100 text-slate-700";return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${style}`}>{value}</span>}

export default function MeetingInvitationsPanel({eventId,pledges}:{eventId:number;pledges:FinancialPledge[]}){
  const [meetings,setMeetings]=useState<Meeting[]>([]),[meetingId,setMeetingId]=useState<number|null>(null),[form,setForm]=useState(emptyForm);
  const [audience,setAudience]=useState<MeetingAudience>("all"),[deliveryMode,setDeliveryMode]=useState<DeliveryMode>("whatsapp"),[manualIds,setManualIds]=useState<Set<number>>(new Set());
  const [preview,setPreview]=useState<MeetingInvitationPreview|null>(null),[selected,setSelected]=useState<PreviewRow|null>(null),[confirmed,setConfirmed]=useState(false);
  const [query,setQuery]=useState(""),[paymentFilter,setPaymentFilter]=useState("all"),[deliveryFilter,setDeliveryFilter]=useState("all"),[manualQuery,setManualQuery]=useState("");
  const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[warning,setWarning]=useState("");
  const [meetingDirty,setMeetingDirty]=useState(false);
  const channels=useMemo<ReminderChannel[]>(()=>deliveryMode==="both"?["whatsapp","sms"]:[deliveryMode],[deliveryMode]);
  const activePledges=useMemo(()=>pledges.filter(item=>item.calculated_status!=="cancelled"),[pledges]);
  const manualVisible=useMemo(()=>activePledges.filter(item=>`${item.full_name} ${item.normalized_phone??item.phone??""}`.toLowerCase().includes(manualQuery.toLowerCase())),[activePledges,manualQuery]);
  function invalidate(){setPreview(null);setConfirmed(false);setSelected(null)}
  function updateForm(key:keyof typeof emptyForm,value:string){setForm(current=>({...current,[key]:value}));setMeetingDirty(true);invalidate()}
  const loadMeetings=useCallback(async(selectId?:number)=>{const rows=await getMeetings(eventId);setMeetings(rows);if(selectId)setMeetingId(selectId)},[eventId]);
  useEffect(()=>{const timer=setTimeout(()=>{void loadMeetings().catch(err=>setError(err instanceof Error?err.message:"Meetings could not be loaded."))},0);return()=>clearTimeout(timer)},[loadMeetings]);
  function chooseMeeting(value:number){const meeting=meetings.find(item=>item.id===value);setMeetingId(value);if(meeting)setForm({title:meeting.title,meetingDate:meeting.meeting_date,meetingTime:meeting.meeting_time.slice(0,5),venue:meeting.venue,mapUrl:meeting.map_url??"",note:meeting.note??""});setMeetingDirty(false);invalidate()}
  async function persist(){try{setBusy(true);setError("");const result=await saveMeeting(eventId,{meetingId:meetingId??undefined,...form});await loadMeetings(result.meeting.id);chooseMeetingFromResult(result.meeting);setNotice("Meeting details saved.")}catch(err){setError(err instanceof Error?err.message:"Meeting could not be saved.")}finally{setBusy(false)}}
  function chooseMeetingFromResult(meeting:Meeting){setMeetingId(meeting.id);setForm({title:meeting.title,meetingDate:meeting.meeting_date,meetingTime:meeting.meeting_time.slice(0,5),venue:meeting.venue,mapUrl:meeting.map_url??"",note:meeting.note??""});setMeetingDirty(false);invalidate()}
  async function cancelSelected(){if(!meetingId||!window.confirm("Cancel this meeting? Existing delivery history will be preserved and no further invitations can be sent."))return;try{setBusy(true);const result=await cancelMeeting(eventId,meetingId);await loadMeetings(result.meeting.id);chooseMeetingFromResult(result.meeting);setWarning("Meeting cancelled. Its invitation history remains available.")}catch(err){setError(err instanceof Error?err.message:"Meeting could not be cancelled.")}finally{setBusy(false)}}
  const request={meetingId:meetingId??0,audience,manualPledgeIds:[...manualIds],channels};
  async function loadRecipients(preserveFeedback=false){if(!meetingId){setError("Select or create a meeting first.");return}if(meetingDirty){setError("Save the meeting changes before loading recipients.");return}try{setBusy(true);if(!preserveFeedback){setError("");setWarning("")}setPreview(await previewMeetingInvitations(eventId,request));setConfirmed(false);setPage(1)}catch(err){setError(err instanceof Error?err.message:"Meeting recipients could not be loaded.")}finally{setBusy(false)}}
  async function send(){if(!preview)return;try{setBusy(true);setError("");setNotice("");setWarning("");const result=await sendMeetingInvitations(eventId,request),totals=`${result.sent} sent, ${result.failed} failed, ${result.skipped} skipped.`;if(result.failed>0)setError(`Meeting invitations: ${totals} ${result.errors.join(" ")}`);else if(result.sent>0)setNotice(`Meeting invitations: ${totals}`);else setWarning(`Meeting invitations not sent: ${result.errors.join(" ")||totals}`);setConfirmed(false);await loadRecipients(true)}catch(err){setError(err instanceof Error?err.message:"Meeting invitations could not be sent.");setConfirmed(false)}finally{setBusy(false)}}
  const grouped=useMemo(()=>{const map=new Map<number,PreviewRow>();(preview?.rows??[]).forEach(row=>{if(!map.has(row.pledgeId))map.set(row.pledgeId,row)});return [...map.values()]},[preview]);
  const channelRow=useCallback((pledgeId:number,channel:ReminderChannel)=>(preview?.rows??[]).find(item=>item.pledgeId===pledgeId&&item.channel===channel),[preview]);
  const channelStatus=useCallback((pledgeId:number,channel:ReminderChannel)=>{const row=channelRow(pledgeId,channel);return row?.deliveryStatus?statusLabel(row.deliveryStatus):row?.eligible?"Ready":statusLabel(row?.skippedReason??null)},[channelRow]);
  const rows=useMemo(()=>grouped.filter(row=>`${row.contributor} ${row.phone??""}`.toLowerCase().includes(query.toLowerCase())&&(paymentFilter==="all"||row.paymentStatus===paymentFilter)&&(deliveryFilter==="all"||channels.some(channel=>{const item=channelRow(row.pledgeId,channel);return channelStatus(row.pledgeId,channel).toLowerCase().replaceAll(" ","_")===deliveryFilter||item?.skippedReason===deliveryFilter}))),[grouped,query,paymentFilter,deliveryFilter,channels,channelStatus,channelRow]);
  const pageCount=Math.max(1,Math.ceil(rows.length/pageSize)),safePage=Math.min(page,pageCount),pageRows=rows.slice((safePage-1)*pageSize,safePage*pageSize);
  const eligibleRows=(preview?.rows??[]).filter(row=>row.eligible),eligibleContributors=new Set(eligibleRows.map(row=>row.pledgeId)).size;
  const uniqueCount=(predicate:(row:PreviewRow)=>boolean)=>new Set((preview?.rows??[]).filter(predicate).map(row=>row.pledgeId)).size;
  const selectedMeeting=meetings.find(item=>item.id===meetingId),today=new Date().toISOString().slice(0,10);

  return <section className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6">
    <h2 className="text-xl font-bold">Meeting Invitations</h2><p className="mt-1 text-sm text-slate-600">Create a meeting, choose contributors, review recipients, then confirm sending.</p>
    {error&&<p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}{warning&&<p role="status" className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{warning}</p>}
    <div className="mt-5 grid gap-4 xl:grid-cols-[.8fr_1.4fr]">
      <div><label className="text-sm font-semibold">Existing meeting<select value={meetingId??""} onChange={event=>{if(event.target.value)chooseMeeting(Number(event.target.value));else{setMeetingId(null);setForm(emptyForm);invalidate()}}} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal"><option value="">Create new meeting</option>{meetings.map(meeting=><option key={meeting.id} value={meeting.id}>{meeting.meeting_date} · {meeting.title} · {meeting.status}</option>)}</select></label><div className="mt-3 space-y-2">{meetings.slice(0,6).map(meeting=><button key={meeting.id} type="button" onClick={()=>chooseMeeting(meeting.id)} className={`w-full rounded-xl border p-3 text-left text-sm ${meeting.id===meetingId?"border-emerald-500 bg-emerald-50":"border-stone-200"}`}><span className="flex justify-between gap-2"><b>{meeting.title}</b><Badge value={meeting.status}/></span><span className="mt-1 block text-slate-500">{meeting.meeting_date<today?"Past":"Upcoming"} · {meeting.meeting_date} {meeting.meeting_time.slice(0,5)}</span></button>)}</div></div>
      <fieldset><legend className="font-bold">Meeting Details</legend><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Meeting title" value={form.title} onChange={value=>updateForm("title",value)}/><Field label="Meeting date" type="date" value={form.meetingDate} onChange={value=>updateForm("meetingDate",value)}/><Field label="Meeting time" type="time" value={form.meetingTime} onChange={value=>updateForm("meetingTime",value)}/><Field label="Venue" value={form.venue} onChange={value=>updateForm("venue",value)}/><Field label="Google Maps/location URL (optional)" type="url" value={form.mapUrl} onChange={value=>updateForm("mapUrl",value)}/><Field label="Note (optional)" value={form.note} onChange={value=>updateForm("note",value)}/></div><div className="mt-3 flex gap-2"><button type="button" disabled={busy||selectedMeeting?.status==="cancelled"} onClick={()=>void persist()} className="min-h-10 rounded-lg bg-slate-900 px-4 text-sm font-bold text-white disabled:opacity-40">{meetingId?"Save Meeting":"Create Meeting"}</button>{selectedMeeting&&selectedMeeting.status!=="cancelled"&&<button type="button" disabled={busy} onClick={()=>void cancelSelected()} className="min-h-10 rounded-lg border border-red-200 px-4 text-sm font-bold text-red-700">Cancel Meeting</button>}</div></fieldset>
    </div>
    <div className="mt-6 grid gap-4 lg:grid-cols-2"><fieldset><legend className="font-bold">Audience</legend><select value={audience} onChange={event=>{setAudience(event.target.value as MeetingAudience);invalidate()}} className="mt-2 min-h-11 w-full rounded-xl border px-3"><option value="all">All contributors</option><option value="pledged">Not Started</option><option value="partial">Partially Paid</option><option value="completed">Completed</option><option value="manual">Manual Selection</option></select>{audience==="manual"&&<div className="mt-3 rounded-xl border p-3"><div className="flex flex-wrap items-center gap-2"><input value={manualQuery} onChange={event=>setManualQuery(event.target.value)} placeholder="Search contributors" className="min-h-10 flex-1 rounded-lg border px-3 text-sm"/><button type="button" onClick={()=>{setManualIds(current=>new Set([...current,...manualVisible.map(item=>item.id)]));invalidate()}} className="rounded-lg border px-3 py-2 text-xs font-bold">Select visible</button><button type="button" onClick={()=>{setManualIds(new Set());invalidate()}} className="rounded-lg border px-3 py-2 text-xs font-bold">Clear selection</button></div><p className="mt-2 text-xs font-semibold">{manualIds.size} contributors selected</p><div className="mt-2 max-h-52 overflow-auto">{manualVisible.map(item=><label key={item.id} className="flex items-center gap-2 border-t py-2 text-sm first:border-t-0"><input type="checkbox" checked={manualIds.has(item.id)} onChange={event=>{setManualIds(current=>{const next=new Set(current);if(event.target.checked)next.add(item.id);else next.delete(item.id);return next});invalidate()}}/><span className="flex-1">{item.full_name}</span><span className="text-xs text-slate-500">{statusLabel(item.calculated_status)} · {item.normalized_phone??"No phone"}</span></label>)}</div></div>}</fieldset><fieldset><legend className="font-bold">Delivery Channel</legend><div className="mt-2 inline-flex rounded-xl bg-stone-100 p-1">{(["whatsapp","sms","both"] as DeliveryMode[]).map(value=><button key={value} type="button" onClick={()=>{setDeliveryMode(value);invalidate()}} className={`min-h-10 rounded-lg px-4 text-sm font-bold ${deliveryMode===value?"bg-white shadow-sm":"text-slate-600"}`}>{value==="both"?"Both":value==="sms"?"SMS":"WhatsApp"}</button>)}</div><p className="mt-2 text-sm text-slate-600">Send Now is available in V1. Exact scheduled sending requires Make automation.</p></fieldset></div>
    <div className="mt-5 flex flex-wrap items-center gap-2"><button type="button" disabled={busy||!meetingId||(audience==="manual"&&!manualIds.size)} onClick={()=>void loadRecipients()} className="min-h-11 rounded-xl border px-4 font-bold disabled:opacity-40">Load Recipients</button>{preview&&<><label className="flex min-h-11 items-center gap-2 rounded-xl border px-3 text-sm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Confirm sending to {eligibleContributors} contributors ({eligibleRows.length} messages)</label><button type="button" disabled={busy||!confirmed||!eligibleRows.length||preview.meeting.status==="cancelled"} onClick={()=>void send()} className="min-h-11 rounded-xl bg-emerald-600 px-4 font-bold text-white disabled:opacity-40">Send Meeting Invitations</button></>}</div>
    {preview&&<><div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-6">{[["Total Audience",grouped.length],["Ready Contributors",eligibleContributors],["Eligible Messages",eligibleRows.length],["Already Sent",uniqueCount(row=>["sent","delivered","read"].includes(row.deliveryStatus??""))],["Failed",uniqueCount(row=>row.deliveryStatus==="failed")],["Missing/Invalid Phone",uniqueCount(row=>["missing_phone","invalid_phone"].includes(row.skippedReason??""))]].map(([label,value])=><article key={label} className="rounded-xl border bg-stone-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-bold tabular-nums">{value}</p></article>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{channels.map(channel=><p key={channel} className={`rounded-xl p-3 text-sm ${preview.provider[channel].configured?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-900"}`}><b>{channel==="sms"?"SMS":"WhatsApp"}:</b> {preview.provider[channel].message}</p>)}</div>
      <div className="mt-4 grid gap-3 lg:grid-cols-3"><Field label="Search name or phone" value={query} onChange={value=>{setQuery(value);setPage(1)}}/><label className="text-sm font-semibold">Payment Status<select value={paymentFilter} onChange={event=>{setPaymentFilter(event.target.value);setPage(1)}} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal"><option value="all">All</option><option value="pledged">Not Started</option><option value="partial">Partially Paid</option><option value="completed">Completed</option></select></label><label className="text-sm font-semibold">Delivery Status<select value={deliveryFilter} onChange={event=>{setDeliveryFilter(event.target.value);setPage(1)}} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal"><option value="all">Any Status</option>{["ready","queued","processing","sent","delivered","read","failed","already_sent","missing_phone","invalid_phone"].map(value=><option key={value} value={value}>{statusLabel(value)}</option>)}</select></label></div>
      <div className="mt-4 overflow-hidden rounded-xl border"><div className="hidden grid-cols-[1.3fr_1fr_1fr_1fr_1fr_1fr_auto] gap-2 bg-stone-100 p-3 text-xs font-bold lg:grid">{["Contributor","Phone","Payment Status","WhatsApp","SMS","Eligibility","Action"].map(label=><span key={label}>{label}</span>)}</div>{pageRows.map(row=>{const eligible=channels.some(channel=>channelRow(row.pledgeId,channel)?.eligible);return <article key={row.pledgeId} className="border-t p-3 first:border-t-0 lg:grid lg:grid-cols-[1.3fr_1fr_1fr_1fr_1fr_1fr_auto] lg:items-center lg:gap-2"><div><b>{row.contributor}</b><p className="text-xs text-slate-500 lg:hidden">{row.phone??"No phone"}</p></div><span className="hidden text-sm lg:block">{row.phone??"No phone"}</span><Badge value={statusLabel(row.paymentStatus)}/><div className="mt-2 flex flex-wrap gap-2 lg:contents"><Badge value={`WhatsApp: ${channelStatus(row.pledgeId,"whatsapp")}`}/><Badge value={`SMS: ${channelStatus(row.pledgeId,"sms")}`}/><Badge value={eligible?"Ready":statusLabel(channels.map(channel=>channelRow(row.pledgeId,channel)?.skippedReason).find(Boolean)??null)}/></div><button type="button" onClick={()=>setSelected(channels.map(channel=>channelRow(row.pledgeId,channel)).find(item=>item?.eligible)??row)} className="mt-2 min-h-8 rounded-lg border px-3 text-xs font-bold lg:mt-0">Preview</button></article>})}{!pageRows.length&&<p className="p-8 text-center text-sm text-slate-500">No contributors match these filters.</p>}</div><div className="mt-3 flex flex-col gap-2 text-sm sm:flex-row sm:items-center sm:justify-between"><p>Showing {rows.length?(safePage-1)*pageSize+1:0}–{Math.min(safePage*pageSize,rows.length)} of {rows.length} contributors</p><div className="flex items-center gap-2"><label>Rows <select value={pageSize} onChange={event=>{setPageSize(Number(event.target.value));setPage(1)}} className="rounded-lg border px-2 py-1">{[25,50,100].map(value=><option key={value}>{value}</option>)}</select></label><button disabled={safePage<=1} onClick={()=>setPage(value=>Math.max(1,value-1))} className="rounded-lg border px-3 py-2 disabled:opacity-40">Previous</button><button disabled={safePage>=pageCount} onClick={()=>setPage(value=>Math.min(pageCount,value+1))} className="rounded-lg border px-3 py-2 disabled:opacity-40">Next</button></div></div></>}
    {!preview&&<div className="mt-5 rounded-xl border border-dashed bg-stone-50 p-6 text-center text-sm text-slate-600">Select a meeting and audience, then choose Load Recipients. Loading never sends messages.</div>}
    <MessagePreviewDialog open={Boolean(selected)} title={selected?`Meeting invitation for ${selected.contributor}`:"Meeting invitation"} channel={selected?.channel==="sms"?"SMS":"WhatsApp"} message={selected?.message??""} providerMessage={selected?preview?.provider[selected.channel].message??"":""} providerReady={Boolean(selected&&preview?.provider[selected.channel].configured)} confirmed={false} busy={busy} canSend={false} previewDetails={selected?.channel==="sms"?<div className={`mt-3 rounded-xl p-3 text-sm ${selected.smsSegments===1?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-900"}`}><p><b>{selected.smsEncoding} usage:</b> {selected.smsCharacters} characters, {selected.smsUnits} {selected.smsEncoding==="GSM-7"?"septets":"code units"}</p><p className="mt-1"><b>Estimated SMS segments: {selected.smsSegments}</b></p>{selected.smsSegments>1&&<p className="mt-1">This message exceeds one SMS segment because some meeting details are long.</p>}</div>:selected?.publicMapUrl?<div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900"><a href={selected.publicMapUrl} target="_blank" rel="noreferrer" className="inline-flex rounded-lg bg-emerald-700 px-3 py-2 font-bold text-white">Fungua Ramani</a><p className="mt-2 break-all text-xs">{selected.publicMapUrl}</p></div>:undefined} confirmationLabel={selected?.channel==="sms"?`Estimated SMS segments: ${selected.smsSegments}`:"Template preview only"} sendLabel="Use bulk confirmation to send" onConfirmedChange={()=>{}} onClose={()=>setSelected(null)} onSend={()=>{}}/>
  </section>
}

function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="text-sm font-semibold">{label}<input type={type} value={value} onChange={event=>onChange(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal"/></label>}
