"use client";

import type { FinancialPledge } from "@/services/financialSuiteService";
import { useAppLanguage } from "@/lib/i18n/useAppLanguage";
import { formatAppDate, formatAppNumber, formatAppTzs } from "@/lib/i18n/formatters";
import { FinancialToolbarButton, financialDesktop } from "./FinancialDesktopUI";
import type { ReminderHistoryRow } from "@/services/financialAutomationService";
import SharedEmptyState from "@/components/ui/EmptyState";
import Button from "@/components/ui/Button";

type WorkspaceProps = {
  eventTitle: string; pledges: FinancialPledge[]; visible: FinancialPledge[]; serialByPledgeId: Map<number, number>; isAdmin: boolean;
  query: string; status: string; guestFilter: string; page: number; pages: number; total: number;
  actionPledgeId: number | null;
  communicationHistory: ReminderHistoryRow[];
  onQuery: (value: string) => void; onStatus: (value: string) => void; onGuestFilter: (value: string) => void; onPage: (value: number) => void;
  onCreate: () => void; onImport: () => void; onBulk: () => void; onExport: (title: string, pledges: FinancialPledge[]) => void; onTemplate: () => void;
  onPay: (pledge: FinancialPledge) => void; onCommunicate: (pledge: FinancialPledge, kind: "reminder" | "thank-you", channel?: "sms" | "whatsapp") => void; onHistory: (pledge: FinancialPledge) => void; onEdit: (pledge: FinancialPledge) => void;
  onCancel: (pledge: FinancialPledge) => void; onRestore: (pledge: FinancialPledge) => void; onDelete: (pledge: FinancialPledge) => void;
  onOpenGuest: (pledge: FinancialPledge) => void; onGenerateInvitation: (pledge: FinancialPledge) => void;
};

export function FinancialContributorsWorkspace(props: WorkspaceProps) {
  const { language, t } = useAppLanguage();
  const statusOptions = [["all",t("common.all")],["completed",t("overview.completed")],["partial",t("overview.partial")],["pledged",t("overview.notStarted")],["cancelled",language === "sw" ? "Zilizofutwa" : "Cancelled"]];
  const guestOptions = [["all",t("common.all")],["single",language === "sw" ? "Mtu Mmoja" : "Single"],["double",language === "sw" ? "Watu Wawili" : "Double"],["pending_guest",language === "sw" ? "Inasubiri" : "Pending"],["none",language === "sw" ? "Hakuna" : "None"]];
  return <div className="space-y-4">
    <section className="sep-card overflow-visible">
      <div className="grid gap-3 border-b border-[#ece7df] bg-[#fffdf9] p-4 lg:grid-cols-[minmax(260px,1fr)_180px_180px_auto] lg:items-center">
        <label className="relative"><span className="sr-only">{t("queue.search")}</span><span className="pointer-events-none absolute inset-y-0 left-4 flex items-center text-slate-400"><SearchIcon /></span><input id="pledge-search" value={props.query} onChange={(event)=>props.onQuery(event.target.value)} placeholder={language === "sw" ? "Tafuta jina au simu..." : "Search name or phone..."} className={`w-full pl-12 ${financialDesktop.input}`}/></label>
        <label><span className="sr-only">{language === "sw" ? "Chuja hali" : "Status filter"}</span><select value={props.status} onChange={(event)=>props.onStatus(event.target.value)} className={`w-full ${financialDesktop.input}`}>{statusOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
        <label><span className="sr-only">{language === "sw" ? "Chuja aina ya mgeni" : "Guest filter"}</span><select value={props.guestFilter} onChange={(event)=>props.onGuestFilter(event.target.value)} className={`w-full ${financialDesktop.input}`}>{guestOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
        <div className="flex flex-wrap justify-start gap-2 lg:justify-end"><FinancialToolbarButton icon="upload" onClick={props.onImport}>{t("overview.importExcel")}</FinancialToolbarButton><FinancialToolbarButton icon="plus" tone="primary" onClick={props.onCreate}>{language === "sw" ? "Ongeza Mchangiaji" : "Add Contributor"}</FinancialToolbarButton></div>
      </div>
      <details className="group border-b border-[#ece7df] px-4 py-2"><summary className="cursor-pointer list-none text-xs font-semibold text-slate-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-600">{language === "sw" ? "Vitendo zaidi" : "More actions"}</summary><div className="mt-2 flex flex-wrap gap-2 pb-2"><FinancialToolbarButton icon="layers" tone="attention" onClick={props.onBulk}>{language === "sw" ? "Vitendo vya Wengi" : "Bulk Actions"}</FinancialToolbarButton><FinancialToolbarButton icon="download" onClick={()=>props.onExport(props.eventTitle,props.pledges)}>{language === "sw" ? "Pakua Wachangiaji" : "Export Contributors"}</FinancialToolbarButton><FinancialToolbarButton icon="download" onClick={props.onTemplate}>{language === "sw" ? "Muundo wa Excel" : "Excel Template"}</FinancialToolbarButton></div></details>

      {!props.visible.length ? <SharedEmptyState
        icon={<svg viewBox="0 0 24 24" className="h-8 w-8" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M19 8v6M22 11h-6"/></svg>}
        title={language==="sw"?"Bado hakuna wachangiaji.":"No contributors yet."}
        description={language==="sw"?"Ongeza mchangiaji wako wa kwanza.":"Create your first contributor."}
        action={<Button onClick={props.onCreate}>+ {language==="sw"?"Ongeza Mchangiaji":"Add Contributor"}</Button>}
      /> : <div className="overflow-visible">
        <table className="w-full table-fixed border-separate border-spacing-0 text-left text-sm">
          <caption className="sr-only">{t("financial.contributors")}</caption>
          <thead className="sticky top-0 z-10 bg-[#faf8f4]/95 text-[11px] font-bold uppercase tracking-[0.08em] text-slate-500 backdrop-blur">
            <tr><th scope="col" className="hidden w-14 px-2 py-3 text-center sm:table-cell">#</th><th scope="col" className="w-[45%] px-3 py-3 sm:w-[43%] lg:w-[24%]">{t("eligibility.contributor")}</th><th scope="col" className="hidden w-[14%] px-3 py-3 xl:table-cell">{t("common.phone")}</th><th scope="col" className="hidden px-3 py-3 lg:table-cell lg:w-[24%]">{language === "sw" ? "Maendeleo ya Michango" : "Contribution Progress"}</th><th scope="col" className="hidden w-[12%] px-3 py-3 lg:table-cell">{t("overview.balance")}</th><th scope="col" className="hidden w-[12%] px-3 py-3 lg:table-cell">{language === "sw" ? "Aina ya Mgeni" : "Guest Type"}</th><th scope="col" className="w-[37%] px-3 py-3 sm:w-[22%]">{language === "sw" ? "Hali ya Malipo" : "Payment Status"}</th><th scope="col" className="hidden w-[13%] px-3 py-3 xl:table-cell">{language === "sw" ? "Malipo ya Mwisho" : "Last Payment"}</th><th scope="col" className="w-14 px-2 py-3 text-center">{t("common.actions")}</th></tr>
          </thead>
          <tbody>{props.visible.map((pledge,index)=><ContributorRow key={pledge.id} pledge={pledge} serial={props.serialByPledgeId.get(pledge.id) ?? (props.page-1)*10+index+1} busy={props.actionPledgeId===pledge.id} {...props}/>)}</tbody>
        </table>
      </div>}
      <footer className="flex flex-col gap-3 border-t border-[#ece7df] bg-[#fffdf9] p-4 text-sm sm:flex-row sm:items-center sm:justify-between"><span className="text-slate-600">{formatAppNumber(props.total,language)} {t("financial.contributors").toLowerCase()}</span><div className="flex items-center gap-2"><PageButton disabled={props.page===1} onClick={()=>props.onPage(props.page-1)}>{t("common.previous")}</PageButton><span className="rounded-lg bg-stone-100 px-3 py-2 font-semibold tabular-nums">{props.page} / {props.pages}</span><PageButton disabled={props.page===props.pages} onClick={()=>props.onPage(props.page+1)}>{t("common.next")}</PageButton></div></footer>
    </section>
  </div>;
}

function ContributorRow({pledge,serial,busy,communicationHistory,isAdmin,onPay,onCommunicate,onHistory,onEdit,onCancel,onRestore,onDelete,onOpenGuest,onGenerateInvitation}: WorkspaceProps & {pledge:FinancialPledge;serial:number;busy:boolean}) {
  const {language,t}=useAppLanguage(); const pledged=Number(pledge.pledged_amount); const paid=Number(pledge.total_paid); const balance=Number(pledge.balance); const progress=pledged>0?Math.min(100,Math.max(0,(paid/pledged)*100)):0;
  return <tr className="group relative bg-white transition duration-150 hover:z-[1] hover:bg-emerald-50/30 hover:shadow-[0_5px_18px_rgba(15,118,110,0.08)] focus-within:z-30 focus-within:bg-emerald-50/40">
    <td className="hidden border-t border-[#eee9e1] px-2 py-4 text-center text-xs font-semibold tabular-nums text-slate-400 sm:table-cell">{serial}</td>
    <td className="border-t border-[#eee9e1] px-3 py-4"><div className="flex min-w-0 items-center gap-3"><Avatar name={pledge.full_name}/><div className="min-w-0"><p className="break-words font-bold text-slate-950" title={pledge.full_name}>{pledge.full_name}</p>{pledge.source==="public_pledge_link"&&<span className="mt-1 inline-flex rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-bold text-amber-900">{language==="sw"?"Link ya Ahadi":"Public Pledge Link"}</span>}<p className="mt-0.5 truncate text-xs text-slate-500">{pledge.phone || (language==="sw"?"Hakuna namba ya simu":"No phone number")}</p><p className="mt-0.5 text-xs font-semibold tabular-nums text-slate-600 lg:hidden">{formatAppNumber(progress/100,language,{style:"percent",maximumFractionDigits:0})} · {formatAppTzs(paid,language)} / {formatAppTzs(pledged,language)}</p><CommunicationBadge history={communicationHistory.filter((item)=>item.pledge_id===pledge.id)}/></div></div></td>
    <td className="hidden border-t border-[#eee9e1] px-3 py-4 font-medium tabular-nums text-slate-600 xl:table-cell">{pledge.phone || "—"}</td>
    <td className="hidden border-t border-[#eee9e1] px-3 py-4 lg:table-cell"><ContributionProgress progress={progress} paid={paid} pledged={pledged} balance={balance}/></td>
    <td className="hidden border-t border-[#eee9e1] px-3 py-4 font-bold tabular-nums text-slate-800 lg:table-cell">{formatAppTzs(balance,language)}</td>
    <td className="hidden border-t border-[#eee9e1] px-3 py-4 lg:table-cell"><GuestTypeBadge status={pledge.guest_eligibility_status}/></td>
    <td className="border-t border-[#eee9e1] px-3 py-4"><PaymentStatus status={pledge.calculated_status}/></td>
    <td className="hidden border-t border-[#eee9e1] px-3 py-4 text-slate-600 xl:table-cell"><LastPayment value={pledge.last_payment_at}/></td>
    <td className="border-t border-[#eee9e1] px-2 py-4 text-center"><ActionMenu pledge={pledge} busy={busy} isAdmin={isAdmin} onPay={onPay} onCommunicate={onCommunicate} onHistory={onHistory} onEdit={onEdit} onCancel={onCancel} onRestore={onRestore} onDelete={onDelete} onOpenGuest={onOpenGuest} onGenerateInvitation={onGenerateInvitation} viewLabel={t("common.view")}/></td>
  </tr>;
}

function ContributionProgress({progress,paid,pledged,balance}:{progress:number;paid:number;pledged:number;balance:number}) { const {language}=useAppLanguage(); return <div className="min-w-0"><div className="flex items-center justify-between gap-2 text-xs"><span className="font-bold tabular-nums text-slate-800">{formatAppNumber(progress/100,language,{style:"percent",maximumFractionDigits:0})}</span>{balance<=0&&pledged>0?<span className="hidden font-bold text-emerald-700 sm:inline">✓ {language==="sw"?"Imekamilika":"Complete"}</span>:null}</div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-stone-200" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress)}><div className={`h-full rounded-full ${progress>=100?"bg-emerald-600":progress>0?"bg-amber-500":"bg-slate-300"}`} style={{width:`${progress}%`}}/></div><p className="mt-1.5 truncate text-[11px] font-medium tabular-nums text-slate-500">{formatAppTzs(paid,language)} / {formatAppTzs(pledged,language)}</p><p className="mt-0.5 hidden text-[11px] tabular-nums text-slate-400 sm:block">{language==="sw"?"Salio":"Balance"}: {formatAppTzs(balance,language)}</p></div>; }

function GuestTypeBadge({status}:{status:FinancialPledge["guest_eligibility_status"]}) { const {language}=useAppLanguage(); const config={single:["👤",language==="sw"?"Mtu Mmoja":"Single","bg-emerald-50 text-emerald-700 ring-emerald-200"],double:["👥",language==="sw"?"Watu Wawili":"Double","bg-blue-50 text-blue-700 ring-blue-200"],pending_guest:["●",language==="sw"?"Inasubiri":"Pending","bg-amber-50 text-amber-800 ring-amber-200"]} as const; const [icon,label,tone]=config[status as keyof typeof config]??["⊘",language==="sw"?"Hakuna":"None","bg-stone-100 text-slate-600 ring-stone-200"]; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold ring-1 ring-inset ${tone}`}><span aria-hidden="true">{icon}</span>{label}</span>; }

function PaymentStatus({status}:{status:FinancialPledge["calculated_status"]}) { const {language}=useAppLanguage(); const config={completed:[language==="sw"?"Imekamilika":"Complete","bg-emerald-50 text-emerald-700 ring-emerald-200","bg-emerald-500"],partial:[language==="sw"?"Sehemu":"Partial","bg-amber-50 text-amber-800 ring-amber-200","bg-amber-500"],pledged:[language==="sw"?"Inasubiri":"Pending","bg-rose-50 text-rose-700 ring-rose-200","bg-rose-500"],cancelled:[language==="sw"?"Imefutwa":"Cancelled","bg-stone-100 text-slate-600 ring-stone-200","bg-slate-400"]} as const; const [label,tone,dot]=config[status]; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold ring-1 ring-inset ${tone}`}><span className={`h-1.5 w-1.5 shrink-0 rounded-full ${dot}`} aria-hidden="true"/><span className="break-words">{label}</span></span>; }

function LastPayment({value}:{value:string|null}) { const {language}=useAppLanguage(); if(!value)return <span className="text-slate-400">—</span>; return <time dateTime={value} className="whitespace-nowrap font-semibold">{formatAppDate(value,language,{day:"2-digit",month:"short",year:"numeric"})}</time>; }

type MenuProps=Pick<WorkspaceProps,"onPay"|"onCommunicate"|"onHistory"|"onEdit"|"onCancel"|"onRestore"|"onDelete"|"onOpenGuest"|"onGenerateInvitation">&{pledge:FinancialPledge;busy:boolean;isAdmin:boolean;viewLabel:string};
function ActionMenu({pledge,busy,isAdmin,...actions}:MenuProps) { const {language,t}=useAppLanguage(); const item="flex w-full items-center gap-3 px-4 py-2.5 text-left text-sm font-semibold text-slate-700 hover:bg-stone-50 focus-visible:bg-emerald-50 focus-visible:outline-none disabled:opacity-40"; const protectedHistory=pledge.payment_row_count>0||pledge.has_protected_financial_history; const deleteDisabled=busy||(protectedHistory&&!isAdmin); const run=(callback:(pledge:FinancialPledge)=>void)=>()=>callback(pledge); const completed=pledge.calculated_status==="completed"; const section=(label:string)=><p className="px-4 pb-1 pt-2 text-[10px] font-black uppercase tracking-[.14em] text-slate-400">{label}</p>; const row=(symbol:string,label:string,onClick:()=>void)=><button className={item} onClick={onClick}><span aria-hidden="true" className="w-5 text-center">{symbol}</span>{label}</button>; return <details className="relative inline-block text-left"><summary aria-label={`${t("common.actions")}: ${pledge.full_name}`} className="grid h-10 w-10 cursor-pointer list-none place-items-center rounded-xl border border-[#e7e1d7] bg-white text-xl font-bold text-slate-600 shadow-sm focus-visible:ring-2 [&::-webkit-details-marker]:hidden">⋮</summary><div className="fixed inset-x-3 bottom-3 z-50 max-h-[80vh] overflow-y-auto rounded-t-3xl border bg-white py-2 text-left shadow-2xl md:absolute md:inset-x-auto md:bottom-auto md:right-0 md:top-12 md:w-64 md:rounded-xl"><p className="border-b px-4 py-3 font-bold md:hidden">{pledge.full_name}</p>{section("Details")}{row("◉","Open Contributor",run(actions.onEdit))}{row("✎",t("common.edit"),run(actions.onEdit))}{pledge.calculated_status!=="cancelled"&&<><div className="my-1 border-t"/>{section("Payments")}{!completed&&row("$",t("payments.record"),run(actions.onPay))}{row("▤",t("payments.history"),run(actions.onHistory))}<div className="my-1 border-t"/>{section("Communication")}{!completed&&row("◔","Send Reminder",()=>actions.onCommunicate(pledge,"reminder"))}{completed&&row("♡","Send Thank You",()=>actions.onCommunicate(pledge,"thank-you"))}{row("◌","Send WhatsApp",()=>actions.onCommunicate(pledge,completed?"thank-you":"reminder","whatsapp"))}{row("✉","Send SMS",()=>actions.onCommunicate(pledge,completed?"thank-you":"reminder","sms"))}{completed&&<><div className="my-1 border-t"/>{section("Guest")}{pledge.guest_id&&row("♙","Open Guest",run(actions.onOpenGuest))}{row("▣","Open Invitation",run(actions.onGenerateInvitation))}</>}<div className="my-1 border-t"/><button className={`${item} text-red-700`} onClick={run(actions.onCancel)}>⌫ {language==="sw"?"Futa":"Delete Contributor"}</button></>}{pledge.calculated_status==="cancelled"&&<>{row("↻","Restore",run(actions.onRestore))}<button className={`${item} text-red-700`} disabled={deleteDisabled} onClick={run(actions.onDelete)}>Delete Permanently</button></>}</div></details>; }

function CommunicationBadge({history}:{history:ReminderHistoryRow[]}) { const latest=[...history].sort((a,b)=>b.created_at.localeCompare(a.created_at))[0]; if(!latest)return null; const failed=latest.delivery_status==="failed"; const thanked=latest.reminder_type==="pledge_thank_you"; const acknowledged=latest.reminder_type==="pledge_acknowledgement"; const today=new Date(latest.created_at).toDateString()===new Date().toDateString(); const label=failed?"Delivery Failed":thanked?"Thank You Sent":acknowledged?"Acknowledgement Sent":today?"Reminder Sent Today":"Reminder Sent"; return <span title={`${new Date(latest.created_at).toLocaleString()} · ${latest.channel} · ${latest.delivery_status}`} className={`mt-1.5 inline-flex rounded-full px-2 py-0.5 text-[10px] font-bold ${failed?"bg-red-50 text-red-700":thanked||acknowledged?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800"}`}>● {label}</span>; }

function Avatar({name}:{name:string}) { const initials=name.trim().split(/\s+/).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"?"; return <span aria-hidden="true" className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-gradient-to-br from-emerald-600 to-teal-700 text-xs font-black text-white shadow-sm">{initials}</span>; }
function PageButton({children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button type="button" {...props} className="min-h-10 rounded-lg border border-stone-200 bg-white px-3 font-semibold shadow-sm hover:bg-stone-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-600 disabled:opacity-40">{children}</button>; }
function SearchIcon(){return <svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>;}
